theory Factor_Set_Frontier_Generation
  imports Factor_Learned_Execution_Soundness
begin

section \<open>Generated finite relations are inputs to the same premise join\<close>

fun finite_premise_set_joins where
  "finite_premise_set_joins [] C={|({||},{||})|}"
| "finite_premise_set_joins ((s,d,p)#ps) C=ffUnion (fimage (\<lambda>(V,H).
    fimage (\<lambda>(e,t). (V |\<union>| finite_matching_bindings p t,finsert (s,e,t) H))
      (ffilter (\<lambda>(e,t). e=d \<and> finite_pattern_accepts p t \<and>
        finite_relation_functional (V |\<union>| finite_matching_bindings p t)) C))
    (finite_premise_set_joins ps C))"

lemma finite_premise_set_joins_member:
  "(V,H) |\<in>| finite_premise_set_joins ps (fset_of_list C) \<longleftrightarrow>
    (V,H)\<in>set (finite_premise_joins ps C)"
proof (induction ps arbitrary: V H)
  case Nil
  then show ?case by simp
next
  case (Cons a ps)
  obtain s d p where shape: "a=(s,d,p)" by (cases a) auto
  show ?case using Cons.IH
    by (auto simp: shape fset_of_list.rep_eq split: prod.splits; force)
qed

lemma finite_premise_set_joins_lists:
  "finite_premise_set_joins ps (fset_of_list C)=fset_of_list (finite_premise_joins ps C)"
proof (rule fset_inject[THEN iffD1], rule set_eqI)
  fix x
  show "x\<in>fset (finite_premise_set_joins ps (fset_of_list C)) \<longleftrightarrow>
    x\<in>fset (fset_of_list (finite_premise_joins ps C))"
    by (cases x) (simp add: finite_premise_set_joins_member fset_of_list.rep_eq)
qed

definition finite_schema_generation_on_set where
  "finite_schema_generation_on_set S ps C=
    (if finite_schema_formed S \<and> set ps=fset (finite_schema_premises S) then
      ffUnion (fimage (\<lambda>(V,H). fimage (\<lambda>t. (t,V,H))
        (ffilter (\<lambda>t. finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V)
          (finite_pattern_values V (finite_schema_conclusion S))))
        (finite_premise_set_joins ps C))
     else {||})"

lemma finite_schema_generation_on_lists [simp]:
  "finite_schema_generation_on_set S ps (fset_of_list C)=finite_schema_generation S ps C"
  by (simp only: finite_schema_generation_on_set_def finite_schema_generation_def finite_premise_set_joins_lists)

definition finite_generated_applications_on_set where
  "finite_generated_applications_on_set L C=ffUnion (fimage (\<lambda>(d,S,ps).
    fimage (\<lambda>(t,V,H). (d,S,t,V,H)) (finite_schema_generation_on_set S ps C)) (fset_of_list L))"

definition finite_generated_rules_on_set where
  "finite_generated_rules_on_set L C=fimage (\<lambda>(d,S,t,V,H). ((d,t),H))
    (finite_generated_applications_on_set L C)"

lemma finite_generated_applications_on_lists [simp]:
  "finite_generated_applications_on_set L (fset_of_list C)=finite_generated_schema_applications L C"
  by (simp add: finite_generated_applications_on_set_def finite_generated_schema_applications_def)

lemma finite_generated_rules_on_lists [simp]:
  "finite_generated_rules_on_set L (fset_of_list C)=finite_generated_schema_rules L C"
  by (simp add: finite_generated_rules_on_set_def finite_generated_schema_rules_def)

definition finite_learned_investigation_on_set where
  "finite_learned_investigation_on_set L C K goals=
    (let applications=finite_generated_applications_on_set L C;
         rules=finite_generated_rules_on_set L C;
         formed=finite_schema_library_formed L \<and>
           fBall C (\<lambda>q. finite_term_formed (snd q)) \<and>
           fBall K (\<lambda>q. finite_term_formed (snd q)) \<and>
           fBall goals (\<lambda>(i,q). finite_term_formed (snd q)) \<and> finite_premise_functional goals
     in (formed,applications,finite_inference_residual rules K goals,
       finite_inference_demand rules K (fimage snd goals),
       finite_inference_demand_reasons rules K (fimage snd goals)))"

theorem finite_learned_investigation_on_lists:
  "finite_learned_investigation_on_set L (fset_of_list C) K goals=finite_learned_investigation L C K goals"
  by (simp add: finite_learned_investigation_on_set_def finite_learned_investigation_def Let_def fset_of_list.rep_eq)

lemma finite_generated_set_conclusion_formed:
  assumes generated: "(q,H) |\<in>| finite_generated_rules_on_set L C"
  shows "finite_term_formed (snd q)"
proof -
  obtain cs where enumeration: "fset_of_list cs=C" using exists_fset_of_list by blast
  have old: "(q,H) |\<in>| finite_generated_schema_rules L cs"
    using generated by (simp only: enumeration[symmetric] finite_generated_rules_on_lists)
  obtain S ps V where member: "(fst q,S,ps)\<in>set L"
    and inst: "(snd q,V,H) |\<in>| finite_schema_generation S ps cs"
    using old by (simp only: finite_generated_schema_rule) blast
  have decoded: "schema_instance (decode_finite_schema S) (decode_finite_term_bindings V)
    (decode_finite_term (snd q)) (decode_finite_premises H)"
    using finite_schema_generation_sound(1)[OF inst] by (simp only: finite_schema_instance_correct)
  show ?thesis using schema_instance_formed[OF decoded] by (simp only: finite_term_formed_correct; blast)
qed

theorem finite_generated_set_closure_sound:
  assumes library: "\<And>d S ps t. (d,S,ps)\<in>set L \<Longrightarrow>
      schema_rule_instance (decode_finite_schema S) (positive_meaning P) t \<Longrightarrow> (d,t)\<in>positive_meaning P"
    and known: "image decode_finite_call_term (fset K)\<subseteq>positive_meaning P"
  shows "image decode_finite_call_term (finite_inference_result (finite_generated_rules_on_set L C) K)
    \<subseteq>positive_meaning P"
proof -
  obtain cs where enumeration: "fset_of_list cs=C" using exists_fset_of_list by blast
  show ?thesis using finite_learned_closure_sound[OF library known, where C=cs]
    by (simp only: enumeration[symmetric] finite_generated_rules_on_lists)
qed

text \<open>
  The finite-set interface has exactly the original complete applications,
  bindings, premise occurrences, residuals, demand, and reasons on every list
  presentation. Its soundness reuses the original generator and inference
  contracts. Frontier rows have no separate occurrence identity; the original
  premise sockets and submitted goal occurrences retain theirs.
\<close>

end
