session RRA_Factor_Structural_Bootstrap = HOL +
  options [document = false]
  sessions "HOL-Library"
  directories "theories"
  theories
    Bootstrap_Relations
    Bootstrap_Finite_Closure
    RRA_Core
    RRA_Data
    RRA_Data_Views
    RRA_Footprint
    RRA_Exact
    RRA_Finite_Artifacts
    RRA_Representation_Audit
    RRA_Environment
    RRA_Finite_Environments
    RRA_Fresh_Uses
    RRA_Source_Clone
    RRA_Structural_Syntax
    RRA_Executable_Syntax
    RRA_Executable_Records
    RRA_Executable_Citations
    RRA_Executable_Retention
    RRA_Read_Transport
    RRA_Binding_Extension
    RRA_Syntax_Construction
    RRA_Syntax_Forests
    RRA_Literal_Extension
    RRA_Bound_Syntax_Construction
    RRA_Scope_Construction
    RRA_Syntax_Composition
    RRA_Bound_Forests
    RRA_Citation_Closure
    RRA_Read_Environment
    RRA_Evidence
    RRA_Generation
    RRA_Generation_Dependencies
    RRA_Generation_Transport
    RRA_Generation_Frames
    RRA_Generation_Construction
    RRA_Selection
    RRA_Publication
    RRA_Publication_Dependencies
    RRA_Transaction
    Factor_Structure
    Factor_Terms
    Factor_Executable_Terms
    Factor_Quotation
    Factor_Executable_Quotation
    Factor_Term_Encoding
    Factor_Material_Observation
    Factor_Executable_Material
    Factor_Executable_Instances
    Factor_Executable_Schemas
    Factor_Executable_Systems
    Factor_Executable_Graphs
    Factor_Executable_Readings
    Factor_Executable_Propagation
    Factor_Executable_Recovery
    Factor_Executable_Graph_Representation
    Factor_Patterns
    Factor_Executable_Patterns
    Factor_Material_Patterns
    Factor_Schemas
    Factor_Interfaces
    Factor_Executable_Matching
    Factor_Schema_Renaming
    Factor_Alpha_Semantics
    Factor_System_Clauses
    Factor_System_Renaming
    Factor_Presentation
    Factor_Executable_Scopes
    Factor_Executable_Calls
    Factor_Executable_References
    Factor_Executable_Tables
    Factor_Executable_Metadata
    Factor_Executable_Realization
    Factor_Executable_Replay_Retention
    Factor_Executable_Replay
    Factor_Executable_Material_Syntax
    Factor_Executable_Families
    Factor_Executable_Premises
    Factor_Executable_Definitions
    Factor_Executable_Packages
    Factor_Executable_Positions
    Factor_Executable_Dependencies
    Factor_Scoped_Transport
    Factor_Syntax_Boundaries
    Factor_Native_Transport
    Factor_Cloned_Transport
    Factor_Packages
    Factor_Applications
    Factor_Application_Encoding
    Factor_Presentation_Dependencies
    Factor_Presentation_Restriction
    Factor_Package_Dependencies
    Factor_Package_Locality
    Factor_Pattern_Encoding
    Factor_Prospective_Encoding
    Factor_Pattern_Forests
    Factor_Material_Encoding
    Factor_Record_Construction
    Factor_Premise_Construction
    Factor_Premise_Forests
    Factor_Schema_Bodies
    Factor_Reference_Tables
    Factor_Interface_Construction
    Factor_Reference_Forests
    Factor_Reference_Environments
    Factor_Reference_Packages
    Factor_Root_Syntax
    Factor_Root_Environments
    Factor_Schema_Frames
    Factor_Schema_Lists
    Factor_Schema_Encoding
    Factor_Schema_Compilation
    Factor_Schema_Totality
    Factor_Syntax_Copy
    Factor_Schema_Code
    Factor_Schema_Forests
    Factor_Definition_Frames
    Factor_Definition_Encoding
    Factor_Definition_Compilation
    Factor_Definition_Code
    Factor_Definition_Environments
    Factor_Program_Construction
    Factor_Schema_Environments
    Factor_Positive_Meaning
    Factor_Pattern_Programs
    Factor_System_Alpha
    Factor_System_Relocation
    Factor_Program_Semantics
    Factor_Program_Compilation
    Factor_Positive_Locality
    Factor_Positive_Parametricity
    Factor_Material_Meaning
    Factor_Native_Meaning
    Factor_Native_Equality
    Factor_Resource_Sensitivity
    Factor_Native_Incidence
    Factor_Future_Applications
    Factor_Compiled_Applications
    Factor_Finite_Relations
    Factor_Seeded_Closure
    Factor_Incidence_Queries
    Factor_View_Definitions
    Factor_Derivation
    RRA_Fragment
    RRA_Assembly
    Factor_Construction
    Factor_Finite_Terms
    Factor_Finite_Presentations
    Factor_Self_Contained_Terms
    Factor_Distinct_Payloads
    Factor_Data_Comparison
    Factor_Bag_Comparison
    Factor_List_Profiles
    Factor_Related_Bags
    Factor_Complete_Data_Quotation
    Factor_Artifact_Values
    Factor_Artifact_Comparison
    Factor_Material_Data_Projection
    Factor_Artifact_Admission
    Factor_Environment_Values
    Factor_Environment_Comparison
    Factor_Coordinate_Admission
    Factor_Keyed_Lists
    Factor_Environment_Admission
    Factor_Judgment_Values
    Factor_Judgment_Scopes
    Factor_Construction_Claims
    Factor_Construction_Presentations
    Factor_Construction_Recovery
    Factor_Construction_Omissions
    Factor_Native_Construction
    Factor_Cause
    Factor_Construction_Permission_Examples
    Factor_Derivation_Graphs
    Factor_Derivation_Recovery
    Factor_Proof_Positions
    Factor_Proof_Flattening
    Factor_Graph_Renaming
    Factor_Graph_Transport
    Factor_Program_Positions
    Factor_Graph_Metadata
    Factor_Native_References
    Factor_Native_Tables
    Factor_Proof_Metadata
    Factor_Realization
    Factor_Application_Retention
    Factor_Judgment_Retention
    Factor_Generation_Scopes
    Factor_Base_Cause
    Factor_Certified_Base_Cause
    Factor_Base_Programs
    Factor_Recorded_Cause
    Factor_Generation_Causes
    Factor_Proof_Restriction
    Factor_Proof_Retention
    Factor_Proof_Inclusion
    Factor_Proof_Reachability
    Factor_Replay_Retention
    Factor_Replay
    Factor_Certified_Construction
    Factor_Certified_Cause
    Factor_Certified_Recorded_Cause
    Factor_Generation_Construction
    Factor_Proof_Evidence
    Factor_Proof_Copy
    Factor_Proof_Rows
    RRA_Syntax_Families
    RRA_Syntax_Records
    RRA_Collection_Frames
    RRA_Collection_References
    RRA_Collection_Selections
    RRA_Publication_Construction
    Factor_Record_Syntax
    Factor_Table_Assembly
    Factor_Proof_Row_Copy
    Factor_Table_Syntax
    Factor_Proof_Tables
    Factor_Table_Copy
    Factor_Proof_Table_Copy
    Factor_Proof_Node_Construction
    Factor_Proof_Node_Code
    Factor_Graph_Construction
    Factor_Native_Proofs
    Factor_Encoding_Order_Audit
    Factor_Construction_Order_Audit
    Factor_Rule_Instances
    SK_Reduction
    Factor_SK_Program
    Factor_SK
    Factor_Native_SK
    SK_Abstraction
    Lambda_Closures
    SK_Lambda_Compilation
    SK_Numerals
    Factor_Lambda
    SK_Confluence
    SK_Lambda_Results
    Lambda_Substitution
    Lambda_Reduction
    Lambda_Confluence
    SK_Lambda_Interpretation
    SK_Lambda_Reflection
    Lambda_Closure_Interpretation
    Lambda_Head_Evaluation
    Lambda_Applications
    Lambda_Standardization
    Lambda_Termination
    SK_Lambda_Termination
    Factor_Coordinate_Values
    Factor_Target_Values
    Factor_Generation_Values
    Factor_Publication_Values
    Factor_Site_Values
    Factor_Publication_Scopes
    Factor_Adoption_Values
    Factor_Authority
    Factor_Native_Authority
    Factor_Authority_Programs
    Factor_Authority_Scopes
    Factor_Certified_Authority
    Factor_Authority_Independence
    Factor_Transaction_Values
    Factor_Continuation_Values
    Factor_Continuation
    Factor_Native_Continuation
    Factor_Continuation_Programs
    Factor_Certified_Continuation
    RRA_Binding_Omissions
    Factor_Package_Omissions
    Factor_Continuation_Omissions
    Factor_Program_Scopes
    Factor_Current_Values
    Factor_Current_Scopes
    Factor_Generation_Programs
    Factor_Current_Programs
    Factor_Program_Generation_Causes
    Factor_Definition_Closure
    Factor_Current_Entries
    Factor_Amendment_Values
    Factor_Amendment
    Factor_Native_Amendment
    Factor_Current_Entry_Construction
    Factor_Amendment_Programs
    Factor_Program_Changes
    Factor_Amendment_Domains
    Factor_Program_Change_Examples
    Factor_Correspondence_Reports
    Factor_Comparison_Reports
    Factor_Report_Programs
    Factor_Report_Patterns
    Factor_Amendment_Reports
    Factor_Report_Examples
    Factor_Current_Companions
    Factor_Current_Continuation
    Factor_Replay_Values
    Factor_Replay_Scopes
    Factor_Current_Certificates
    Factor_Predecessor_Continuation
    Factor_Continuation_Selection_Examples
