session RRA_Factor_Structural_Bootstrap = HOL +
  options [document = false]
  sessions "HOL-Library"
  directories "theories"
  theories
    Presentation_Classes
    Presentation_Relations
    Presentation_Closure
    Bootstrap_Relations
    Bootstrap_Finite_Closure
    RRA_Core
    RRA_Data
    RRA_Data_Views
    RRA_Footprint
    RRA_Exact
    RRA_Finite_Artifacts
    RRA_Representation_Audit
    RRA_Environment
    RRA_Finite_Environments
    RRA_Fresh_Uses
    RRA_Source_Clone
    RRA_Structural_Syntax
    RRA_Record_Chains
    RRA_Executable_Syntax
    RRA_Executable_Records
    RRA_Executable_Citations
    RRA_Executable_Retention
    RRA_Read_Transport
    RRA_Binding_Extension
    RRA_Syntax_Construction
    RRA_Syntax_Forests
    RRA_Literal_Extension
    RRA_Bound_Syntax_Construction
    RRA_Scope_Construction
    RRA_Syntax_Composition
    RRA_Bound_Forests
    RRA_Citation_Closure
    RRA_Read_Environment
    RRA_Evidence
    RRA_Generation
    RRA_Generation_Dependencies
    RRA_Generation_Transport
    RRA_Generation_Frames
    RRA_Generation_Construction
    RRA_Selection
    RRA_Publication
    RRA_Publication_Dependencies
    RRA_Transaction
    Factor_Structure
    Factor_Terms
    Factor_Executable_Terms
    Factor_Quotation
    Factor_Executable_Quotation
    Factor_Term_Encoding
    Factor_Material_Observation
    Factor_Executable_Material
    Factor_Executable_Instances
    Factor_Executable_Schemas
    Factor_Executable_Systems
    Factor_Executable_Graphs
    Factor_Executable_Readings
    Factor_Executable_Propagation
    Factor_Executable_Recovery
    Factor_Executable_Graph_Representation
    Factor_Patterns
    Factor_Executable_Patterns
    Factor_Material_Patterns
    Factor_Schemas
    Factor_Interfaces
    Factor_Executable_Matching
    Factor_Schema_Renaming
    Factor_Alpha_Semantics
    Factor_System_Clauses
    Factor_System_Renaming
    Factor_Presentation
    Factor_Executable_Scopes
    Factor_Executable_Calls
    Factor_Executable_References
    Factor_Executable_Tables
    Factor_Executable_Metadata
    Factor_Executable_Realization
    Factor_Executable_Replay_Retention
    Factor_Executable_Replay
    Factor_Executable_Material_Syntax
    Factor_Executable_Families
    Factor_Executable_Premises
    Factor_Executable_Definitions
    Factor_Executable_Packages
    Factor_Executable_Positions
    Factor_Executable_Dependencies
    Factor_Scoped_Transport
    Factor_Syntax_Boundaries
    Factor_Native_Transport
    Factor_Cloned_Transport
    Factor_Packages
    Factor_Applications
    Factor_Application_Encoding
    Factor_Presentation_Dependencies
    Factor_Presentation_Restriction
    Factor_Package_Dependencies
    Factor_Package_Locality
    Factor_Pattern_Encoding
    Factor_Prospective_Encoding
    Factor_Pattern_Forests
    Factor_Material_Encoding
    Factor_Record_Construction
    Factor_Premise_Construction
    Factor_Premise_Forests
    Factor_Schema_Bodies
    Factor_Reference_Tables
    Factor_Interface_Construction
    Factor_Reference_Forests
    Factor_Reference_Environments
    Factor_Reference_Packages
    Factor_Root_Syntax
    Factor_Root_Environments
    Factor_Schema_Frames
    Factor_Schema_Lists
    Factor_Schema_Encoding
    Factor_Schema_Compilation
    Factor_Schema_Totality
    Factor_Syntax_Copy
    Factor_Schema_Code
    Factor_Schema_Forests
    Factor_Definition_Frames
    Factor_Definition_Encoding
    Factor_Definition_Compilation
    Factor_Definition_Code
    Factor_Definition_Environments
    Factor_Program_Construction
    Factor_Schema_Environments
    Factor_Positive_Meaning
    Factor_Pattern_Programs
    Factor_System_Alpha
    Factor_System_Relocation
    Factor_Program_Semantics
    Factor_Program_Compilation
    Factor_Positive_Locality
    Factor_System_Unions
    Factor_Positive_Parametricity
    Factor_Material_Meaning
    Factor_Native_Meaning
    Factor_Native_Equality
    Factor_Resource_Sensitivity
    Factor_Native_Incidence
    Factor_Future_Applications
    Factor_Compiled_Applications
    Factor_Finite_Relations
    Factor_Seeded_Closure
    Factor_Incidence_Queries
    Factor_View_Definitions
    Factor_Pattern_Families
    Factor_Tagged_Views
    Factor_Historical_Views
    Factor_Derivation
    RRA_Fragment
    RRA_Assembly
    Factor_Construction
    Factor_Finite_Terms
    Factor_Finite_Presentations
    Factor_Self_Contained_Terms
    Factor_Distinct_Payloads
    Factor_Data_Comparison
    Factor_Bag_Comparison
    Factor_List_Profiles
    Factor_Related_Bags
    Factor_Complete_Data_Quotation
    Factor_Complete_Data_Recognition
    Factor_Artifact_Values
    Factor_Artifact_Comparison
    Factor_Material_Data_Projection
    Factor_Artifact_Admission
    Factor_Environment_Values
    Factor_Environment_Comparison
    Factor_Coordinate_Admission
    Factor_Keyed_Lists
    Factor_Environment_Admission
    Factor_Key_Fibres
    Factor_Headed_Material
    Factor_Family_Admission
    Factor_Record_Admission
    Factor_Target_Admission
    Factor_Citation_Admission
    Factor_Environment_Lookup
    Factor_Citation_Resolution
    Factor_Citation_Interpretation
    Factor_Citation_Reading
    Factor_Anchored_Admission
    Factor_Target_Projection
    Factor_Data_List_Operations
    Factor_Data_Collection_Operations
    Factor_Quotation_Admission
    Factor_Binding_Admission
    Factor_Binder_Admission
    Factor_Pattern_Instantiation
    Factor_Scoped_Instantiation
    Factor_Prospective_Instantiation
    Factor_Application_Reading
    Factor_Row_Values
    Factor_Vector_Instantiation
    Factor_Record_Instantiation
    Factor_Material_Instantiation
    Factor_Premise_Instances
    Factor_Premise_Row_Instantiation
    Factor_Premise_Family_Instantiation
    Factor_Schema_Instantiation
    Factor_Material_Checking
    Factor_Schema_Material_Checking
    Factor_Schema_Admission
    Factor_Schema_Family_Admission
    Factor_Definition_Call_Admission
    Factor_Schema_Callee_Inclusion
    Factor_Definition_Callee_Inclusion
    Factor_Package_Closure_Admission
    Factor_Located_List
    Factor_Root_Family_Reading
    Factor_Package_Admission
    Factor_Definition_Clause_Reading
    Factor_Definition_Edge_Reading
    Factor_Package_Membership
    Factor_Program_Call_Admission
    Factor_Application_Admission
    Factor_Program_Call_List
    Factor_Admitted_Instantiation
    Factor_Boundary_Lists
    Factor_Site_Citation_Reading
    Factor_Site_Link_Reading
    Factor_Application_Vector
    Factor_Site_Link_Vector
    Factor_Table_Reading_Profiles
    Factor_Binding_Table_Reading
    Factor_Discharge_Table_Reading
    Factor_Proof_Node_Reading
    Factor_Finite_Graph_Order
    Factor_Proof_Graph_Bounds
    Factor_Proof_Link_Checking
    Factor_Proof_Bound_Values
    Factor_Proof_Bound_Checking
    Factor_Proof_Graph_Admission
    Factor_Proof_Graph_Membership
    Factor_Row_Qualification
    Factor_Keyed_Row_Join
    Factor_Proof_Claim_Values
    Factor_Proof_Claim_Instances
    Factor_Proof_Claim_Checking
    Factor_Derivation_Admission
    Factor_Slot_Observations
    Factor_Premise_Slot_Reading
    Factor_Schema_Slot_Reading
    Factor_Definition_Slot_Reading
    Factor_Retention_Observations
    Factor_Replay_Source_Reading
    Factor_Replay_Slot_Reading
    Factor_Replay_Coverage
    Factor_Retention_Admission
    Factor_Replay_Admission
    Factor_Environment_Inclusion
    Factor_Positive_Admission
    Factor_Program_Reflection
    Factor_Judgment_Values
    Factor_Judgment_Scopes
    Factor_Construction_Claims
    Factor_Construction_Presentations
    Factor_Construction_Recovery
    Factor_Construction_Omissions
    Factor_Native_Construction
    Factor_Cause
    Factor_Construction_Permission_Examples
    Factor_Derivation_Graphs
    Factor_Derivation_Recovery
    Factor_Proof_Positions
    Factor_Proof_Flattening
    Factor_Graph_Renaming
    Factor_Graph_Transport
    Factor_Program_Positions
    Factor_Positioned_Instances
    Factor_Graph_Metadata
    Factor_Native_References
    Factor_Native_Tables
    Factor_Table_Metadata
    Factor_Proof_Metadata
    Factor_Realization
    Factor_Application_Retention
    Factor_Judgment_Retention
    Factor_Generation_Scopes
    Factor_Base_Cause
    Factor_Certified_Base_Cause
    Factor_Base_Programs
    Factor_Recorded_Cause
    Factor_Generation_Causes
    Factor_Proof_Restriction
    Factor_Proof_Retention
    Factor_Proof_Inclusion
    Factor_Proof_Reachability
    Factor_Replay_Retention
    Factor_Replay
    Factor_Certified_Construction
    Factor_Certified_Cause
    Factor_Certified_Recorded_Cause
    Factor_Generation_Construction
    Factor_Proof_Evidence
    Factor_Proof_Copy
    Factor_Proof_Rows
    RRA_Syntax_Families
    RRA_Syntax_Records
    RRA_Collection_Frames
    RRA_Collection_References
    RRA_Collection_Selections
    RRA_Publication_Construction
    Factor_Record_Syntax
    Factor_Table_Assembly
    Factor_Table_Enumeration
    Factor_Proof_Row_Copy
    Factor_Table_Syntax
    Factor_Proof_Tables
    Factor_Table_Copy
    Factor_Proof_Table_Copy
    Factor_Proof_Node_Construction
    Factor_Proof_Node_Code
    Factor_Graph_Construction
    Factor_Native_Proofs
    Factor_Encoding_Order_Audit
    Factor_Construction_Order_Audit
    Factor_Rule_Instances
    SK_Reduction
    Factor_SK_Program
    Factor_SK
    Factor_Native_SK
    SK_Abstraction
    Lambda_Closures
    SK_Lambda_Compilation
    SK_Numerals
    Factor_Lambda
    SK_Confluence
    SK_Lambda_Results
    Lambda_Substitution
    Lambda_Reduction
    Lambda_Confluence
    SK_Lambda_Interpretation
    SK_Lambda_Reflection
    Lambda_Closure_Interpretation
    Lambda_Head_Evaluation
    Lambda_Applications
    Lambda_Standardization
    Lambda_Termination
    SK_Lambda_Termination
    Factor_Coordinate_Values
    Factor_Citation_Values
    Factor_Target_Values
    Factor_Generation_Values
    Factor_Publication_Values
    Factor_Site_Values
    Factor_Publication_Scopes
    Factor_Adoption_Values
    Factor_Authority
    Factor_Native_Authority
    Factor_Authority_Programs
    Factor_Authority_Scopes
    Factor_Certified_Authority
    Factor_Authority_Independence
    Factor_Transaction_Values
    Factor_Continuation_Values
    Factor_Continuation
    Factor_Native_Continuation
    Factor_Continuation_Programs
    Factor_Certified_Continuation
    RRA_Binding_Omissions
    Factor_Package_Omissions
    Factor_Continuation_Omissions
    Factor_Program_Scopes
    Factor_Historical_Programs
    Factor_Current_Values
    Factor_Current_Scopes
    Factor_Generation_Programs
    Factor_Current_Programs
    Factor_Program_Generation_Causes
    Factor_Definition_Closure
    Factor_Current_Entries
    Factor_Amendment_Values
    Factor_Amendment
    Factor_Native_Amendment
    Factor_Current_Entry_Construction
    Factor_Amendment_Programs
    Factor_Program_Changes
    Factor_Amendment_Domains
    Factor_Program_Change_Examples
    Factor_Correspondence_Reports
    Factor_Comparison_Reports
    Factor_Report_Programs
    Factor_Report_Patterns
    Factor_Report_Families
    Factor_Copy_Reports
    Factor_Amendment_Reports
    Factor_Report_Examples
    Factor_Current_Companions
    Factor_Current_Continuation
    Factor_Replay_Values
    Factor_Replay_Scopes
    Factor_Current_Certificates
    Factor_Predecessor_Continuation
    Factor_Continuation_Selection_Examples
    Factor_Transition_Values
    Factor_Current_Acceptance_Certificates
    Factor_Continuation_Envelopes
    Factor_Transition_Selection
    Factor_Transition_Examples
    Factor_Current_Construction
    Factor_Current_Construction_Certificates
    Factor_Generation_Replay_Causes
    Factor_Predecessor_Assembly
    Factor_Assembly_Support
    Factor_Transition_Accounts
    Factor_Transition_Account_Examples
    Factor_Site_Permission
    Factor_Current_Site_Permission
    Factor_Current_Site_Certificates
    Factor_Amendment_Dependencies
    Factor_Dependency_Support
    Factor_Dependency_Evidence
    Factor_Transition_Dependencies
    Factor_Dependency_Evidence_Examples
    RRA_Assembly_Reuse
    Factor_Construction_Reuse
    RRA_Replacement
    Factor_Current_Entry_Publications
    Factor_Transition_Construction_Examples
    Factor_Program_Entry_Values
    Factor_Comparison_Support
    Factor_Amendment_Comparisons
    Factor_Transition_Comparisons
    Factor_Transition_Comparison_Examples
    Factor_Interpretation_Support
    Factor_Amendment_Interpretations
    Factor_Represented_Interpretations
    Factor_Transition_Interpretations
    Factor_Interpretation_Retention
    Factor_Interpretation_Construction
    Factor_Pattern_Determination
    Factor_Schema_Determination
    Factor_Native_Syntax_Determination
    Factor_Scope_Forwarding
    Factor_Scope_Admission
    Factor_Scope_Interpreters
    Factor_Interpreter_Admission
    Factor_Package_Source_Reading
    Factor_Package_Slot_Reading
    Factor_Package_Coverage
    Factor_Package_Retention_Admission
    Factor_Complete_Data_Admission
    Factor_Presentation_Classes
    Factor_Finite_Set_Presentations
    Factor_Target_Presentations
    Factor_Constrained_Readings
    Factor_Program_Scope_Reading
    Factor_Schema_Observations
    Factor_Reference_Bindings
    Factor_Schema_Reading
    Factor_Reader_Clauses
    Factor_Single_Clause_Reading
    Factor_Constrained_Contracts
    Factor_Reader_Contracts
    Factor_Judgment_Presentations
    Factor_Derivation_Presentations
    Factor_Replay_Presentations
    Factor_Replay_Reading
    Factor_Replay_Self_Presentation
    Factor_Generation_Presentations
    Factor_Generation_Scope_Presentations
    Presentation_Transport
    Presentation_Contracts
    Factor_Presentation_Transport
    Factor_Bag_Presentations
    Factor_System_Composition
    Factor_Separated_Lists
    Factor_Bag_Difference
    Factor_Artifact_Difference
    Factor_Target_Comparison
    Factor_Comparison_Programs
    Bag_Difference_Witnesses
    Factor_System_Restriction
    Factor_Recursive_Groups
    Factor_Related_Difference
    Factor_Generation_Clauses
    Factor_Generation_Equations
    Factor_Generation_Admission
    Factor_Generation_Contracts
    Factor_Generation_Value_Programs
    Bag_Readings
    Factor_Related_Lists
    RRA_Generation_Lists
    Factor_Generation_Source_Base
    Factor_Generation_Source_Clauses
    Factor_Generation_Field_Admission
    Factor_Generation_Source_Equations
    Factor_Generation_Source_Admission
    Factor_Generation_Predecessor_Admission
    Factor_Generation_Source_Contracts
    Factor_Quoted_Artifacts
    Factor_Transported_Readings
    Factor_Context_Clauses
    Factor_Context_Admission
    Factor_Scope_Reading_Base
    Factor_Judgment_Scope_Reading
    Factor_Program_Scope_Reports
    Factor_Scope_Programs
    Factor_Generation_Program_Presentations
    Factor_Generation_Scope_Base
    Factor_Generation_Scope_Clauses
    Factor_Generation_Scope_Admission
    Factor_Generation_Scope_Contracts
    Factor_Environment_Inclusion_Contracts
    Factor_Generation_Retention_Presentations
    Factor_Generation_Retention_Base
    Factor_Generation_Dependency_Clauses
    Factor_Generation_Read_Sites
    Factor_Generation_Citation_Roots
    Factor_Generation_Requests
    Factor_Generation_Retention_Admission
    Factor_Generation_Dependency_Contracts
    Factor_Generation_Retention_Contracts
    Factor_Judgment_Retention_Presentations
    Factor_Judgment_Retention_Base
    Factor_Judgment_Retention_Clauses
    Factor_Judgment_Source_Admission
    Factor_Judgment_Dependency_Reading
    Factor_Judgment_Retention_Admission
    Factor_Judgment_Dependency_Contracts
    Factor_Judgment_Retention_Contracts
    Factor_Base_Admission
    Factor_Base_Admission_Contracts
    Factor_Base_Cause_Base
    Factor_Base_Cause_Clauses
    Factor_Base_Cause_Contracts
    Factor_Base_Cause_Presentations
    Factor_Recorded_Base_Admission
    Factor_Collection_Comparisons
    Factor_Structural_Collections
    Factor_Fragment_Presentations
    Factor_Fragment_Enumerations
    Factor_Context_Filters
    Factor_Fragment_Clauses
    Factor_Fragment_Equations
    Factor_Fragment_Predicates
    Factor_Fragment_Filters
    Factor_Fragment_Admission
    Factor_Fragment_Projections
    Factor_Fragment_Contracts
    Factor_Table_Presentations
    Factor_Table_Admission_Profiles
    Factor_Assembly_Presentations
    Factor_Structural_Table_Clauses
    Factor_Structural_Table_Admission
    Factor_Structural_Table_Contracts
    Presentation_Contract_Constructions
    Factor_Related_List_Maps
    RRA_Data_Enumerations
    Factor_Assembly_Enumerations
    List_Relation_Folds
    Factor_List_Folds
    Factor_Data_Flattening
    Factor_Data_Flattening_Contracts
