theory Allocated_Environment_Execution
  imports Allocated_Environment_Presentation Finite_Term_Object_Words RRA_Allocated_Environment_Investigation Factor_Executable_Artifact_Values Native_Execution_Refinements
begin

setup \<open>Finite_Observation_Contracts.export @{term allocated_update_investigation}\<close>

export_code allocated_environment_report_value allocated_environment_report_selections finite_term_shared_word_fold allocated_update_packet allocated_update_indices allocated_update_inspect
  allocated_environment_chain_report allocated_environment_chain_paths allocated_environment_view raw_allocated_environment
  Allocate_Artifact Add_Allocated_Binding finite_environment_artifacts finite_environment_bindings
  finite_artifact_rows Finite_Whole Finite_Anchor fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Allocated_Environment_Execution file_prefix allocated_environment

end
