theory Builtin_Investigation_Execution
 imports Factor_Investigation_Input_Investigation Factor_Observation_Collection_Investigation Factor_Observation_Investigation Factor_Observation_Scope_Investigation Factor_Observation_Table_Investigation Factor_Pair_Scope_Investigation Factor_Permission_Investigation Factor_Proof_Probe_Investigation Factor_Reasoning_Method_Investigation Factor_Schema_Socket_Investigation Factor_Substitution_Investigation Finite_Investigation_Interface Native_Execution_Refinements Observation_Revision_Investigation Presentation_Completion_Investigation
   Builtin_Investigation_Presentation
begin

setup \<open>Finite_Observation_Contracts.export @{term reasoning_method_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term input_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term revision_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term table_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term pair_scope_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term collection_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term scope_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term observation_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term completion_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term permission_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term pattern_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term proof_probes_investigation}\<close>
setup \<open>Finite_Observation_Contracts.export @{term schema_sockets_investigation}\<close>

export_code builtin_investigation_report_value builtin_investigation_selections finite_term_shared_word_fold investigation_inference investigation_basis investigation_repairs investigation_extend investigation_revision nat_of_integer integer_of_nat reasoning_method_investigation reasoning_method_investigation_observations reasoning_method_investigation_relation input_investigation input_investigation_observations input_investigation_relation revision_investigation revision_investigation_observations revision_investigation_relation table_investigation table_investigation_observations table_investigation_relation pair_scope_investigation pair_scope_investigation_observations pair_scope_investigation_relation collection_investigation collection_investigation_observations collection_investigation_relation scope_investigation scope_investigation_observations scope_investigation_relation observation_investigation observation_investigation_observations observation_investigation_relation completion_investigation completion_investigation_observations completion_investigation_relation permission_investigation permission_investigation_observations permission_investigation_relation pattern_investigation pattern_investigation_observations pattern_investigation_relation proof_probes_investigation proof_probes_investigation_observations proof_probes_investigation_relation schema_sockets_investigation schema_sockets_investigation_observations schema_sockets_investigation_relation
 in Eval module_name Finite_Investigation file_prefix "builtin_investigations"

end
