theory Checked_Requirement_Execution
  imports Checked_Requirement_Execution_Base Native_Execution_Refinements
begin

export_code checked_requirement_source checked_requirement_reports
  admission_sequence admission_sequence_reports portable_requirement_reports
  portable_requirement_execution portable_table_diagnostics portable_table_goals
  Existing_Admission Paired_Admission Collected_Admission Pair_Admission_Instruction List_Admission_Instruction
  Finite_Payload Finite_Pair Finite_Target Finite_Whole finite_empty_artifact
  finite_reasoning_term_equal nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Requirement_Plans file_prefix checked_requirement_plans

end
