theory Concurrent_Replay_Execution
  imports Factor_Parallel_Packet_Cycles Parallel_Assessment_Execution Factor_Packet_Stages Factor_Packet_Source_Projections Factor_Primary_Computed_Cause_Execution Factor_Packet_Observation_Readings Factor_Prepared_Replay_Assessments Ordered_Environment_Artifact_Objects Complete_Object_References Factor_Shared_Replay_Construction Finite_Collection_Equality_Execution Factor_Nested_Replay_Identity Finite_Shared_Inspection_Rows Shared_Digit_Replay_Execution Finite_Sorted_Set_Execution Factor_Finite_Accumulated_Data_Syntax RRA_Ordered_Artifact_Formation Factor_Ordered_Target_Equality Finite_Relation_Functionality_Execution Complete_Artifact_References Factor_Constructed_Cause_Cache Factor_Prepared_Replay_Inspections Native_Execution_Refinements
begin

setup \<open>Finite_Observation_Contracts.export @{term digit_replay_investigation}\<close>

export_code replay_stage_table replay_stage_compare replay_stage_cycles replay_table_sources read_assessed_observation prepared_replay_family_assessor complete_environment_artifact_objects complete_empty_artifacts complete_object_reference complete_object_table_rows finite_environment_artifacts complete_artifact_reference digit_replay_packet digit_replay_indices digit_replay_inspect digit_replay_family_inspect
  digit_replay_subject_view digit_replay_source_scope digit_replay_source_cases digit_replay_source_equal
  digit_replay_initial_material_source digit_replay_literal_sources digit_replay_history_sources
  digit_replay_chain_length literal_replay_seed literal_replay_family required_history_seed_replays
  required_history_case generation_record_case raw_required_history
  required_history_source required_history_source_use required_history_source_root required_history_goals
  required_history_entry required_history_policy required_history_policy_use required_history_material required_history_members
  finite_environment_artifact_rows finite_environment_bindings finite_artifact_rows
  finite_system_interfaces finite_system_clauses finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_source finite_material_atoms finite_material_edges finite_material_counts finite_material_functions
  finite_graph_inferences finite_graph_discharges
  generation_locus generation_predecessors generation_payload generation_cause
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target History_Step
  Schema_Proof Finite_Inference Finite_Assertion Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  Existing_Admission Paired_Admission Collected_Admission fset set nat_of_integer integer_of_nat
 complete_term_reference complete_empty_terms
  in Eval module_name Digit_Replay_Execution file_prefix concurrent_replay

end
