theory Concurrent_History_Execution
  imports Concurrent_History_Presentation Finite_Term_Word_Streaming Factor_Parallel_Packet_Cycles Parallel_Assessment_Execution Factor_Packet_Stages Factor_Packet_Source_Projections Factor_Success_Shared_History Factor_Known_History_Control_Construction Factor_Packet_Observation_Readings Ordered_Environment_Artifact_Objects Complete_Object_References Factor_Constructed_Original_History_Execution Factor_Shared_History_Construction Finite_Collection_Equality_Execution Factor_Nested_History_Identity Finite_Shared_Inspection_Rows Shared_Constructed_History_Execution Finite_Sorted_Set_Execution Factor_Finite_Accumulated_Data_Syntax RRA_Ordered_Artifact_Formation Factor_Ordered_Target_Equality Finite_Relation_Functionality_Execution Complete_Artifact_References Finite_Prepared_Reader_Inspections Native_Execution_Refinements
    Parallel_History_Source_Rows
begin

setup \<open>Finite_Observation_Contracts.export @{term constructed_history_investigation}\<close>

export_code concurrent_history_report_value concurrent_history_report_selections finite_term_shared_word_fold history_stage_table history_stage_compare history_stage_cycles history_table_sources read_assessed_observation complete_environment_artifact_objects complete_empty_artifacts complete_object_reference complete_object_table_rows finite_environment_artifacts complete_artifact_reference constructed_history_packet digit_history_indices digit_history_question_inspect digit_history_view digit_history_state_view
  digit_history_subject_view bounded_history_subject_view digit_history_source_scope digit_history_source_cases
  digit_history_source_equal digit_history_source_index digit_history_chain_length
  raw_digit_required_history raw_required_history required_history_source required_history_source_use
  required_history_source_root required_history_goals required_history_entry required_history_policy
  required_history_policy_use required_history_material required_history_members
  generation_locus generation_payload generation_cause generation_predecessors
  finite_artifact_rows finite_environment_artifact_rows finite_environment_bindings
  History_Step Schema_Proof Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  Existing_Admission Paired_Admission Collected_Admission fset set nat_of_integer integer_of_nat
 complete_term_reference complete_empty_terms
  in Eval module_name Digit_History_Execution file_prefix concurrent_history

end
