theory Data_Reading_Execution
  imports Data_Reading_Presentation Finite_Term_Object_Words Factor_Data_Reading_Investigation Factor_Executable_Artifact_Values Factor_Data_Reading_Fixture Native_Execution_Refinements
begin

setup \<open>Finite_Observation_Contracts.export @{term data_reading_investigation}\<close>

export_code data_reading_report_value data_reading_report_selections finite_term_shared_word_fold data_reading_packet data_reading_indices data_reading_inspect
  data_reading_fixture_packet Schema_Proof
  finite_complete_data_readings finite_complete_data_readings_prepared
  finite_complete_data_root_candidates finite_complete_data_readings_at_roots
  finite_artifact_rows finite_enumerated_artifact
  Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Data_Reading_Execution file_prefix data_reading

end
