theory Digit_Replay_Execution
  imports Finite_Term_Object_Words Concurrent_Replay_Presentation Factor_Digit_Replay_Investigation Factor_Executable_Environment_Values
    Factor_Finite_Judgment_Reading_Sharing Factor_Digit_Replay_Reading_Sharing Factor_Structural_Replay_Identity RRA_Generation_Child_Row_Images Native_Execution_Refinements
begin

declare digit_replay_packet_parallel_stages_code[code]
  digit_replay_report_concurrent_code[code]

setup \<open>Finite_Observation_Contracts.export @{term digit_replay_investigation}\<close>

export_code digit_replay_report_value digit_replay_report_selections finite_term_shared_word_fold digit_replay_packet digit_replay_indices digit_replay_inspect digit_replay_family_inspect
  digit_replay_subject_view digit_replay_source_scope digit_replay_source_cases digit_replay_source_equal
  digit_replay_initial_material_source digit_replay_literal_sources digit_replay_history_sources
  digit_replay_chain_length literal_replay_seed literal_replay_family required_history_seed_replays
  required_history_case generation_record_case raw_required_history
  required_history_source required_history_source_use required_history_source_root required_history_goals
  required_history_entry required_history_policy required_history_policy_use required_history_material required_history_members
  finite_environment_artifact_rows finite_environment_bindings finite_artifact_rows
  finite_system_interfaces finite_system_clauses finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_source finite_material_atoms finite_material_edges finite_material_counts finite_material_functions
  finite_graph_inferences finite_graph_discharges
  generation_locus generation_predecessors generation_payload generation_cause
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target History_Step
  Schema_Proof Finite_Inference Finite_Assertion Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  Existing_Admission Paired_Admission Collected_Admission fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Digit_Replay_Execution file_prefix digit_replay

end
