theory Factor_Schema_Generation_Rows
  imports Factor_Schema_Generation Finite_Functional_Enumeration
begin

lemma finite_schema_instance_unique_conclusion:
  assumes first: "finite_schema_instance S V x H"
    and second: "finite_schema_instance S V y K"
  shows "x=y"
proof -
  have functional: "single_valued (decode_finite_term_bindings V)"
    and x: "pattern_instance (decode_finite_term_bindings V)
      (decode_finite_pattern (finite_schema_conclusion S)) (decode_finite_term x)"
    and y: "pattern_instance (decode_finite_term_bindings V)
      (decode_finite_pattern (finite_schema_conclusion S)) (decode_finite_term y)"
    using first second by (auto simp: finite_schema_instance_correct schema_instance_def
      term_bindings_formed_def)
  show ?thesis using pattern_instance_unique[OF functional x y] by simp
qed

definition finite_generation_head where
  "finite_generation_head S V H=finite_singleton_option
    (ffilter (\<lambda>t. finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V)
      (finite_pattern_instances V (finite_schema_conclusion S)))"

lemma finite_generation_head_exact:
  "finite_generation_head S V H=Some t \<longleftrightarrow>
    finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V"
proof -
  have unique: "x=y" if
    "x |\<in>| ffilter (\<lambda>t. finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V)
      (finite_pattern_instances V (finite_schema_conclusion S))"
    "y |\<in>| ffilter (\<lambda>t. finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V)
      (finite_pattern_instances V (finite_schema_conclusion S))" for x y
    by (rule finite_schema_instance_unique_conclusion) (use that in auto)
  show ?thesis unfolding finite_generation_head_def
    by (simp only: finite_singleton_option_member[OF unique])
      (auto simp: finite_pattern_instances_member finite_schema_instance_def)
qed

lemma finite_generation_head_reversed:
  "Some t=finite_generation_head S V H \<longleftrightarrow>
    finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V"
  by (subst eq_commute) (rule finite_generation_head_exact)

definition finite_schema_generation_rows where
  "finite_schema_generation_rows S ps K=(if finite_schema_formed S \<and>
      set ps=fset (finite_schema_premises S) then
    concat (map (\<lambda>(V,H). case finite_generation_head S V H of
      None \<Rightarrow> [] | Some t \<Rightarrow> [(t,V,H)]) (finite_premise_joins ps K)) else [])"

lemma finite_schema_generation_rows_member:
  "(t,V,H)\<in>set (finite_schema_generation_rows S ps K) \<longleftrightarrow>
    finite_schema_formed S \<and> set ps=fset (finite_schema_premises S) \<and>
    (V,H)\<in>set (finite_premise_joins ps K) \<and>
    finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V"
  by (auto simp: finite_schema_generation_rows_def split_def
    finite_generation_head_exact finite_generation_head_reversed
    split: option.splits if_splits)

lemma finite_schema_generation_complete_member:
  "(t,V,H) |\<in>| finite_schema_generation S ps K \<longleftrightarrow>
    finite_schema_formed S \<and> set ps=fset (finite_schema_premises S) \<and>
    (V,H)\<in>set (finite_premise_joins ps K) \<and>
    finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V"
proof
  assume generated: "(t,V,H) |\<in>| finite_schema_generation S ps K"
  show "finite_schema_formed S \<and> set ps=fset (finite_schema_premises S) \<and>
    (V,H)\<in>set (finite_premise_joins ps K) \<and>
    finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V"
    using generated by (auto simp: finite_schema_generation_def split_def
      fset_of_list.rep_eq split: if_splits)
next
  assume parts: "finite_schema_formed S \<and> set ps=fset (finite_schema_premises S) \<and>
    (V,H)\<in>set (finite_premise_joins ps K) \<and>
    finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V"
  let ?heads="\<lambda>V H. ffilter (\<lambda>t. finite_schema_instance S V t H \<and>
    finite_schema_material_satisfied S V) (finite_pattern_instances V (finite_schema_conclusion S))"
  have head: "t |\<in>| ?heads V H"
    using parts by (auto simp: finite_pattern_instances_member finite_schema_instance_def)
  have inner: "(t,V,H) |\<in>| fimage (\<lambda>x. (x,V,H)) (?heads V H)"
    by (rule fimageI[OF head])
  have joined: "(V,H) |\<in>| fset_of_list (finite_premise_joins ps K)"
    using parts by (simp only: fset_of_list.rep_eq; blast)
  have family: "fimage (\<lambda>x. (x,V,H)) (?heads V H) |\<in>|
      fimage (\<lambda>(V,H). fimage (\<lambda>x. (x,V,H)) (?heads V H))
        (fset_of_list (finite_premise_joins ps K))"
    using fimageI[OF joined, of "\<lambda>(V,H). fimage (\<lambda>x. (x,V,H)) (?heads V H)"] by simp
  have collected: "(t,V,H) |\<in>| ffUnion (fimage (\<lambda>(V,H).
      fimage (\<lambda>x. (x,V,H)) (?heads V H)) (fset_of_list (finite_premise_joins ps K)))"
    using family inner by (simp only: ffUnion_membership; blast)
  show "(t,V,H) |\<in>| finite_schema_generation S ps K"
    using parts collected by (simp add: finite_schema_generation_def)
qed

theorem finite_schema_generation_rows_exact:
  "set (finite_schema_generation_rows S ps K)=fset (finite_schema_generation S ps K)"
  by (auto simp only: set_eq_iff split_paired_All finite_schema_generation_rows_member
    finite_schema_generation_complete_member)

definition finite_schema_ordered_generation ::
  "('a,'s::linorder,'d) finite_factor_schema \<Rightarrow> ('d\<times>finite_factor_term) list \<Rightarrow>
    (finite_factor_term\<times>(('a\<times>finite_factor_term) fset\<times>
      ('s\<times>('d\<times>finite_factor_term)) fset)) list" where
  "finite_schema_ordered_generation S K=finite_schema_generation_rows S
    (finite_functional_rows (finite_schema_premises S)) K"

theorem finite_schema_ordered_generation_sound:
  assumes member: "(t,V,H)\<in>set (finite_schema_ordered_generation S K)"
  shows "finite_schema_instance S V t H" "finite_schema_material_satisfied S V"
    "\<forall>s d x. (s,d,x) |\<in>| H \<longrightarrow> (d,x)\<in>set K"
  using member unfolding finite_schema_ordered_generation_def
    finite_schema_generation_rows_exact
  by (rule finite_schema_generation_sound)+

text \<open>
  This is an ordered presentation of the existing schema generator, with the
  same complete result set. Only identified premise sockets are ordered.
  A complete binding determines at most one conclusion; the original instance
  and material checks are retained before selecting that singleton. Repeated
  premise choices remain separate list occurrences.
\<close>

end
