theory Factor_Native_Generation_Semantics
  imports Factor_Native_Generation
begin

lemma finite_program_generation_rows_admitted:
  assumes "((d,c),(t,V,H))\<in>set (finite_program_generation_rows P K)"
  shows "finite_admitted_schema_instance P d c V t H"
  using assms by (auto simp: finite_program_generation_rows_def)

theorem finite_program_generation_rows_sound:
  assumes formed: "finite_system_formed P"
    and known: "\<And>e y. (e,y)\<in>set K \<Longrightarrow>
      (e,decode_finite_term y)\<in>positive_meaning (decode_finite_system P)"
    and generated: "((d,c),(t,V,H))\<in>set (finite_program_generation_rows P K)"
  shows "(d,decode_finite_term t)\<in>positive_meaning (decode_finite_system P)"
proof -
  have inst: "admitted_schema_instance (decode_finite_system P) d c
    (decode_finite_term_bindings V) (decode_finite_term t) (decode_finite_premises H)"
    using finite_program_generation_rows_admitted[OF generated]
    by (simp only: finite_admitted_schema_instance_correct)
  have support: "\<forall>s e y. (s,e,y) |\<in>| H \<longrightarrow> (e,y)\<in>set K"
    using finite_program_generation_rows_origin[OF formed generated] by blast
  have children: "\<forall>s e y. (s,e,y)\<in>decode_finite_premises H \<longrightarrow>
      (e,y)\<in>positive_meaning (decode_finite_system P)"
    using support known by (auto simp: decode_finite_premises_value_member)
  show ?thesis by (rule positive_meaning_step[OF inst children])
qed

lemma finite_native_generation_fields:
  assumes result: "finite_native_generation E u r x=Some (P,D,A,rows)"
  shows "finite_native_source E u r=Some P"
    "D=finite_program_term_demand P {|x|}"
    "finite_native_program_evaluation E u r D=Some (P,A)"
    "rows=finite_program_generation_rows P (finite_native_seed_rows P x A)"
proof -
  obtain Q where source: "finite_native_source E u r=Some Q"
    and demand: "D=finite_program_term_demand Q {|x|}"
    and evaluated: "finite_native_program_evaluation E u r D=Some (P,A)"
    and rows: "rows=finite_program_generation_rows P (finite_native_seed_rows P x A)"
    using result by (auto simp: finite_native_generation_def Let_def
      split: option.splits prod.splits)
  have actual: "finite_native_source E u r=Some P"
    using evaluated by (simp only: finite_native_program_evaluation_conditions
      finite_native_source_correct; blast)
  have equal: "Q=P" using actual source by simp
  show "finite_native_source E u r=Some P" "D=finite_program_term_demand P {|x|}"
    "finite_native_program_evaluation E u r D=Some (P,A)"
    "rows=finite_program_generation_rows P (finite_native_seed_rows P x A)"
    using actual demand evaluated rows by (simp_all only: equal)
qed

theorem finite_native_generation_sound:
  assumes result: "finite_native_generation E u r x=Some (P,D,A,rows)"
    and generated: "((d,c),(t,V,H))\<in>set rows"
  shows "native_package_at (decode_finite_environment E) u r (decode_finite_system P)"
    "(d,decode_finite_term t)\<in>positive_meaning (decode_finite_system P)"
proof -
  have source: "finite_native_source E u r=Some P"
    and demand: "D=finite_program_term_demand P {|x|}"
    and evaluated: "finite_native_program_evaluation E u r D=Some (P,A)"
    and rows: "rows=finite_program_generation_rows P (finite_native_seed_rows P x A)"
    by (rule finite_native_generation_fields[OF result])+
  show package: "native_package_at (decode_finite_environment E) u r (decode_finite_system P)"
    using source by (simp only: finite_native_source_correct)
  have formed: "finite_system_formed P"
    using native_package_system_formed[OF package] by (simp only: finite_system_formed_correct)
  have known: "(e,decode_finite_term y)\<in>positive_meaning (decode_finite_system P)"
    if "(e,y)\<in>set (finite_native_seed_rows P x A)" for e y
    using that finite_native_program_evaluation_exact(2)[OF evaluated]
    by (auto simp: finite_native_seed_rows_def)
  have row: "((d,c),(t,V,H))\<in>set (finite_program_generation_rows P (finite_native_seed_rows P x A))"
    using generated by (simp only: rows)
  show "(d,decode_finite_term t)\<in>positive_meaning (decode_finite_system P)"
    by (rule finite_program_generation_rows_sound[OF formed known row])
qed

theorem finite_generated_outputs_sound:
  assumes result: "finite_native_generation E u r x=Some (P,D,A,rows)"
    and selected: "y\<in>set (finite_generated_outputs entry x rows)"
  shows "(entry,Pair_Term (decode_finite_term x) (decode_finite_term y))
    \<in>positive_meaning (decode_finite_system P)"
proof -
  obtain c V H where generated: "((entry,c),(Finite_Pair x y,V,H))\<in>set rows"
    using selected by (simp only: finite_generated_outputs_member; blast)
  show ?thesis using finite_native_generation_sound(2)[OF result generated] by simp
qed

end
