theory Factor_Reference_Tables
  imports Factor_Schema_Bodies
begin

section \<open>Finite compatible reference tables generated by syntax construction\<close>

definition reference_table_formed ::
  "(local_address \<times> exact_artifact) set \<Rightarrow> (local_address \<times> 'a) set \<Rightarrow> bool" where
  "reference_table_formed L C \<longleftrightarrow> finite (socket_sum L C) \<and>
    single_valued (socket_sum L C) \<and> (\<forall>k R. (k,R) \<in> L \<longrightarrow> exact_formed R)"

lemma reference_table_properties:
  assumes "reference_table_formed L C"
  shows "finite L" "finite C" "single_valued L" "single_valued C"
    "rel_dom L \<inter> rel_dom C = {}" "\<forall>k R. (k,R) \<in> L \<longrightarrow> exact_formed R"
  using assms by (auto simp only: reference_table_formed_def socket_sum_finite socket_sum_single_valued)

lemma reference_table_empty [simp]: "reference_table_formed {} {}"
  by (simp only: reference_table_formed_def socket_sum_finite socket_sum_single_valued)
     (simp add: single_valued_def)

lemma reference_table_literals:
  assumes "finite L" "single_valued L" "\<forall>k R. (k,R) \<in> L \<longrightarrow> exact_formed R"
  shows "reference_table_formed L {}"
  using assms by (simp only: reference_table_formed_def socket_sum_finite socket_sum_single_valued)
     (simp add: single_valued_def)

lemma reference_table_callees:
  assumes "finite C" "single_valued C"
  shows "reference_table_formed {} C"
  using assms by (simp only: reference_table_formed_def socket_sum_finite socket_sum_single_valued)
     (simp add: single_valued_def)

lemma mapped_reference_sum:
  "socket_sum (map_slot_keys f L) (map_slot_keys f C) = map_slot_keys f (socket_sum L C)"
  by (simp add: socket_sum_def map_slot_keys_def image_Un image_image split_def)

lemma reference_table_map:
  assumes formed: "reference_table_formed L C" and injective: "inj f"
  shows "reference_table_formed (map_slot_keys f L) (map_slot_keys f C)"
proof -
  have sv: "single_valued (socket_sum L C)" and fin: "finite (socket_sum L C)"
    using formed by (auto simp: reference_table_formed_def)
  have inj: "inj_on f (rel_dom (socket_sum L C))" using injective by (auto simp: inj_on_def)
  have mapped: "single_valued (map_slot_keys f (socket_sum L C))"
    using single_valued_pair_image[OF sv inj, where g=id] by (simp add: map_slot_keys_def)
  show ?thesis using mapped fin formed
    by (simp only: reference_table_formed_def mapped_reference_sum) (auto simp: map_slot_keys_def)
qed

lemma socket_sum_unions:
  "socket_sum (L\<union>A) (C\<union>B) = socket_sum L C \<union> socket_sum A B"
  by (auto simp: socket_sum_def)

lemma reference_table_union:
  assumes first: "reference_table_formed L C" and second: "reference_table_formed A B"
    and separate: "(rel_dom L \<union> rel_dom C) \<inter> (rel_dom A \<union> rel_dom B) = {}"
  shows "reference_table_formed (L\<union>A) (C\<union>B)"
proof -
  have lsv: "single_valued (socket_sum L C)" and rsv: "single_valued (socket_sum A B)"
    using first second by (auto simp: reference_table_formed_def)
  have disjoint: "rel_dom (socket_sum L C) \<inter> rel_dom (socket_sum A B) = {}"
    using separate by simp
  have cross: "\<forall>x y z. (x,y) \<in> socket_sum L C \<longrightarrow> (x,z) \<in> socket_sum A B \<longrightarrow> y=z"
  proof (intro allI impI)
    fix x y z assume left: "(x,y) \<in> socket_sum L C" and right: "(x,z) \<in> socket_sum A B"
    have a: "x \<in> rel_dom (socket_sum L C)" by (rule rel_domI[OF left])
    have b: "x \<in> rel_dom (socket_sum A B)" by (rule rel_domI[OF right])
    show "y=z" using disjoint a b by blast
  qed
  have sv: "single_valued (socket_sum L C \<union> socket_sum A B)"
    using single_valued_union_iff[OF lsv rsv] cross by blast
  show ?thesis using first second sv
    by (auto simp: reference_table_formed_def socket_sum_unions)
qed

lemma reference_table_prefix_union:
  assumes first: "reference_table_formed L C" and second: "reference_table_formed A B"
    and left_boundary: "(rel_dom L \<union> rel_dom C) \<inter> binder_addresses = {}"
    and right_boundary: "(rel_dom A \<union> rel_dom B) \<inter> binder_addresses = {}"
  shows "reference_table_formed
    (map_slot_keys (syntax_prefix 2) L \<union> map_slot_keys (syntax_prefix 3) A)
    (map_slot_keys (syntax_prefix 2) C \<union> map_slot_keys (syntax_prefix 3) B)"
proof -
  have left_inj: "inj (syntax_prefix 2)" and right_inj: "inj (syntax_prefix 3)"
    by (rule syntax_prefix_injective, simp)+
  have left: "reference_table_formed (map_slot_keys (syntax_prefix 2) L) (map_slot_keys (syntax_prefix 2) C)"
    by (rule reference_table_map[OF first left_inj])
  have right: "reference_table_formed (map_slot_keys (syntax_prefix 3) A) (map_slot_keys (syntax_prefix 3) B)"
    by (rule reference_table_map[OF second right_inj])
  have separate: "(rel_dom (map_slot_keys (syntax_prefix 2) L) \<union> rel_dom (map_slot_keys (syntax_prefix 2) C)) \<inter>
    (rel_dom (map_slot_keys (syntax_prefix 3) A) \<union> rel_dom (map_slot_keys (syntax_prefix 3) B)) = {}"
    by (simp only: map_slot_keys_domain image_Un[symmetric]
        syntax_prefix_image_outside[OF left_boundary] syntax_prefix_image_outside[OF right_boundary]) auto
  show ?thesis by (rule reference_table_union[OF left right separate])
qed

text \<open>
  A forest over placements that are injective and whose images are apart has formed reference tables
  when each child has.
\<close>

lemma reference_table_placed:
  assumes len: "length Ls = length Cs"
    and profiles: "\<forall>i<length Ls. reference_table_formed (Ls!i) (Cs!i)"
    and injective: "\<And>i. inj (g i)" and apart: "\<And>i j. i \<noteq> j \<Longrightarrow> range (g i) \<inter> range (g j) = {}"
  shows "reference_table_formed (placed_table g Ls) (placed_table g Cs)"
proof -
  let ?L = "\<lambda>n. \<Union>i<n. map_slot_keys (g i) (Ls!i)"
  let ?C = "\<lambda>n. \<Union>i<n. map_slot_keys (g i) (Cs!i)"
  have prefix: "n \<le> length Ls \<Longrightarrow> reference_table_formed (?L n) (?C n)" for n
  proof (induction n)
    case 0
    then show ?case by simp
  next
    case (Suc n)
    have old: "reference_table_formed (?L n) (?C n)" using Suc.IH Suc.prems by simp
    have small: "n < length Ls" using Suc.prems by simp
    have new: "reference_table_formed (map_slot_keys (g n) (Ls!n)) (map_slot_keys (g n) (Cs!n))"
      by (rule reference_table_map[OF _ injective]) (use profiles small in blast)
    have separated: "range (g i) \<inter> range (g n) = {}" if "i < n" for i
      using that by (intro apart) simp
    have below: "rel_dom (?L n) \<union> rel_dom (?C n) \<subseteq> (\<Union>i<n. range (g i))"
      unfolding rel_dom_image image_UN
      by (intro Un_least UN_mono subset_refl) (auto simp: map_slot_keys_def)
    have here: "rel_dom (map_slot_keys (g n) (Ls!n)) \<union> rel_dom (map_slot_keys (g n) (Cs!n)) \<subseteq> range (g n)"
      by (auto simp: map_slot_keys_domain)
    have separate: "(rel_dom (map_slot_keys (g n) (Ls!n)) \<union> rel_dom (map_slot_keys (g n) (Cs!n)))
      \<inter> (rel_dom (?L n) \<union> rel_dom (?C n)) = {}"
      using below here separated by blast
    have union: "reference_table_formed (map_slot_keys (g n) (Ls!n) \<union> ?L n) (map_slot_keys (g n) (Cs!n) \<union> ?C n)"
      by (rule reference_table_union[OF new old separate])
    show ?case using union by (simp only: lessThan_Suc UN_insert)
  qed
  show ?thesis using prefix[of "length Ls"] len by (simp add: placed_table_eq)
qed

lemma template_reference_table:
  assumes formed: "template_formed t"
  shows "reference_table_formed (template_literals t) (template_callees t)"
proof (cases t)
  case (Inl dp)
  obtain d p where shape: "dp=(d,p)" by (cases dp)
  have pf: "pattern_formed p" using formed Inl shape by simp
  have literal_targets: "\<forall>k R. (k,R) \<in> pattern_literal_bindings p \<longrightarrow> exact_formed R"
    by (rule pattern_literal_bindings_formed[OF pf])
  have base: "reference_table_formed (pattern_literal_bindings p) {}"
    by (rule reference_table_literals[OF pattern_literal_bindings_finite pattern_literal_bindings_functional literal_targets])
  have left: "reference_table_formed (map_slot_keys (Cons 3) (pattern_literal_bindings p)) {}"
    using reference_table_map[OF base, of "Cons 3"] by (simp add: map_slot_keys_def)
  have right: "reference_table_formed {} {([2,4],d)}"
    by (rule reference_table_callees) (auto simp: single_valued_def)
  have separate: "(rel_dom (map_slot_keys (Cons 3) (pattern_literal_bindings p)) \<union> rel_dom {}) \<inter>
    (rel_dom {} \<union> rel_dom {([2,4],d)}) = {}"
    by (auto simp: map_slot_keys_def rel_dom_def)
  show ?thesis using reference_table_union[OF left right separate] by (simp add: Inl shape)
next
  case (Inr M)
  have fields: "\<forall>p\<in>set (material_fields M). pattern_formed p"
    using formed Inr by (simp add: material_pattern_formed_def)
  have literal_targets: "\<forall>k R. (k,R) \<in> pattern_forest_bindings (material_fields M) \<longrightarrow> exact_formed R"
    by (rule pattern_forest_bindings_formed[OF fields])
  show ?thesis by (simp only: Inr template_literals.simps template_callees.simps)
    (rule reference_table_literals[OF pattern_forest_bindings_finite pattern_forest_bindings_functional literal_targets])
qed

lemma premise_forest_reference_table:
  assumes formed: "\<forall>t\<in>set ts. template_formed t"
  shows "reference_table_formed (premise_forest_literals ts) (premise_forest_callees ts)"
  unfolding premise_forest_literals_def premise_forest_callees_def
proof (rule reference_table_placed[OF _ _ syntax_branch_injective syntax_branch_disjoint])
  show "length (map template_literals ts) = length (map template_callees ts)" by simp
  show "\<forall>i<length (map template_literals ts). reference_table_formed (map template_literals ts ! i) (map template_callees ts ! i)"
  proof (intro allI impI)
    fix i assume "i < length (map template_literals ts)"
    then have i: "i < length ts" by simp
    have "template_formed (ts!i)" using formed nth_mem[OF i] by blast
    then show "reference_table_formed (map template_literals ts ! i) (map template_callees ts ! i)"
      using i by (simp add: template_reference_table)
  qed
qed

lemma template_callee_range_left:
  "rel_ran (template_callees (Inl dp)) = {fst dp}"
  by (cases dp) (auto simp: rel_ran_def)

lemma premise_forest_callee_range:
  "rel_ran (premise_forest_callees ts) = (\<Union>t\<in>set ts. rel_ran (template_callees t))"
proof (rule set_eqI, rule iffI)
  fix d assume "d \<in> rel_ran (premise_forest_callees ts)"
  then obtain a where "(a,d) \<in> premise_forest_callees ts" by (auto simp: rel_ran_def)
  then obtain i k where i: "i < length ts" and kd: "(k,d) \<in> template_callees (ts!i)"
    unfolding premise_forest_callees_def placed_table_member by auto
  show "d \<in> (\<Union>t\<in>set ts. rel_ran (template_callees t))"
    unfolding rel_ran_def using nth_mem[OF i] kd by blast
next
  fix d assume "d \<in> (\<Union>t\<in>set ts. rel_ran (template_callees t))"
  then obtain t k where t: "t \<in> set ts" and kd: "(k,d) \<in> template_callees t" by (auto simp: rel_ran_def)
  obtain j where "(j,d) \<in> premise_forest_callees ts" using premise_forest_callee_origin[OF t kd] by blast
  then show "d \<in> rel_ran (premise_forest_callees ts)" unfolding rel_ran_def by blast
qed

lemma (in schema_bodies) reference_table:
  "reference_table_formed literals callees"
proof -
  have literal_targets: "\<forall>k R. (k,R) \<in> pattern_literal_bindings p \<longrightarrow> exact_formed R"
    by (rule pattern_literal_bindings_formed[OF conclusion_formed])
  have head: "reference_table_formed (pattern_literal_bindings p) {}"
    by (rule reference_table_literals[OF pattern_literal_bindings_finite pattern_literal_bindings_functional literal_targets])
  have tail: "reference_table_formed (premise_forest_literals ts) (premise_forest_callees ts)"
    by (rule premise_forest_reference_table[OF templates_formed])
  have outside: "(rel_dom (pattern_literal_bindings p) \<union> rel_dom {}) \<inter> binder_addresses = {}"
    using pattern_literal_slots_outside[of p] by simp
  show ?thesis using reference_table_prefix_union[OF head tail outside premise_forest_reference_slots_outside]
    by (simp add: schema_body_literals_def schema_body_callees_def map_slot_keys_def)
qed

lemma (in schema_bodies) reference_slots_inside:
  "rel_dom literals \<union> rel_dom callees \<subseteq> rra_carrier (object_structure body)"
proof -
  have pbound: "rel_dom (pattern_literal_bindings p) \<subseteq> rra_carrier (object_structure (pattern_syntax f p))"
    by (auto simp: pattern_syntax_carrier[OF conclusion_addressing])
  have tbound: "rel_dom (premise_forest_literals ts) \<union> rel_dom (premise_forest_callees ts) \<subseteq>
    rra_carrier (object_structure (premise_forest_syntax f ts))"
    by (auto simp: premise_forest_carrier[OF premise_addressing])
  have left: "syntax_prefix 2 ` rel_dom (pattern_literal_bindings p) \<subseteq>
    syntax_prefix 2 ` rra_carrier (object_structure (pattern_syntax f p))"
    by (rule image_mono[OF pbound])
  have right: "syntax_prefix 3 ` (rel_dom (premise_forest_literals ts) \<union> rel_dom (premise_forest_callees ts)) \<subseteq>
    syntax_prefix 3 ` rra_carrier (object_structure (premise_forest_syntax f ts))"
    by (rule image_mono[OF tbound])
  show ?thesis using left right
    by (auto simp: schema_body_literals_def schema_body_callees_def rel_dom_union map_slot_keys_domain carrier)
qed

text \<open>
  Every generated literal and callee table is finite and functional, and the two
  kinds of reference occupy disjoint slots. Literal targets are formed exact
  artifacts. Every slot belongs to the source body carrier. These are derived
  properties of the constructors, used to build actual finite environments;
  they are not additional stored fields or a semantic acceptance predicate.
\<close>

end
