theory Factor_Finite_Inference_Premises
  imports Factor_Finite_Inference_Premises_Base Native_Execution_Refinements
begin

export_code finite_literal_inference_value finite_literal_inference_known
  Finite_Payload Finite_Pair Finite_Target Finite_Whole nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Finite_Literal_Inference_Premises file_prefix finite_literal_inference_premises

end
