theory Factor_Generation_Bindings
  imports Factor_Schema_Generation
begin

section \<open>The current generator cannot recover variables absent from its premises\<close>

fun finite_premise_variables where
  "finite_premise_variables []={||}"
| "finite_premise_variables ((s,d,p)#ps)=finite_pattern_variables p |\<union>| finite_premise_variables ps"

lemma finite_premise_variables_set:
  "finite_premise_variables ps=
    ffUnion (fimage (\<lambda>(s,d,p). finite_pattern_variables p) (fset_of_list ps))"
  by (induction ps) (auto split: prod.splits)

lemma finite_matching_binding_variable:
  assumes "(a,x) |\<in>| finite_matching_bindings p t"
  shows "a |\<in>| finite_pattern_variables p"
  using assms by (induction p arbitrary: t) (auto split: finite_factor_term.splits)

lemma finite_premise_joins_variables:
  assumes joined: "(V,H)\<in>set (finite_premise_joins ps C)"
    and bound: "(a,x) |\<in>| V"
  shows "a |\<in>| finite_premise_variables ps"
  using joined bound
proof (induction ps arbitrary: V H a x)
  case Nil
  then show ?case by simp
next
  case (Cons z ps)
  obtain s d p where shape: "z=(s,d,p)" by (cases z) auto
  show ?case using Cons
    by (auto simp: shape split: prod.splits dest: finite_matching_binding_variable)
qed

lemma finite_schema_generation_variable_bound:
  assumes generated: "(t,V,H) |\<in>| finite_schema_generation S ps C"
    and variable: "a |\<in>| finite_schema_variables S"
  shows "a |\<in>| finite_premise_variables ps"
proof -
  have joined: "(V,H)\<in>set (finite_premise_joins ps C)"
    using generated by (auto simp: finite_schema_generation_def fset_of_list.rep_eq split: if_splits)
  have domain: "fimage fst V=finite_schema_variables S"
    using finite_schema_generation_sound(1)[OF generated]
    by (simp add: finite_schema_instance_def finite_term_bindings_formed_def)
  obtain x where bound: "(a,x) |\<in>| V" using variable domain by force
  show ?thesis by (rule finite_premise_joins_variables[OF joined bound])
qed

definition finite_schema_premise_missing where
  "finite_schema_premise_missing S=finite_schema_variables S |-|
    ffUnion (fimage (\<lambda>(s,d,p). finite_pattern_variables p) (finite_schema_premises S))"

definition finite_schema_head_missing where
  "finite_schema_head_missing S=finite_schema_variables S |-|
    finite_pattern_variables (finite_schema_conclusion S)"

theorem finite_schema_generation_missing_variables:
  assumes missing: "finite_schema_premise_missing S\<noteq>{||}"
  shows "finite_schema_generation S ps C={||}"
proof (rule fset_inject[THEN iffD1], rule set_eqI)
  fix z
  show "z\<in>fset (finite_schema_generation S ps C) \<longleftrightarrow> z\<in>fset {||}"
  proof
    assume member: "z\<in>fset (finite_schema_generation S ps C)"
    obtain t V H where shape: "z=(t,V,H)" by (cases z) auto
    have generated: "(t,V,H) |\<in>| finite_schema_generation S ps C"
      using member by (simp only: shape)
    have complete: "fset_of_list ps=finite_schema_premises S"
      using finite_schema_generation_sound(4)[OF generated]
      by (simp add: fset_inject[symmetric] fset_of_list.rep_eq)
    have bound: "\<And>a. a |\<in>| finite_schema_variables S \<Longrightarrow>
      a |\<in>| ffUnion (fimage (\<lambda>(s,d,p). finite_pattern_variables p) (finite_schema_premises S))"
      using finite_schema_generation_variable_bound[OF generated]
      by (simp only: finite_premise_variables_set complete)
    have "finite_schema_premise_missing S={||}"
      using bound by (auto simp: finite_schema_premise_missing_def)
    with missing show "z\<in>fset {||}" by contradiction
  next
    assume "z\<in>fset {||}"
    then show "z\<in>fset (finite_schema_generation S ps C)" by simp
  qed
qed

text \<open>
  A reported missing variable prevents this generator from constructing any
  application, for every possible frontier and enumeration. Variables in the
  head, private ordinary premises, and all five material operands contribute
  to the complete required scope. The head diagnostic separately records
  which of those variables cannot be recovered from a requested conclusion.
  Neither an empty diagnostic nor head matching establishes premise truth.
\<close>

definition natural_schema_binding_gaps where
  "natural_schema_binding_gaps (S::(nat,nat,nat) finite_factor_schema)=
    (finite_schema_premise_missing S,finite_schema_head_missing S)"

export_code natural_schema_binding_gaps checking SML

end
