theory Factor_Application_Execution
  imports Factor_Application_Execution_Base Native_Execution_Refinements
begin

export_code make_finite_schema make_finite_material make_application_problem application_entry application_schema application_enumeration
  application_frontier application_requests application_required
  Separate_Application_Sources Joined_Application_Observations
  Complete_Instance_Condition Existing_Application_Condition Required_Application_Condition
  application_candidate_subjects application_condition_subjects application_observation_scope
  application_plan_result application_mandatory_targets application_construct_plan
  application_construction_case_formed application_construction_cases_formed application_construction_report
  application_requirement_subjects application_indexed_part_coverage
  application_plan_requirements application_part_coverage application_uncovered_requirements
  application_plan_sufficient application_problem_observations finite_selected_observations
  application_investigation_candidates
  application_construction_result application_condition_holds
  application_investigation application_investigation_observations application_investigation_relation
  investigation_repairs investigation_extend investigation_revision
  finite_pattern_observations finite_observed_bindings finite_binding_support finite_join_observations
  finite_schema_observation_sources finite_schema_call_observations
  natural_schema_observation_sources natural_schema_call_observations natural_observation_join
  natural_observed_bindings natural_binding_support natural_observed_schema_applications
  Finite_Conclusion_Site Finite_Premise_Site Finite_Material_Source_Site Finite_Material_Atoms_Site
  Finite_Material_Edges_Site Finite_Material_Counts_Site Finite_Material_Functions_Site
  Finite_Payload Finite_Pair Finite_Target Finite_Whole finite_empty_artifact
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target
  finite_factor_schema.make finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_pattern.make finite_material_source finite_material_atoms finite_material_edges
  finite_material_counts finite_material_functions
  finite_reasoning_term_equal fset set fset_of_list nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Application_Comparison file_prefix application_comparison

end
