theory Factor_Requirement_Source_Examples
  imports Factor_Requirement_Source_Examples_Base Native_Execution_Refinements
begin

export_code native_guard_source_meaning_report integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Native_Guard_Source_Meaning file_prefix native_guard_source_meaning

end
