theory Factor_Native_Generation
  imports Factor_Schema_Generation_Rows Factor_Finite_Term_Demands Functional_Enumeration_Indexes
begin

fun finite_term_component_rows where
  "finite_term_component_rows (Finite_Target a)=[Finite_Target a]"
| "finite_term_component_rows (Finite_Payload b)=[Finite_Payload b]"
| "finite_term_component_rows (Finite_Pair x y)=Finite_Pair x y #
    (finite_term_component_rows x @ finite_term_component_rows y)"

lemma finite_term_component_rows_exact:
  "set (finite_term_component_rows x)=fset (finite_term_components x)"
  by (induction x) auto

definition finite_native_seed_rows ::
  "local_address option finite_native_system \<Rightarrow> finite_factor_term \<Rightarrow>
    (local_address option definition_site\<times>finite_factor_term) fset \<Rightarrow>
    (local_address option definition_site\<times>finite_factor_term) list" where
  "finite_native_seed_rows P x A=filter (\<lambda>q. q |\<in>| A)
    (concat (map (\<lambda>d. map (Pair d) (finite_term_component_rows x))
      (sorted_list_of_fset (finite_system_definitions P))))"

lemma finite_native_seed_rows_exact:
  assumes evaluation: "finite_native_program_evaluation E u r
    (finite_program_term_demand P {|x|})=Some (P,A)"
  shows "set (finite_native_seed_rows P x A)=fset A"
  using finite_native_program_evaluation_exact(2)[OF evaluation]
  by (auto simp: finite_native_seed_rows_def finite_term_component_rows_exact
    finite_program_term_demand_def)

definition finite_program_generation_rows ::
  "local_address option finite_native_system \<Rightarrow>
    (local_address option definition_site\<times>finite_factor_term) list \<Rightarrow>
    ((local_address option definition_site\<times>local_address)\<times>
      (finite_factor_term\<times>((local_address\<times>finite_factor_term) fset\<times>
        (local_address\<times>(local_address option definition_site\<times>finite_factor_term)) fset))) list" where
  "finite_program_generation_rows P K=concat (map (\<lambda>((d,c),S).
    map (Pair (d,c)) (filter (\<lambda>(t,V,H). finite_admitted_schema_instance P d c V t H)
      (finite_schema_ordered_generation S K)))
      (finite_functional_rows (finite_system_clauses P)))"

definition finite_native_generation where
  "finite_native_generation E u r x=(case finite_native_source E u r of None \<Rightarrow> None
    | Some P \<Rightarrow> let D=finite_program_term_demand P {|x|} in
      map_option (\<lambda>(Q,A). (Q,D,A,finite_program_generation_rows Q
        (finite_native_seed_rows Q x A))) (finite_native_program_evaluation E u r D))"

fun finite_generated_row where
  "finite_generated_row entry x ((d,c),(Finite_Target a,V,H))=[]"
| "finite_generated_row entry x ((d,c),(Finite_Payload b,V,H))=[]"
| "finite_generated_row entry x ((d,c),(Finite_Pair a y,V,H))=
    (if d=entry \<and> a=x then [y] else [])"

lemma finite_generated_row_member:
  "y\<in>set (finite_generated_row entry x row) \<longleftrightarrow>
    (\<exists>c V H. row=((entry,c),(Finite_Pair x y,V,H)))"
  by (induct entry x row rule: finite_generated_row.induct) auto

definition finite_generated_outputs where
  "finite_generated_outputs entry x rows=concat (map (finite_generated_row entry x) rows)"

lemma finite_generated_outputs_member:
  "y\<in>set (finite_generated_outputs entry x rows) \<longleftrightarrow>
    (\<exists>c V H. ((entry,c),(Finite_Pair x y,V,H))\<in>set rows)"
  by (auto simp: finite_generated_outputs_def finite_generated_row_member)

lemma finite_program_generation_rows_origin:
  assumes formed: "finite_system_formed P"
    and generated: "((d,c),(t,V,H))\<in>set (finite_program_generation_rows P K)"
  shows "\<exists>S. ((d,c),S) |\<in>| finite_system_clauses P \<and>
    finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V \<and>
    (\<forall>s e y. (s,e,y) |\<in>| H \<longrightarrow> (e,y)\<in>set K)"
proof -
  have functional: "finite_relation_functional (finite_system_clauses P)"
    using formed by (simp add: finite_system_formed_def)
  have rows: "set (finite_functional_rows (finite_system_clauses P))=fset (finite_system_clauses P)"
    using functional_rows_index.found_pairs[OF functional] by simp
  obtain S where actual: "((d,c),S) |\<in>| finite_system_clauses P"
    and row: "(t,V,H)\<in>set (finite_schema_ordered_generation S K)"
    using generated by (auto simp: finite_program_generation_rows_def rows)
  show ?thesis using actual finite_schema_ordered_generation_sound[OF row] by blast
qed

text \<open>
  The source and complete input determine the known premise calls. Every seed
  is an actual answer from the native program evaluator. Identified rules then
  construct conclusions with complete bindings and premise occurrences. The
  output projection keeps only the requested entry and the same whole input.
  This is one finite generation step; readiness and broader search completeness
  are separate requirements. No candidate conclusion or satisfaction table is
  an input to this operation.
\<close>

end
