theory Factor_Admission_Pair_Reasoning
  imports Factor_Admission_Pair_Reasoning_Base Native_Execution_Refinements
begin

export_code admission_plan admission_pair_reasoning_experiment
  finite_generated_schema_applications finite_generated_schema_rules finite_learned_investigation
  nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Native_Learned_Reasoning file_prefix native_learned_reasoning

end
