theory Factor_Requirement_Source_Boundary
  imports Factor_Requirement_Source_Boundary_Base Native_Execution_Refinements
begin

export_code requirement_source_boundary_report integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Requirement_Source_Boundary file_prefix requirement_source_boundary

end
