theory Factor_Schema_Generation
  imports Factor_Executable_Schemas Factor_Executable_Matching Factor_Learned_Schemas
begin

section \<open>Premises determine bindings before conclusions are constructed\<close>

lemma ffUnion_membership [simp]:
  "x |\<in>| ffUnion A \<longleftrightarrow> (\<exists>B. B |\<in>| A \<and> x |\<in>| B)"
  by (auto simp: ffUnion.rep_eq)

fun finite_pattern_values ::
  "('a\<times>finite_factor_term) fset \<Rightarrow> 'a finite_term_pattern \<Rightarrow> finite_factor_term fset" where
  "finite_pattern_values V (Finite_Variable a)=fimage snd (ffilter (\<lambda>z. fst z=a) V)"
| "finite_pattern_values V (Finite_Pattern_Target t)=(if finite_target_formed t then {|Finite_Target t|} else {||})"
| "finite_pattern_values V (Finite_Pattern_Payload b)=(if octets_formed b then {|Finite_Payload b|} else {||})"
| "finite_pattern_values V (Finite_Pattern_Pair p q)=
    ffUnion (fimage (\<lambda>x. fimage (Finite_Pair x) (finite_pattern_values V q)) (finite_pattern_values V p))"

lemma finite_pattern_values_exact:
  "t |\<in>| finite_pattern_values V p \<longleftrightarrow> finite_pattern_instance V p t"
proof (induction p arbitrary: t)
  case (Finite_Variable a)
  have reverse: "t |\<in>| finite_pattern_values V (Finite_Variable a)" if "(a,t) |\<in>| V"
  proof -
    have row: "(a,t) |\<in>| ffilter (\<lambda>z. fst z=a) V" using that by simp
    have "snd (a,t) |\<in>| fimage snd (ffilter (\<lambda>z. fst z=a) V)"
      by (rule fimageI[OF row])
    then show ?thesis by simp
  qed
  show ?case using reverse by auto
next
  case (Finite_Pattern_Target x)
  then show ?case by auto
next
  case (Finite_Pattern_Payload x)
  then show ?case by auto
next
  case (Finite_Pattern_Pair p q)
  then show ?case by (cases t) auto
qed

fun finite_premise_joins ::
  "('s\<times>('d\<times>'a finite_term_pattern)) list \<Rightarrow>
    ('d\<times>finite_factor_term) list \<Rightarrow>
    (('a\<times>finite_factor_term) fset \<times> ('s\<times>('d\<times>finite_factor_term)) fset) list" where
  "finite_premise_joins [] K=[({||},{||})]"
| "finite_premise_joins ((s,d,p)#ps) K=concat (map (\<lambda>(V,H).
    map (\<lambda>(e,t). (V |\<union>| finite_matching_bindings p t,finsert (s,e,t) H))
      (filter (\<lambda>(e,t). e=d \<and> finite_pattern_accepts p t \<and>
        finite_relation_functional (V |\<union>| finite_matching_bindings p t)) K))
    (finite_premise_joins ps K))"

lemma finite_premise_joins_support:
  assumes "(V,H)\<in>set (finite_premise_joins ps K)" "(s,d,t) |\<in>| H"
  shows "(d,t)\<in>set K"
  using assms
proof (induction ps arbitrary: V H s d t)
  case Nil
  then show ?case by simp
next
  case (Cons a ps)
  obtain k e p where shape: "a=(k,e,p)" by (cases a) auto
  show ?case using Cons by (auto simp: shape split: prod.splits; blast)
qed

definition finite_schema_generation ::
  "('a,'s,'d) finite_factor_schema \<Rightarrow> ('s\<times>('d\<times>'a finite_term_pattern)) list \<Rightarrow>
    ('d\<times>finite_factor_term) list \<Rightarrow>
    (finite_factor_term \<times> (('a\<times>finite_factor_term) fset \<times>
      ('s\<times>('d\<times>finite_factor_term)) fset)) fset" where
  "finite_schema_generation S ps K =
    (if finite_schema_formed S \<and> set ps=fset (finite_schema_premises S) then
      ffUnion (fimage (\<lambda>(V,H).
        fimage (\<lambda>t. (t,V,H))
          (ffilter (\<lambda>t. finite_schema_instance S V t H \<and> finite_schema_material_satisfied S V)
            (finite_pattern_values V (finite_schema_conclusion S))))
        (fset_of_list (finite_premise_joins ps K)))
     else {||})"

theorem finite_schema_generation_sound:
  assumes generated: "(t,V,H) |\<in>| finite_schema_generation S ps K"
  shows "finite_schema_instance S V t H"
    "finite_schema_material_satisfied S V"
    "\<forall>s d x. (s,d,x) |\<in>| H \<longrightarrow> (d,x)\<in>set K"
    "set ps=fset (finite_schema_premises S)"
proof -
  have parts: "(V,H)\<in>set (finite_premise_joins ps K)"
    "finite_schema_instance S V t H" "finite_schema_material_satisfied S V"
    "set ps=fset (finite_schema_premises S)"
    using generated by (auto simp: finite_schema_generation_def fset_of_list.rep_eq split: if_splits)
  show "finite_schema_instance S V t H" "finite_schema_material_satisfied S V"
    "set ps=fset (finite_schema_premises S)" using parts by blast+
  show "\<forall>s d x. (s,d,x) |\<in>| H \<longrightarrow> (d,x)\<in>set K"
    using finite_premise_joins_support[OF parts(1)] by blast
qed

theorem finite_schema_generation_inference:
  assumes generated: "(t,V,H) |\<in>| finite_schema_generation S ps K"
    and library: "(d,decode_finite_schema S)\<in>L"
  shows "learned_schema_inferences L (d,decode_finite_term t) (decode_finite_premises H)"
    "rel_ran (decode_finite_premises H)\<subseteq>decode_finite_call_term ` set K"
proof -
  have inst: "schema_instance (decode_finite_schema S) (decode_finite_term_bindings V)
      (decode_finite_term t) (decode_finite_premises H)"
    using finite_schema_generation_sound(1)[OF generated] by (simp only: finite_schema_instance_correct)
  have material: "schema_material_satisfied (decode_finite_schema S) (decode_finite_term_bindings V)"
    using finite_schema_generation_sound(2)[OF generated] by (simp only: finite_schema_material_satisfied_correct)
  show "learned_schema_inferences L (d,decode_finite_term t) (decode_finite_premises H)"
    unfolding learned_schema_inferences_def
    by (simp only: fst_conv snd_conv, rule exI[of _ "decode_finite_schema S"],
      rule exI[of _ "decode_finite_term_bindings V"])
      (use library inst material in blast)
  show "rel_ran (decode_finite_premises H)\<subseteq>decode_finite_call_term ` set K"
    using finite_schema_generation_sound(3)[OF generated]
    by (auto simp: decode_finite_premises_def rel_ran_def map_relation_values_def
      decode_finite_call_term_def; force)
qed

theorem finite_schema_generation_consequence:
  assumes generated: "(t,V,H) |\<in>| finite_schema_generation S ps K"
    and library: "(d,decode_finite_schema S)\<in>L"
  shows "(d,decode_finite_term t)\<in>
    inference_consequences (learned_schema_inferences L) (decode_finite_call_term ` set K)"
proof -
  have inst: "schema_instance (decode_finite_schema S) (decode_finite_term_bindings V)
      (decode_finite_term t) (decode_finite_premises H)"
    using finite_schema_generation_sound(1)[OF generated] by (simp only: finite_schema_instance_correct)
  have finite: "finite (decode_finite_premises H)" and functional: "single_valued (decode_finite_premises H)"
    using inst by (auto simp: schema_instance_def schema_premise_instance_def)
  show ?thesis unfolding inference_consequences_def
    by (rule CollectI, rule exI[of _ "decode_finite_premises H"])
      (use finite functional finite_schema_generation_inference[OF generated library] in blast)
qed

export_code finite_pattern_values finite_premise_joins finite_schema_generation checking SML

text \<open>
  Inputs are schemas and available calls. Candidate conclusions are generated
  from bindings found by matching the schemas' complete premise families.
  Every generated result retains those bindings and the identified premise
  occurrences. Repeated variables must agree across all matched calls.
  The final check retains the complete binder and all material conditions.

  Each returned conclusion is an actual consequence in the same inference
  account used for learned rules. No input list of candidate conclusions or
  pre-instantiated rule table is needed. Premise-list order is an execution
  choice; the supplied list must enumerate the complete original family.

  A binder variable with no matched occurrence is not assigned an arbitrary
  value. Such a rule is not completed by this executor. This sound finite
  construction step is not a completeness claim for unrestricted schemata,
  a stopping test for repeated generation, or native proof-scheme admission.
\<close>

end
