theory Factor_Investigation_Input_Investigation
  imports Factor_Investigation_Input_Investigation_Base Native_Execution_Refinements
begin

export_code investigation_inference investigation_basis investigation_repairs investigation_extend input_investigation
  input_investigation_observations input_investigation_relation nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Finite_Investigation file_prefix finite_investigation

end
