theory Factor_Finite_Application_Proofs
  imports Factor_Finite_Derivations Factor_Finite_Program_Histories
begin

definition finite_application_proofs where
  "finite_application_proofs W T=ffUnion (fimage (\<lambda>(d,c,t,V,H).
    fimage (\<lambda>B. ((d,t),Schema_Proof c V B)) (finite_family_images H T)) W)"

lemma finite_application_proof_member:
  "((d,t),p) |\<in>| finite_application_proofs W T \<longleftrightarrow>
    (\<exists>c V H B. (d,c,t,V,H) |\<in>| W \<and> B |\<in>| finite_family_images H T \<and>
      p=Schema_Proof c V B)"
  by (auto simp: finite_application_proofs_def finite_union_image_member
    finite_image_member split: prod.splits; force)

theorem finite_application_proofs_domain:
  fixes W :: "('d\<times>'c\<times>'t\<times>('a\<times>'v) fset\<times>('s\<times>('d\<times>'t)) fset) fset"
    and T :: "(('d\<times>'t)\<times>('a,'s,'c,'v) inference_proof) fset"
  assumes support: "\<And>d c t V H. (d,c,t,V,H) |\<in>| W \<Longrightarrow> fimage snd H |\<subseteq>| fimage fst T"
  shows "fimage fst (finite_application_proofs W T)=fimage (\<lambda>(d,c,t,V,H). (d,t)) W"
proof -
  have available: "\<exists>B. B |\<in>| finite_family_images H T"
    if member: "(d,c,t,V,H) |\<in>| W" for d c t V H
    using finite_family_images_total[OF support[OF member]] by auto
  show ?thesis
  proof (rule fset_inject[THEN iffD1], rule set_eqI)
    fix q :: "'d\<times>'t"
    obtain d t where shape: "q=(d,t)" by (cases q)
    show "q\<in>fset (fimage fst (finite_application_proofs W T)) \<longleftrightarrow>
      q\<in>fset (fimage (\<lambda>(d,c,t,V,H). (d,t)) W)"
    proof
      assume head: "q\<in>fset (fimage fst (finite_application_proofs W T))"
      obtain p where generated: "((d,t),p) |\<in>| finite_application_proofs W T"
        using head by (simp only: shape finite_first_projection_member; blast)
      obtain c V H B where actual: "(d,c,t,V,H) |\<in>| W"
        using generated by (simp only: finite_application_proof_member; blast)
      show "q\<in>fset (fimage (\<lambda>(d,c,t,V,H). (d,t)) W)"
        apply (simp only: finite_image_member)
        apply (rule exI[of _ "(d,c,t,V,H)"])
        using actual by (simp only: case_prod_conv shape; blast)
    next
      assume head: "q\<in>fset (fimage (\<lambda>(d,c,t,V,H). (d,t)) W)"
      obtain z where actual: "z |\<in>| W" and projected: "q=(\<lambda>(d,c,t,V,H). (d,t)) z"
        using head by (simp only: finite_image_member; blast)
      obtain e c x V H where row: "z=(e,c,x,V,H)" by (cases z) auto
      have member: "(e,c,x,V,H) |\<in>| W" using actual by (simp only: row)
      obtain B where family: "B |\<in>| finite_family_images H T" using available[OF member] by blast
      have generated: "((e,x),Schema_Proof c V B) |\<in>| finite_application_proofs W T"
        using member family by (simp only: finite_application_proof_member; blast)
      have same: "q=(e,x)" using projected by (simp only: row case_prod_conv)
      show "q\<in>fset (fimage fst (finite_application_proofs W T))"
        using generated by (simp only: same finite_first_projection_member; blast)
    qed
  qed
qed

theorem finite_application_proof_sound:
  assumes applications: "\<And>d c t V H. (d,c,t,V,H) |\<in>| W \<Longrightarrow> finite_admitted_schema_instance P d c V t H"
    and previous: "\<And>q p. (q,p) |\<in>| T \<Longrightarrow>
      checks_schema_proof (decode_finite_system P) (decode_finite_proof p) (fst q) (decode_finite_term (snd q))"
    and generated: "((d,t),p) |\<in>| finite_application_proofs W T"
  shows "checks_schema_proof (decode_finite_system P) (decode_finite_proof p) d (decode_finite_term t)"
proof -
  obtain c V H B where actual: "(d,c,t,V,H) |\<in>| W"
    and family: "B |\<in>| finite_family_images H T" and shape: "p=Schema_Proof c V B"
    using generated by (simp only: finite_application_proof_member; blast)
  have inst: "admitted_schema_instance (decode_finite_system P) d c (decode_finite_term_bindings V)
    (decode_finite_term t) (decode_finite_premises H)"
    using applications[OF actual] by (simp only: finite_admitted_schema_instance_correct)
  have fields: "finite_relation_functional B \<and> fimage fst B=fimage fst H \<and>
    (\<forall>s p. (s,p) |\<in>| B \<longrightarrow> (\<exists>q. (s,q) |\<in>| H \<and> (q,p) |\<in>| T))"
    using family by (simp only: finite_family_image_exact; blast)
  let ?B="fimage (map_prod id decode_finite_proof) B"
  have functional: "single_valued (fset ?B)"
    using fields by (simp only: decoded_proof_family_functional; blast)
  have same_domain: "fimage fst B=fimage fst H" using fields by blast
  have domain: "rel_dom (fset ?B)=rel_dom (decode_finite_premises H)"
    by (simp only: decoded_proof_family_domain decode_finite_premises_domain same_domain)
  have supported: "\<exists>e x. (s,e,x)\<in>decode_finite_premises H \<and>
      checks_schema_proof (decode_finite_system P) (decode_finite_proof child) e x"
    if member: "(s,child) |\<in>| B" for s child
  proof -
    obtain q where required: "(s,q) |\<in>| H" and prior: "(q,child) |\<in>| T"
      using fields member by blast
    obtain e x where call: "q=(e,x)" by (cases q)
    have valid: "checks_schema_proof (decode_finite_system P) (decode_finite_proof child) e (decode_finite_term x)"
      using previous[OF prior] by (simp only: call fst_conv snd_conv)
    have premise: "(s,e,decode_finite_term x)\<in>decode_finite_premises H"
      using required by (simp only: call decode_finite_premises_member)
    show ?thesis using premise valid by blast
  qed
  have children: "\<forall>s q. (s,q)\<in>fset ?B \<longrightarrow>
    (\<exists>e x. (s,e,x)\<in>decode_finite_premises H \<and>
      checks_schema_proof (decode_finite_system P) q e x)"
    using supported by (simp only: decoded_proof_family_all; blast)
  show ?thesis unfolding shape decode_finite_proof_node checks_schema_proof_node
    by (rule exI[of _ "decode_finite_premises H"])
      (use inst functional domain children in \<open>simp only: decode_finite_binding_set_values; blast\<close>)
qed

definition finite_proofs_sound where
  "finite_proofs_sound P T=(\<forall>d t p. ((d,t),p) |\<in>| T \<longrightarrow>
    checks_schema_proof (decode_finite_system P) (decode_finite_proof p) d (decode_finite_term t))"

lemma finite_application_proofs_sound:
  assumes applications: "\<And>d c t V H. (d,c,t,V,H) |\<in>| W \<Longrightarrow> finite_admitted_schema_instance P d c V t H"
    and previous: "finite_proofs_sound P T"
  shows "finite_proofs_sound P (finite_application_proofs W T)"
  unfolding finite_proofs_sound_def
proof (intro allI impI)
  fix d t p assume generated: "((d,t),p) |\<in>| finite_application_proofs W T"
  have valid: "checks_schema_proof (decode_finite_system P) (decode_finite_proof q) (fst x) (decode_finite_term (snd x))"
    if "(x,q) |\<in>| T" for x q
    using previous that by (cases x) (auto simp: finite_proofs_sound_def)
  show "checks_schema_proof (decode_finite_system P) (decode_finite_proof p) d (decode_finite_term t)"
    by (rule finite_application_proof_sound[OF applications valid generated])
qed

text \<open>
  Each complete indexed child family is assembled from actual earlier proofs
  of its required calls. Every generated certificate retains the original
  clause and complete bindings and satisfies the existing proof checker.
  The operation returns all such finite combinations for this one round.
  It does not assume a proof for a missing premise or select a native placement.
\<close>

end
