theory Factor_Observation_Execution
  imports Factor_Observation_Execution_Base Native_Execution_Refinements
begin

export_code observation_octet_profile observation_octet_losses
  observation_reference_profile_decision observation_reference_losses_decision nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Native_Observation file_prefix native_observation

end
