theory Factor_Required_History_Steps
  imports Factor_Required_History_States Factor_Finite_Generation_Replay
    RRA_Finite_Generation_Reference_Construction
begin

definition finite_required_history_step where
  "finite_required_history_step q l rows E pu pr au ar root R=(
    if list_all (\<lambda>row. row\<in>set (required_history_members q)) rows then
      (case finite_record_native_replay (required_history_material q) l rows E pu pr au ar root R of
        None \<Rightarrow> None | Some (A,u,G,J,C) \<Rightarrow>
        if finite_certified_policy_cause (required_history_policy q) (required_history_policy_use q) []
          (required_history_entry q) A u [] G E root R then
          Some (q\<lparr>required_history_material:=A,
            required_history_members:=((u,[]),G)#required_history_members q\<rparr>) else None)
    else None)"

lemma finite_required_history_step_result:
  "finite_required_history_step q l rows E pu pr au ar root R=Some following \<longleftrightarrow>
    list_all (\<lambda>row. row\<in>set (required_history_members q)) rows \<and>
    (\<exists>A u G J C. finite_record_native_replay (required_history_material q) l rows E pu pr au ar root R=
      Some (A,u,G,J,C) \<and>
      finite_certified_policy_cause (required_history_policy q) (required_history_policy_use q) []
        (required_history_entry q) A u [] G E root R \<and>
      following=q\<lparr>required_history_material:=A,
        required_history_members:=((u,[]),G)#required_history_members q\<rparr>)"
  by (auto simp: finite_required_history_step_def split: option.splits if_splits)

theorem finite_required_history_step_valid:
  assumes previous: "finite_required_history_valid q"
    and result: "finite_required_history_step q l rows E pu pr au ar root R=Some following"
  shows "finite_required_history_valid following"
proof -
  obtain P where source: "finite_native_source (required_history_source q) (required_history_source_use q)
      (required_history_source_root q)=Some P"
    and built: "finite_construct_source_requirements (required_history_source q) (required_history_source_use q)
      (required_history_source_root q) (required_history_goals q)=
        Some (required_history_entry q,required_history_policy q,required_history_policy_use q)"
    and original: "finite_environment_formed (required_history_material q)"
    and old: "\<forall>d G. (d,G)\<in>set (required_history_members q) \<longrightarrow>
      finite_check_generation G (required_history_material q) (fst d) (snd d) \<and>
      required_generation_payload P (required_history_goals q) G"
    using previous unfolding finite_required_history_valid_def by blast
  obtain A u G J C where generated: "finite_record_native_replay (required_history_material q) l rows
      E pu pr au ar root R=Some (A,u,G,J,C)"
    and admitted: "finite_certified_policy_cause (required_history_policy q) (required_history_policy_use q) []
      (required_history_entry q) A u [] G E root R"
    and following: "following=q\<lparr>required_history_material:=A,
      required_history_members:=((u,[]),G)#required_history_members q\<rparr>"
    using result unfolding finite_required_history_step_result by blast
  have constructed: "finite_construct_generation_record (required_history_material q) l
    (Finite_Whole R) (Finite_Whole C) rows=Some (A,u,G)"
    using generated by (simp only: finite_record_native_replay_result; blast)
  have formed: "finite_environment_formed A"
    and gen: "finite_check_generation G A u []"
    and core: "G=finite_generation_record_core l (Finite_Whole R) (Finite_Whole C) rows"
    by (rule finite_construct_generation_record_correct[OF constructed])+
  have included: "finite_environment_included (required_history_material q) A"
    using finite_construct_generation_record_correct(4)[OF constructed]
    by (simp only: finite_environment_included_correct)
  have required: "finite_required_cause (required_history_source q) (required_history_source_use q)
    (required_history_source_root q) (required_history_goals q) A u [] G E root R"
    by (simp only: finite_required_cause_def built option.case case_prod_conv admitted)
  have truth: "admission_requirements_hold (positive_meaning (decode_finite_system P))
      (required_history_goals q) (Target_Term (Whole_Artifact (decode_finite_object R)))"
    by (rule finite_required_cause_all_requirements[OF source required])
  have payload: "required_generation_payload P (required_history_goals q) G"
    using truth by (auto simp: required_generation_payload_def core finite_generation_record_core_def)
  have kept: "finite_check_generation H A (fst d) (snd d) \<and>
    required_generation_payload P (required_history_goals q) H"
    if member: "(d,H)\<in>set (required_history_members q)" for d H
    using old member finite_check_generation_included[OF _ included formed] by blast
  show ?thesis unfolding finite_required_history_valid_def
    by (rule exI[of _ P]) (use source built formed gen payload kept in \<open>auto simp: following\<close>)
qed

theorem finite_required_history_step_previous:
  assumes result: "finite_required_history_step q l rows E pu pr au ar root R=Some following"
  shows "set rows\<subseteq>set (required_history_members q)"
    "finite_environment_agrees_on (required_history_material q) (required_history_material following)
      (finite_environment_uses (required_history_material q))"
    "(required_history_source following,required_history_source_use following,required_history_source_root following,
      required_history_goals following,required_history_entry following,required_history_policy following,required_history_policy_use following)=
      (required_history_source q,required_history_source_use q,required_history_source_root q,
        required_history_goals q,required_history_entry q,required_history_policy q,required_history_policy_use q)"
proof -
  obtain A u G J C where generated: "finite_record_native_replay (required_history_material q) l rows
      E pu pr au ar root R=Some (A,u,G,J,C)"
    and following: "following=q\<lparr>required_history_material:=A,
      required_history_members:=((u,[]),G)#required_history_members q\<rparr>"
    and previous: "list_all (\<lambda>row. row\<in>set (required_history_members q)) rows"
    using result unfolding finite_required_history_step_result by blast
  show "set rows\<subseteq>set (required_history_members q)" using previous by (auto simp: list_all_iff)
  show "finite_environment_agrees_on (required_history_material q) (required_history_material following)
      (finite_environment_uses (required_history_material q))"
    using finite_record_native_replay_preserves_history(1)[OF generated] by (simp only: following; simp)
  show "(required_history_source following,required_history_source_use following,required_history_source_root following,
      required_history_goals following,required_history_entry following,required_history_policy following,required_history_policy_use following)=
      (required_history_source q,required_history_source_use q,required_history_source_root q,
        required_history_goals q,required_history_entry q,required_history_policy q,required_history_policy_use q)"
    by (simp only: following; simp)
qed

text \<open>
  A step can use only predecessor rows already admitted at their original sites.
  The existing joined constructor validates their readings, preserves every old
  field and records the exact requested references. The stored policy then
  checks the new actual cause. Its request and policy remain unchanged. This
  establishes the scoped transition, not adequacy for all development actions,
  complete historical permission, a local allocation implementation, or genesis.
\<close>

end
