theory Factor_Investigation_Input_Execution
  imports Factor_Investigation_Input_Execution_Base Native_Execution_Refinements
begin

export_code investigation_input_octets nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Native_Investigation_Input file_prefix native_investigation_input

end
