theory Factor_Finite_Generation_Replay_Completion
  imports Factor_Finite_Generation_Replay
begin

lemma finite_native_judgment_quote_formed:
  assumes result: "finite_native_judgment_quote E pu pr au ar=Some (J,C)"
  shows "finite_exact_formed C"
proof -
  have quoted: "judgment_value_quoted_at (decode_finite_object C) [] (decode_finite_environment J) pu pr au ar"
    by (rule finite_native_judgment_quote_correct(1)[OF result])
  obtain t where complete: "complete_data_quoted_at (decode_finite_object C) [] t"
    using quoted by (auto simp: judgment_value_quoted_at_def)
  show ?thesis using complete_data_quotation_formed[OF complete]
    by (simp only: finite_exact_formed_correct; blast)
qed

theorem finite_record_native_replay_domain:
  "finite_record_native_replay H l rows E pu pr au ar root R\<noteq>None \<longleftrightarrow>
    finite_environment_formed H \<and> finite_target_formed l \<and> distinct (map snd rows) \<and>
    list_all (\<lambda>(d,G). finite_check_generation G H (fst d) (snd d)) rows \<and>
    finite_literal_replay_ready E pu pr au ar root R"
proof
  assume available: "finite_record_native_replay H l rows E pu pr au ar root R\<noteq>None"
  obtain A u G J C where result: "finite_record_native_replay H l rows E pu pr au ar root R=Some (A,u,G,J,C)"
    using available by (cases "finite_record_native_replay H l rows E pu pr au ar root R") auto
  have generated: "finite_construct_generation_record H l (Finite_Whole R) (Finite_Whole C) rows=Some (A,u,G)"
    and ready: "finite_literal_replay_ready E pu pr au ar root R"
    using result by (simp only: finite_record_native_replay_result; blast)+
  show "finite_environment_formed H \<and> finite_target_formed l \<and> distinct (map snd rows) \<and>
    list_all (\<lambda>(d,G). finite_check_generation G H (fst d) (snd d)) rows \<and>
    finite_literal_replay_ready E pu pr au ar root R"
    using finite_construct_generation_record_correct(1)[OF generated] ready
    by (simp only: finite_generation_record_ready_def; blast)
next
  assume context_ready: "finite_environment_formed H \<and> finite_target_formed l \<and> distinct (map snd rows) \<and>
    list_all (\<lambda>(d,G). finite_check_generation G H (fst d) (snd d)) rows \<and>
    finite_literal_replay_ready E pu pr au ar root R"
  have ready: "finite_literal_replay_ready E pu pr au ar root R" using context_ready by blast
  have judgment_ready: "finite_native_judgment_ready E pu pr au ar"
    and payload: "finite_exact_formed R"
    by (rule finite_literal_replay_ready_properties[OF ready])+
  obtain J C where quoted: "finite_native_judgment_quote E pu pr au ar=Some (J,C)"
    using judgment_ready by (simp only: finite_native_judgment_quote_domain[symmetric]; blast)
  have cause: "finite_exact_formed C" by (rule finite_native_judgment_quote_formed[OF quoted])
  have record_ready: "finite_generation_record_ready H l (Finite_Whole R) (Finite_Whole C) rows"
    using context_ready payload cause by (simp add: finite_generation_record_ready_def)
  obtain A u G where generated: "finite_construct_generation_record H l (Finite_Whole R) (Finite_Whole C) rows=Some (A,u,G)"
    using record_ready by (simp only: finite_construct_generation_record_domain[symmetric]; blast)
  have result: "finite_record_native_replay H l rows E pu pr au ar root R=Some (A,u,G,J,C)"
    using ready quoted generated by (simp only: finite_record_native_replay_result; blast)
  show "finite_record_native_replay H l rows E pu pr au ar root R\<noteq>None" using result by simp
qed

text \<open>
  A ready literal replay and the actual original history premises suffice for
  construction. Payload formation follows from the actual native call; cause
  formation follows from its complete judgment quotation. Conversely, every
  returned record requires those same original premises. No additional supplied
  validity flag or independently chosen cause is accepted by this operation.
\<close>

end
