theory Finite_Presented_Storage_Notions
 imports Finite_Derived_Values Finite_Presented_Generation_Queries RRA_Artifact_Lookup_Investigation RRA_Environment_Update_Investigation RRA_Use_Allocation_Investigation RRA_Allocated_Environment_Investigation RRA_Encoded_Environment_Investigation RRA_Graft_Investigation RRA_Graft_Admission_Investigation RRA_Cached_Graft_Investigation RRA_Digit_Allocation_Investigation RRA_Use_Codec_Investigation RRA_Generation_Record_Investigation Factor_Data_Reading_Investigation Factor_Data_Reading_Fixture
begin

definition finite_digit_use_value where
 "finite_digit_use_value u=finite_storage_path_value (digit_use_path u)"
lemma finite_digit_use_value_injective [intro]: "inj finite_digit_use_value"
 by (rule injI) (simp add: finite_digit_use_value_def inj_eq[OF finite_storage_path_value_injective])
lemma finite_digit_use_identity:
 "finite_digit_use_value u=finite_digit_use_value v \<longleftrightarrow> finite_use_data u=finite_use_data v"
 by (simp only: inj_eq[OF finite_digit_use_value_injective] inj_eq[OF finite_use_data_injective])

text \<open>The established digit encoders identify the same complete natural
 and use notions as the original unary data terms. Large decoded coordinates
 remain arbitrary naturals; none are bounded, truncated or conflated with octets.
 Absence and a present empty use keep their distinct original digit paths.\<close>

definition finite_artifact_entry_value where
 "finite_artifact_entry_value=(finite_pair_presentation finite_use_data finite_artifact_term)"

lemma finite_artifact_entry_value_injective [intro]: "inj finite_artifact_entry_value"
 unfolding finite_artifact_entry_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective)

definition finite_binding_row_value where
 "finite_binding_row_value=(finite_pair_presentation (finite_pair_presentation finite_use_data Finite_Payload) finite_use_data)"

lemma finite_binding_row_value_injective [intro]: "inj finite_binding_row_value"
 unfolding finite_binding_row_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective)

definition finite_allocation_state_value where
 "finite_allocation_state_value=(finite_pair_presentation finite_natural_data finite_environment_presentation)"

lemma finite_allocation_state_value_injective [intro]: "inj finite_allocation_state_value"
 unfolding finite_allocation_state_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective)

definition finite_use_mapping_pair_value where
 "finite_use_mapping_pair_value=(finite_pair_presentation finite_use_data finite_use_data)"

lemma finite_use_mapping_pair_value_injective [intro]: "inj finite_use_mapping_pair_value"
 unfolding finite_use_mapping_pair_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective)

definition finite_storage_path_result_value where
 "finite_storage_path_result_value=(finite_pair_presentation finite_storage_path_value (finite_pair_presentation (finite_pair_presentation (finite_option_presentation (finite_collection_presentation finite_artifact_term)) finite_natural_data) (finite_pair_presentation (finite_pair_presentation finite_natural_data finite_natural_data) (finite_pair_presentation (finite_collection_presentation finite_artifact_term) finite_environment_presentation))))"

lemma finite_storage_path_result_value_injective [intro]: "inj finite_storage_path_result_value"
 unfolding finite_storage_path_result_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective)

definition finite_allocation_chain_state_value where
 "finite_allocation_chain_state_value=(finite_pair_presentation finite_allocation_state_value (finite_pair_presentation finite_use_data (finite_pair_presentation (finite_collection_presentation finite_artifact_term) (finite_pair_presentation (finite_option_presentation (finite_collection_presentation finite_artifact_term)) finite_natural_data))))"

lemma finite_allocation_chain_state_value_injective [intro]: "inj finite_allocation_chain_state_value"
 unfolding finite_allocation_chain_state_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective)

definition finite_allocation_chain_paths_value where
 "finite_allocation_chain_paths_value=(finite_option_presentation (finite_pair_presentation finite_allocation_chain_state_value finite_storage_path_result_value))"

lemma finite_allocation_chain_paths_value_injective [intro]: "inj finite_allocation_chain_paths_value"
 unfolding finite_allocation_chain_paths_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective)

definition finite_artifact_lookup_subject_value where
 "finite_artifact_lookup_subject_value=(finite_pair_presentation (finite_sequence_presentation finite_artifact_entry_value) finite_use_data)"

lemma finite_artifact_lookup_subject_value_injective [intro]: "inj finite_artifact_lookup_subject_value"
 unfolding finite_artifact_lookup_subject_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective)

definition finite_artifact_lookup_path_value where
 "finite_artifact_lookup_path_value=(finite_pair_presentation finite_storage_path_value (finite_pair_presentation (finite_pair_presentation (finite_option_presentation (finite_collection_presentation finite_artifact_term)) finite_natural_data) (finite_pair_presentation finite_natural_data (finite_pair_presentation (finite_collection_presentation finite_artifact_term) (finite_sequence_presentation (finite_pair_presentation finite_use_data (finite_pair_presentation (finite_collection_presentation finite_artifact_term) (finite_collection_presentation finite_artifact_term))))))))"

lemma finite_artifact_lookup_path_value_injective [intro]: "inj finite_artifact_lookup_path_value"
 unfolding finite_artifact_lookup_path_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective)

definition finite_environment_chain_value where
 "finite_environment_chain_value=(finite_option_presentation (finite_pair_presentation finite_environment_presentation (finite_pair_presentation (finite_collection_presentation finite_artifact_term) (finite_pair_presentation (finite_option_presentation (finite_collection_presentation finite_artifact_term)) finite_natural_data))))"

lemma finite_environment_chain_value_injective [intro]: "inj finite_environment_chain_value"
 unfolding finite_environment_chain_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective)

definition finite_use_allocation_subject_value where
 "finite_use_allocation_subject_value=(finite_pair_presentation (finite_collection_presentation finite_use_data) (finite_pair_presentation finite_use_data (finite_collection_presentation Finite_Payload)))"

lemma finite_use_allocation_subject_value_injective [intro]: "inj finite_use_allocation_subject_value"
 unfolding finite_use_allocation_subject_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective)

definition finite_use_codec_subject_value where
 "finite_use_codec_subject_value=(finite_pair_presentation (finite_collection_presentation finite_digit_use_value) (finite_pair_presentation (finite_collection_presentation finite_storage_path_value) finite_binary_natural_value))"

lemma finite_use_codec_subject_value_injective [intro]: "inj finite_use_codec_subject_value"
 unfolding finite_use_codec_subject_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_digit_use_value_injective finite_binary_natural_value_injective)

definition finite_use_codec_forward_base_value where
 "finite_use_codec_forward_base_value=(finite_pair_presentation finite_digit_use_value (finite_pair_presentation finite_storage_path_value (finite_option_presentation finite_digit_use_value)))"

lemma finite_use_codec_forward_base_value_injective [intro]: "inj finite_use_codec_forward_base_value"
 unfolding finite_use_codec_forward_base_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_digit_use_value_injective finite_binary_natural_value_injective)

definition finite_use_codec_backward_value where
 "finite_use_codec_backward_value=(finite_pair_presentation finite_storage_path_value (finite_pair_presentation (finite_option_presentation finite_digit_use_value) (finite_option_presentation finite_storage_path_value)))"

lemma finite_use_codec_backward_value_injective [intro]: "inj finite_use_codec_backward_value"
 unfolding finite_use_codec_backward_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_digit_use_value_injective finite_binary_natural_value_injective)

definition finite_generation_record_result_value where
 "finite_generation_record_result_value=(finite_option_presentation (finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_use_data (finite_generation_value Finite_Target))))"

lemma finite_generation_record_result_value_injective [intro]: "inj finite_generation_record_result_value"
 unfolding finite_generation_record_result_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective)

definition finite_generation_original_value where
 "finite_generation_original_value=(finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_sequence_presentation (finite_pair_presentation finite_history_member_value finite_boolean_data)))))))"

lemma finite_generation_original_value_injective [intro]: "inj finite_generation_original_value"
 unfolding finite_generation_original_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective)

definition finite_generation_record_context_value where
 "finite_generation_record_context_value=(finite_pair_presentation finite_generation_problem_value (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_generation_original_value (finite_sequence_presentation (finite_pair_presentation finite_natural_data finite_generation_record_result_value)))))"

lemma finite_generation_record_context_value_injective [intro]: "inj finite_generation_record_context_value"
 unfolding finite_generation_record_context_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective)

definition finite_generation_record_cell_value where
 "finite_generation_record_cell_value=(finite_pair_presentation finite_generation_problem_value (finite_pair_presentation finite_generation_record_result_value finite_generation_assessment_value))"

lemma finite_generation_record_cell_value_injective [intro]: "inj finite_generation_record_cell_value"
 unfolding finite_generation_record_cell_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective)

definition finite_formed_environment_value where
 "finite_formed_environment_value=(finite_derived_value finite_environment_presentation (\<lambda>E. finite_boolean_data (graft_view_formed E)))"

lemma finite_formed_environment_value_injective [intro]: "inj finite_formed_environment_value"
 unfolding finite_formed_environment_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective)

definition finite_formed_allocation_state_value where
 "finite_formed_allocation_state_value=(finite_derived_value finite_allocation_state_value (\<lambda>(next_head,E). finite_boolean_data (graft_view_formed E)))"

lemma finite_formed_allocation_state_value_injective [intro]: "inj finite_formed_allocation_state_value"
 unfolding finite_formed_allocation_state_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective finite_formed_environment_value_injective)

definition finite_use_mapping_value where
 "finite_use_mapping_value=(finite_derived_value finite_use_mapping_pair_value (\<lambda>(x,y). (finite_pair_presentation finite_natural_data finite_natural_data) (use_word_length x,use_word_length y)))"

lemma finite_use_mapping_value_injective [intro]: "inj finite_use_mapping_value"
 unfolding finite_use_mapping_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective finite_formed_environment_value_injective finite_formed_allocation_state_value_injective)

fun finite_environment_update_value :: "environment_update \<Rightarrow> finite_factor_term" where
  "finite_environment_update_value (Install_Artifact u R)=Finite_Pair (Finite_Payload [0]) (finite_artifact_entry_value (u,R))"
| "finite_environment_update_value (Install_Binding u k v)=Finite_Pair (Finite_Payload [1]) (finite_binding_row_value ((u,k),v))"

lemma finite_environment_update_value_injective [intro]: "inj finite_environment_update_value"
 proof (rule injI)
   fix x y assume same: "finite_environment_update_value x=finite_environment_update_value y"
   show "x=y" using same
     by (cases x; cases y) (simp_all add: inj_eq[OF finite_artifact_entry_value_injective]
       inj_eq[OF finite_binding_row_value_injective] inj_eq[OF finite_artifact_term_injective])
 qed

fun finite_allocation_operation_value :: "allocated_environment_update \<Rightarrow> finite_factor_term" where
  "finite_allocation_operation_value (Allocate_Artifact R)=Finite_Pair (Finite_Payload [0]) (finite_artifact_term R)"
| "finite_allocation_operation_value (Add_Allocated_Binding u k v)=Finite_Pair (Finite_Payload [1]) (finite_binding_row_value ((u,k),v))"

lemma finite_allocation_operation_value_injective [intro]: "inj finite_allocation_operation_value"
 proof (rule injI)
   fix x y assume same: "finite_allocation_operation_value x=finite_allocation_operation_value y"
   show "x=y" using same
     by (cases x; cases y) (simp_all add: inj_eq[OF finite_artifact_entry_value_injective]
       inj_eq[OF finite_binding_row_value_injective] inj_eq[OF finite_artifact_term_injective])
 qed

definition finite_environment_update_subject_value where
 "finite_environment_update_subject_value=(finite_pair_presentation (finite_sequence_presentation finite_artifact_entry_value) (finite_pair_presentation (finite_sequence_presentation finite_binding_row_value) finite_environment_update_value))"

lemma finite_environment_update_subject_value_injective [intro]: "inj finite_environment_update_subject_value"
 unfolding finite_environment_update_subject_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective finite_formed_environment_value_injective finite_formed_allocation_state_value_injective finite_use_mapping_value_injective finite_environment_update_value_injective finite_allocation_operation_value_injective)

definition finite_viewed_allocation_subject_value where
 "finite_viewed_allocation_subject_value=(finite_pair_presentation (finite_option_presentation finite_allocation_state_value) finite_allocation_operation_value)"

lemma finite_viewed_allocation_subject_value_injective [intro]: "inj finite_viewed_allocation_subject_value"
 unfolding finite_viewed_allocation_subject_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective finite_formed_environment_value_injective finite_formed_allocation_state_value_injective finite_use_mapping_value_injective finite_environment_update_value_injective finite_allocation_operation_value_injective finite_environment_update_subject_value_injective)

definition finite_graft_subject_value where
 "finite_graft_subject_value=(finite_pair_presentation finite_formed_environment_value (finite_pair_presentation finite_use_data finite_formed_environment_value))"

lemma finite_graft_subject_value_injective [intro]: "inj finite_graft_subject_value"
 unfolding finite_graft_subject_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective finite_formed_environment_value_injective finite_formed_allocation_state_value_injective finite_use_mapping_value_injective finite_environment_update_value_injective finite_allocation_operation_value_injective finite_environment_update_subject_value_injective finite_viewed_allocation_subject_value_injective)

definition finite_graft_assessment_value where
 "finite_graft_assessment_value=(finite_pair_presentation finite_graft_subject_value (finite_pair_presentation (finite_collection_presentation finite_use_mapping_value) (finite_pair_presentation finite_formed_environment_value finite_formed_environment_value)))"

lemma finite_graft_assessment_value_injective [intro]: "inj finite_graft_assessment_value"
 unfolding finite_graft_assessment_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective finite_formed_environment_value_injective finite_formed_allocation_state_value_injective finite_use_mapping_value_injective finite_environment_update_value_injective finite_allocation_operation_value_injective finite_environment_update_subject_value_injective finite_viewed_allocation_subject_value_injective finite_graft_subject_value_injective)

definition finite_graft_requirements_value where
 "finite_graft_requirements_value=(finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation (finite_collection_presentation finite_use_mapping_pair_value) finite_formed_environment_value))))))"

lemma finite_graft_requirements_value_injective [intro]: "inj finite_graft_requirements_value"
 unfolding finite_graft_requirements_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective finite_formed_environment_value_injective finite_formed_allocation_state_value_injective finite_use_mapping_value_injective finite_environment_update_value_injective finite_allocation_operation_value_injective finite_environment_update_subject_value_injective finite_viewed_allocation_subject_value_injective finite_graft_subject_value_injective finite_graft_assessment_value_injective)

definition finite_use_allocation_assessment_value where
 "finite_use_allocation_assessment_value=(finite_pair_presentation finite_use_allocation_subject_value (finite_collection_presentation finite_use_mapping_value))"

lemma finite_use_allocation_assessment_value_injective [intro]: "inj finite_use_allocation_assessment_value"
 unfolding finite_use_allocation_assessment_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_derived_value_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_certificate_value_injective finite_generation_problem_value_injective finite_generation_assessment_value_injective finite_investigation_values_injective finite_index_values_injective inj_on_id finite_storage_path_value_injective finite_artifact_entry_value_injective finite_binding_row_value_injective finite_allocation_state_value_injective finite_use_mapping_pair_value_injective finite_storage_path_result_value_injective finite_allocation_chain_state_value_injective finite_allocation_chain_paths_value_injective finite_artifact_lookup_subject_value_injective finite_artifact_lookup_path_value_injective finite_environment_chain_value_injective finite_use_allocation_subject_value_injective finite_use_codec_subject_value_injective finite_use_codec_forward_base_value_injective finite_use_codec_backward_value_injective finite_generation_record_result_value_injective finite_generation_original_value_injective finite_generation_record_context_value_injective finite_generation_record_cell_value_injective finite_formed_environment_value_injective finite_formed_allocation_state_value_injective finite_use_mapping_value_injective finite_environment_update_value_injective finite_allocation_operation_value_injective finite_environment_update_subject_value_injective finite_viewed_allocation_subject_value_injective finite_graft_subject_value_injective finite_graft_assessment_value_injective finite_graft_requirements_value_injective)

definition finite_reader_context_presentation where
 "finite_reader_context_presentation subject value=finite_pair_presentation subject (finite_collection_presentation value)"
lemma finite_reader_context_presentation_injective [intro]:
 "inj subject \<Longrightarrow> inj value \<Longrightarrow> inj (finite_reader_context_presentation subject value)"
 unfolding finite_reader_context_presentation_def
 by (intro finite_pair_presentation_injective finite_collection_presentation_injective)

definition finite_reader_assessment_presentation where
 "finite_reader_assessment_presentation value=finite_pair_presentation
   (finite_collection_presentation value) (finite_collection_presentation value)"
lemma finite_reader_assessment_presentation_injective [intro]:
 "inj value \<Longrightarrow> inj (finite_reader_assessment_presentation value)"
 unfolding finite_reader_assessment_presentation_def
 by (intro finite_pair_presentation_injective finite_collection_presentation_injective)

definition finite_dual_comparison_packet_value where
 "finite_dual_comparison_packet_value context cell=finite_pair_presentation
   (finite_assessment_table_value context cell) (finite_pair_presentation
     finite_investigation_comparison_value (finite_pair_presentation
       finite_investigation_comparison_value (finite_sequence_presentation finite_investigation_cycle_value)))"
lemma finite_dual_comparison_packet_value_injective [intro]:
 "inj context \<Longrightarrow> inj cell \<Longrightarrow> inj (finite_dual_comparison_packet_value context cell)"
 unfolding finite_dual_comparison_packet_value_def
 by (intro finite_pair_presentation_injective finite_assessment_table_value_injective
     finite_sequence_presentation_injective finite_investigation_values_injective)

definition finite_allocated_subject_value where
 "finite_allocated_subject_value=finite_viewed_allocation_subject_value \<circ> (\<lambda>(input,operation). (map_option (\<lambda>q. allocated_environment_view (raw_allocated_environment q)) input,operation))"

definition finite_digit_allocation_subject_value where
 "finite_digit_allocation_subject_value=finite_viewed_allocation_subject_value \<circ> (\<lambda>(input,operation). (map_option digit_allocated_view input,operation))"

definition finite_cached_graft_subject_value where
 "finite_cached_graft_subject_value=(\<lambda>(input,boundary,A,B). (finite_pair_presentation (finite_option_presentation finite_formed_allocation_state_value) (finite_pair_presentation finite_use_data (finite_pair_presentation (finite_sequence_presentation finite_artifact_entry_value) (finite_pair_presentation (finite_sequence_presentation finite_binding_row_value) finite_environment_presentation)))) (map_option digit_allocated_view input,boundary,A,B,finite_enumerated_environment A B))"

lemma finite_allocated_subject_value_exact:
 "finite_allocated_subject_value (input,op)=finite_allocated_subject_value (other,action) \<longleftrightarrow>
   (map_option (\<lambda>q. allocated_environment_view (raw_allocated_environment q)) input,op)=
   (map_option (\<lambda>q. allocated_environment_view (raw_allocated_environment q)) other,action)"
 by (simp add: finite_allocated_subject_value_def inj_eq[OF finite_viewed_allocation_subject_value_injective])
lemma finite_digit_allocation_subject_value_exact:
 "finite_digit_allocation_subject_value (input,op)=finite_digit_allocation_subject_value (other,action) \<longleftrightarrow>
   (map_option digit_allocated_view input,op)=(map_option digit_allocated_view other,action)"
 by (simp add: finite_digit_allocation_subject_value_def inj_eq[OF finite_viewed_allocation_subject_value_injective])

definition finite_use_codec_forward_value where
 "finite_use_codec_forward_value k=finite_derived_value finite_use_codec_forward_base_value
   (\<lambda>(u,path,decoded). (finite_pair_presentation finite_binary_natural_value (finite_pair_presentation finite_boolean_data finite_binary_natural_value)) (length path,use_coordinate_bound k u,use_path_budget k u))"
lemma finite_use_codec_forward_value_injective [intro]: "inj (finite_use_codec_forward_value k)"
 unfolding finite_use_codec_forward_value_def
 by (intro finite_derived_value_injective finite_use_codec_forward_base_value_injective)

definition finite_use_codec_report_value where
 "finite_use_codec_report_value report=(case report of ((uses,paths,k),forward,backward) \<Rightarrow>
   (finite_pair_presentation finite_use_codec_subject_value (finite_pair_presentation (finite_collection_presentation (finite_use_codec_forward_value k)) (finite_collection_presentation finite_use_codec_backward_value))) ((uses,paths,k),forward,backward))"


lemma finite_use_codec_report_value_injective [intro]: "inj finite_use_codec_report_value"
 by (rule injI)
   (auto simp: finite_use_codec_report_value_def finite_pair_presentation_def
     inj_eq[OF finite_use_codec_subject_value_injective]
     inj_eq[OF finite_collection_presentation_injective[OF finite_use_codec_forward_value_injective]]
     inj_eq[OF finite_collection_presentation_injective[OF finite_use_codec_backward_value_injective]]
     split: prod.splits)

lemma finite_cached_graft_subject_value_exact:
 "finite_cached_graft_subject_value (input,u,A,B)=finite_cached_graft_subject_value (other,v,C,D) \<longleftrightarrow>
   (map_option digit_allocated_view input,u,A,B)=(map_option digit_allocated_view other,v,C,D)"
proof -
 have exact: "inj (finite_pair_presentation (finite_option_presentation finite_formed_allocation_state_value) (finite_pair_presentation finite_use_data (finite_pair_presentation (finite_sequence_presentation finite_artifact_entry_value) (finite_pair_presentation (finite_sequence_presentation finite_binding_row_value) finite_environment_presentation))))"
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
    finite_sequence_presentation_injective finite_formed_allocation_state_value_injective
    finite_use_data_injective finite_artifact_entry_value_injective finite_binding_row_value_injective
    finite_environment_presentation_injective)
 show ?thesis by (simp only: finite_cached_graft_subject_value_def case_prod_conv inj_eq[OF exact] prod.inject; auto)
qed

text \<open>Original views identify opaque allocation stores, including their
 next counter. Complete row sequences and counted paths are retained separately;
 no input occurrence, failed optional level, binding or material value is erased.
 Use mappings keep actual lengths, and codecs keep their actual decoded results,
 path lengths, coordinate bounds and budgets. Formation flags are computed on
 the original displayed environments, independently of raw merge construction.\<close>
end
