theory Finite_Presented_Replays
  imports Finite_Presented_Graphs Digit_History_Presentation
    Factor_Digit_Replay_Cases Factor_Digit_Replay_Reports Factor_Requirement_Decision_Cases
    Factor_Native_Replay_Assessment
begin

section \<open>Programs, proof graphs and complete native replay results\<close>

definition finite_native_system_value where
  "finite_native_system_value=(finite_system_presentation Finite_Payload Finite_Payload finite_site_data Finite_Payload)"

definition finite_native_graph_value where
  "finite_native_graph_value=(finite_graph_presentation finite_site_data finite_site_data finite_site_data finite_site_data)"

definition finite_instantiated_node_value where
  "finite_instantiated_node_value=(finite_pair_presentation (finite_proof_value Finite_Payload (finite_pair_presentation Finite_Payload id) Finite_Payload) finite_call_value)"

definition finite_native_replay_result_value :: "native_replay_result \<Rightarrow> finite_factor_term" where
  "finite_native_replay_result_value=(finite_option_presentation (finite_pair_presentation finite_environment_presentation (finite_pair_presentation (finite_collection_presentation (finite_pair_presentation finite_instantiated_node_value finite_site_data)) (finite_pair_presentation finite_site_data (finite_pair_presentation finite_native_graph_value (finite_pair_presentation finite_use_data (finite_pair_presentation (finite_collection_presentation Finite_Payload) (finite_pair_presentation (finite_collection_presentation Finite_Payload) finite_environment_presentation))))))))"

definition finite_requirement_decision_body_value where
  "finite_requirement_decision_body_value=(finite_pair_presentation finite_site_data (finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_use_data (finite_pair_presentation finite_native_system_value (finite_pair_presentation (finite_collection_presentation finite_call_value) (finite_pair_presentation (finite_collection_presentation finite_call_value) (finite_pair_presentation (finite_collection_presentation finite_history_certificate_value) (finite_collection_presentation id))))))))"

definition finite_decision_replay_value where
  "finite_decision_replay_value=(finite_pair_presentation finite_requirement_decision_body_value (finite_collection_presentation (finite_pair_presentation finite_history_certificate_value finite_native_replay_result_value)))"

definition finite_literal_replay_value :: "literal_replay_subject \<Rightarrow> finite_factor_term" where
  "finite_literal_replay_value=(finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_use_data (finite_pair_presentation Finite_Payload (finite_pair_presentation finite_use_data (finite_pair_presentation Finite_Payload (finite_pair_presentation finite_site_data finite_artifact_term))))))"

definition finite_replay_state_value where
  "finite_replay_state_value=(finite_pair_presentation finite_natural_data finite_environment_presentation)"

definition finite_bounded_replay_value :: "bounded_replay_value \<Rightarrow> finite_factor_term" where
  "finite_bounded_replay_value=(finite_option_presentation (finite_pair_presentation finite_replay_state_value (finite_pair_presentation finite_use_data (finite_pair_presentation (finite_generation_value Finite_Target) (finite_pair_presentation finite_environment_presentation finite_artifact_term)))))"

definition finite_bounded_replay_subject_value :: "bounded_replay_subject \<Rightarrow> finite_factor_term" where
  "finite_bounded_replay_subject_value=(finite_pair_presentation (finite_option_presentation finite_replay_state_value) (finite_pair_presentation Finite_Target (finite_pair_presentation (finite_sequence_presentation finite_history_member_value) finite_literal_replay_value)))"

definition finite_original_replay_input_value :: "original_replay_input \<Rightarrow> finite_factor_term" where
  "finite_original_replay_input_value=(finite_pair_presentation finite_environment_presentation (finite_pair_presentation Finite_Target (finite_pair_presentation (finite_sequence_presentation finite_history_member_value) finite_literal_replay_value)))"

definition finite_generation_problem_value where
  "finite_generation_problem_value=(finite_pair_presentation finite_environment_presentation (finite_pair_presentation Finite_Target (finite_pair_presentation Finite_Target (finite_pair_presentation Finite_Target (finite_sequence_presentation finite_history_member_value)))))"

definition finite_cause_subject_value :: "certified_cause_subject \<Rightarrow> finite_factor_term" where
  "finite_cause_subject_value=(finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_use_data (finite_pair_presentation Finite_Payload (finite_pair_presentation (finite_generation_value Finite_Target) (finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_site_data finite_artifact_term))))))"

definition finite_judgment_context_value where
  "finite_judgment_context_value=(finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_use_data (finite_pair_presentation Finite_Payload (finite_pair_presentation finite_use_data Finite_Payload))))"

definition finite_application_reading_value where
  "finite_application_reading_value=(finite_pair_presentation finite_call_value (finite_pair_presentation (finite_collection_presentation Finite_Payload) (finite_collection_presentation Finite_Payload)))"

definition finite_assertion_readings_value where
  "finite_assertion_readings_value=(finite_collection_presentation (finite_pair_presentation finite_site_data finite_call_value))"

definition finite_cause_scope_value where
  "finite_cause_scope_value=(finite_pair_presentation finite_judgment_context_value (finite_pair_presentation finite_environment_presentation (finite_pair_presentation (finite_collection_presentation finite_native_system_value) (finite_pair_presentation (finite_collection_presentation finite_application_reading_value) (finite_pair_presentation (finite_collection_presentation finite_assertion_readings_value) (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data finite_boolean_data))))))))"

definition finite_cause_report_value where
  "finite_cause_report_value=(finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_collection_presentation finite_cause_scope_value)))"

definition finite_literal_seed_value where
  "finite_literal_seed_value=(finite_option_presentation (finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_use_data (finite_pair_presentation Finite_Payload (finite_pair_presentation finite_artifact_term (finite_option_presentation finite_decision_replay_value))))))"

definition finite_literal_source_value where
  "finite_literal_source_value=(finite_pair_presentation finite_natural_data (finite_collection_presentation (finite_pair_presentation finite_history_certificate_value (finite_option_presentation finite_literal_replay_value))))"

definition finite_history_source_value where
  "finite_history_source_value=(finite_pair_presentation finite_natural_data (finite_collection_presentation finite_history_subject_value))"

section \<open>Each complete replay notion has an injective presentation\<close>

lemma finite_native_system_value_injective [intro]: "inj finite_native_system_value"
  unfolding finite_native_system_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id )

lemma finite_native_graph_value_injective [intro]: "inj finite_native_graph_value"
  unfolding finite_native_graph_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective)

lemma finite_instantiated_node_value_injective [intro]: "inj finite_instantiated_node_value"
  unfolding finite_instantiated_node_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective)

lemma finite_native_replay_result_value_injective [intro]: "inj finite_native_replay_result_value"
  unfolding finite_native_replay_result_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective)

lemma finite_requirement_decision_body_value_injective [intro]: "inj finite_requirement_decision_body_value"
  unfolding finite_requirement_decision_body_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective)

lemma finite_decision_replay_value_injective [intro]: "inj finite_decision_replay_value"
  unfolding finite_decision_replay_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective)

lemma finite_literal_replay_value_injective [intro]: "inj finite_literal_replay_value"
  unfolding finite_literal_replay_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective)

lemma finite_replay_state_value_injective [intro]: "inj finite_replay_state_value"
  unfolding finite_replay_state_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective)

lemma finite_bounded_replay_value_injective [intro]: "inj finite_bounded_replay_value"
  unfolding finite_bounded_replay_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective)

lemma finite_bounded_replay_subject_value_injective [intro]: "inj finite_bounded_replay_subject_value"
  unfolding finite_bounded_replay_subject_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective)

lemma finite_original_replay_input_value_injective [intro]: "inj finite_original_replay_input_value"
  unfolding finite_original_replay_input_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective)

lemma finite_generation_problem_value_injective [intro]: "inj finite_generation_problem_value"
  unfolding finite_generation_problem_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective)

lemma finite_cause_subject_value_injective [intro]: "inj finite_cause_subject_value"
  unfolding finite_cause_subject_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective)

lemma finite_judgment_context_value_injective [intro]: "inj finite_judgment_context_value"
  unfolding finite_judgment_context_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective finite_cause_subject_value_injective)

lemma finite_application_reading_value_injective [intro]: "inj finite_application_reading_value"
  unfolding finite_application_reading_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective finite_cause_subject_value_injective finite_judgment_context_value_injective)

lemma finite_assertion_readings_value_injective [intro]: "inj finite_assertion_readings_value"
  unfolding finite_assertion_readings_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective finite_cause_subject_value_injective finite_judgment_context_value_injective finite_application_reading_value_injective)

lemma finite_cause_scope_value_injective [intro]: "inj finite_cause_scope_value"
  unfolding finite_cause_scope_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective finite_cause_subject_value_injective finite_judgment_context_value_injective finite_application_reading_value_injective finite_assertion_readings_value_injective)

lemma finite_cause_report_value_injective [intro]: "inj finite_cause_report_value"
  unfolding finite_cause_report_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective finite_cause_subject_value_injective finite_judgment_context_value_injective finite_application_reading_value_injective finite_assertion_readings_value_injective finite_cause_scope_value_injective)

lemma finite_literal_seed_value_injective [intro]: "inj finite_literal_seed_value"
  unfolding finite_literal_seed_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective finite_cause_subject_value_injective finite_judgment_context_value_injective finite_application_reading_value_injective finite_assertion_readings_value_injective finite_cause_scope_value_injective finite_cause_report_value_injective)

lemma finite_literal_source_value_injective [intro]: "inj finite_literal_source_value"
  unfolding finite_literal_source_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective finite_cause_subject_value_injective finite_judgment_context_value_injective finite_application_reading_value_injective finite_assertion_readings_value_injective finite_cause_scope_value_injective finite_cause_report_value_injective finite_literal_seed_value_injective)

lemma finite_history_source_value_injective [intro]: "inj finite_history_source_value"
  unfolding finite_history_source_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_sequence_presentation_injective finite_collection_presentation_injective
      finite_system_presentation_injective finite_graph_presentation_injective finite_proof_value_injective
      finite_generation_value_injective finite_environment_presentation_injective finite_use_data_injective
      finite_site_data_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_history_member_injective finite_history_rows_injective finite_natural_data_injective
      finite_boolean_data_injective finite_payload_injective finite_target_injective
      finite_artifact_term_injective inj_on_id finite_native_system_value_injective finite_native_graph_value_injective finite_instantiated_node_value_injective finite_native_replay_result_value_injective finite_requirement_decision_body_value_injective finite_decision_replay_value_injective finite_literal_replay_value_injective finite_replay_state_value_injective finite_bounded_replay_value_injective finite_bounded_replay_subject_value_injective finite_original_replay_input_value_injective finite_generation_problem_value_injective finite_cause_subject_value_injective finite_judgment_context_value_injective finite_application_reading_value_injective finite_assertion_readings_value_injective finite_cause_scope_value_injective finite_cause_report_value_injective finite_literal_seed_value_injective finite_literal_source_value_injective)

export_code finite_decision_replay_value finite_bounded_replay_value finite_literal_seed_value
  finite_cause_report_value checking SML

text \<open>Every optional level, source environment, graph, certificate, replay reading,
  generation, judgment scope and native diagnostic is retained. These composed
  presentations identify their full subjects; native admission remains the
  independent operation whose actual results are being presented.\<close>

end
