theory Finite_Presented_Native_Certificates
 imports Finite_Presented_Native_Construction Finite_Presented_Decisions Finite_Presented_Reviews
   Factor_Native_Derivation_Reports
   Factor_Native_Certificate_Investigation
begin

section \<open>Native history problems, source readings and demand coverage\<close>

definition finite_native_history_subject_value where
  "finite_native_history_subject_value=finite_native_source_problem_value (finite_collection_presentation finite_call_value)"

lemma finite_native_history_subject_value_injective [intro]: "inj finite_native_history_subject_value"
  unfolding finite_native_history_subject_value_def
  by (intro finite_native_source_problem_value_injective finite_collection_presentation_injective
      finite_call_value_injective)

definition finite_native_history_details_value where
  "finite_native_history_details_value=finite_option_presentation (finite_pair_presentation finite_boolean_data
    (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data
      (finite_collection_presentation finite_native_application_value))))"

lemma finite_native_history_details_value_injective [intro]: "inj finite_native_history_details_value"
  unfolding finite_native_history_details_value_def
  by (intro finite_option_presentation_injective finite_pair_presentation_injective finite_boolean_data_injective
      finite_collection_presentation_injective finite_native_application_value_injective)

definition finite_native_history_coverage_value where
  "finite_native_history_coverage_value=finite_pair_presentation (finite_collection_presentation finite_call_value)
    (finite_pair_presentation (finite_option_presentation finite_boolean_data) finite_native_program_evaluation_value)"

lemma finite_native_history_coverage_value_injective [intro]: "inj finite_native_history_coverage_value"
  unfolding finite_native_history_coverage_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_call_value_injective
      finite_option_presentation_injective finite_boolean_data_injective finite_native_program_evaluation_value_injective)

definition finite_native_history_reference_value where
  "finite_native_history_reference_value=finite_pair_presentation finite_native_source_value
    (finite_pair_presentation finite_native_history_details_value
      (finite_pair_presentation finite_native_program_evaluation_value finite_native_history_coverage_value))"

lemma finite_native_history_reference_value_injective [intro]: "inj finite_native_history_reference_value"
  unfolding finite_native_history_reference_value_def
  by (intro finite_pair_presentation_injective finite_native_source_value_injective
      finite_native_history_details_value_injective finite_native_program_evaluation_value_injective
      finite_native_history_coverage_value_injective)

section \<open>Derivations specialize evidenced results, evidence assessments and subject packets\<close>

definition finite_native_derivation_result_value where
  "finite_native_derivation_result_value=finite_native_evidence_result_value
    (finite_collection_presentation finite_history_certificate_value)"

lemma finite_native_derivation_result_value_injective [intro]: "inj finite_native_derivation_result_value"
  unfolding finite_native_derivation_result_value_def
  by (intro finite_native_evidence_result_value_injective finite_collection_presentation_injective
      finite_history_certificate_value_injective)

definition finite_native_derivation_assessment_value where
  "finite_native_derivation_assessment_value=finite_evidence_assessment_value finite_call_value"

lemma finite_native_derivation_assessment_value_injective [intro]: "inj finite_native_derivation_assessment_value"
  unfolding finite_native_derivation_assessment_value_def
  by (intro finite_evidence_assessment_value_injective finite_call_value_injective)

definition finite_native_derivation_review_value where
  "finite_native_derivation_review_value=finite_option_presentation (finite_pair_presentation
    (finite_collection_presentation (finite_pair_presentation finite_history_certificate_value finite_boolean_data))
    (finite_collection_differences_value finite_call_value))"

lemma finite_native_derivation_review_value_injective [intro]: "inj finite_native_derivation_review_value"
  unfolding finite_native_derivation_review_value_def
  by (intro finite_option_presentation_injective finite_pair_presentation_injective finite_collection_presentation_injective
      finite_history_certificate_value_injective finite_boolean_data_injective
      finite_collection_differences_value_injective finite_call_value_injective)

definition finite_native_derivation_cell_value where
  "finite_native_derivation_cell_value=finite_option_presentation (finite_pair_presentation
    finite_native_derivation_assessment_value finite_native_derivation_review_value)"

lemma finite_native_derivation_cell_value_injective [intro]: "inj finite_native_derivation_cell_value"
  unfolding finite_native_derivation_cell_value_def
  by (intro finite_option_presentation_injective finite_pair_presentation_injective
      finite_native_derivation_assessment_value_injective finite_native_derivation_review_value_injective)

definition finite_native_derivation_subject_report_value where
  "finite_native_derivation_subject_report_value=finite_subject_report_value finite_native_history_subject_value
    finite_native_history_reference_value finite_native_derivation_result_value"

lemma finite_native_derivation_subject_report_value_injective [intro]: "inj finite_native_derivation_subject_report_value"
  unfolding finite_native_derivation_subject_report_value_def
  by (intro finite_subject_report_value_injective finite_native_history_subject_value_injective
      finite_native_history_reference_value_injective finite_native_derivation_result_value_injective)

definition finite_native_derivation_packet_value where
  "finite_native_derivation_packet_value=finite_subject_assessment_packet_value
    finite_native_derivation_subject_report_value finite_native_derivation_cell_value"

lemma finite_native_derivation_packet_value_injective [intro]: "inj finite_native_derivation_packet_value"
  unfolding finite_native_derivation_packet_value_def
  by (intro finite_subject_assessment_packet_value_injective finite_native_derivation_subject_report_value_injective
      finite_native_derivation_cell_value_injective)

section \<open>Certificate paths, graphs and rows\<close>

definition finite_certificate_path_value where
  "finite_certificate_path_value=finite_sequence_presentation Finite_Payload"

lemma finite_certificate_path_value_injective [intro]: "inj finite_certificate_path_value"
  unfolding finite_certificate_path_value_def
  by (intro finite_sequence_presentation_injective finite_payload_injective)

definition finite_certificate_path_node_value where
  "finite_certificate_path_node_value=finite_pair_presentation finite_certificate_path_value finite_instantiated_node_value"

lemma finite_certificate_path_node_value_injective [intro]: "inj finite_certificate_path_node_value"
  unfolding finite_certificate_path_node_value_def
  by (intro finite_pair_presentation_injective finite_certificate_path_value_injective
      finite_instantiated_node_value_injective)

definition finite_certificate_paths_value where
  "finite_certificate_paths_value=finite_collection_presentation finite_certificate_path_node_value"

lemma finite_certificate_paths_value_injective [intro]: "inj finite_certificate_paths_value"
  unfolding finite_certificate_paths_value_def
  by (intro finite_collection_presentation_injective finite_certificate_path_node_value_injective)

definition finite_certificate_mapping_value where
  "finite_certificate_mapping_value=finite_collection_presentation
    (finite_pair_presentation finite_instantiated_node_value finite_certificate_path_value)"

lemma finite_certificate_mapping_value_injective [intro]: "inj finite_certificate_mapping_value"
  unfolding finite_certificate_mapping_value_def
  by (intro finite_collection_presentation_injective finite_pair_presentation_injective
      finite_instantiated_node_value_injective finite_certificate_path_value_injective)

definition finite_certificate_coordinate_graph_value where
  "finite_certificate_coordinate_graph_value=finite_graph_presentation Finite_Payload Finite_Payload Finite_Payload
    finite_certificate_path_value"

lemma finite_certificate_coordinate_graph_value_injective [intro]: "inj finite_certificate_coordinate_graph_value"
  unfolding finite_certificate_coordinate_graph_value_def
  by (intro finite_graph_presentation_injective finite_payload_injective finite_certificate_path_value_injective)

definition finite_certificate_original_graph_value where
  "finite_certificate_original_graph_value=finite_graph_presentation Finite_Payload Finite_Payload Finite_Payload
    finite_instantiated_node_value"

lemma finite_certificate_original_graph_value_injective [intro]: "inj finite_certificate_original_graph_value"
  unfolding finite_certificate_original_graph_value_def
  by (intro finite_graph_presentation_injective finite_payload_injective finite_instantiated_node_value_injective)

definition finite_certificate_row_value where
  "finite_certificate_row_value=finite_pair_presentation finite_instantiated_node_value
    (finite_pair_presentation finite_certificate_paths_value
      (finite_pair_presentation finite_certificate_mapping_value finite_certificate_coordinate_graph_value))"

lemma finite_certificate_row_value_injective [intro]: "inj finite_certificate_row_value"
  unfolding finite_certificate_row_value_def
  by (intro finite_pair_presentation_injective finite_instantiated_node_value_injective
      finite_certificate_paths_value_injective finite_certificate_mapping_value_injective
      finite_certificate_coordinate_graph_value_injective)

section \<open>Certificate results, assessments and tables\<close>

definition finite_native_certificate_result_value where
  "finite_native_certificate_result_value=finite_native_evidence_result_value
    (finite_collection_presentation finite_certificate_row_value)"

lemma finite_native_certificate_result_value_injective [intro]: "inj finite_native_certificate_result_value"
  unfolding finite_native_certificate_result_value_def
  by (intro finite_native_evidence_result_value_injective finite_collection_presentation_injective
      finite_certificate_row_value_injective)

definition finite_certificate_row_assessment_value where
  "finite_certificate_row_assessment_value=finite_pair_presentation finite_certificate_paths_value
    (finite_pair_presentation finite_certificate_original_graph_value
      (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data finite_boolean_data)))"

lemma finite_certificate_row_assessment_value_injective [intro]: "inj finite_certificate_row_assessment_value"
  unfolding finite_certificate_row_assessment_value_def
  by (intro finite_pair_presentation_injective finite_certificate_paths_value_injective
      finite_certificate_original_graph_value_injective finite_boolean_data_injective)

definition finite_native_certificate_assessment_value where
  "finite_native_certificate_assessment_value=finite_pair_presentation finite_boolean_data
    (finite_pair_presentation (finite_option_presentation (finite_pair_presentation finite_boolean_data
        (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data
          (finite_collection_presentation (finite_pair_presentation finite_certificate_row_value
            finite_certificate_row_assessment_value))))))
      finite_boolean_data)"

lemma finite_native_certificate_assessment_value_injective [intro]: "inj finite_native_certificate_assessment_value"
  unfolding finite_native_certificate_assessment_value_def
  by (intro finite_pair_presentation_injective finite_boolean_data_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_certificate_row_value_injective
      finite_certificate_row_assessment_value_injective)

definition finite_native_certificate_cell_value where
  "finite_native_certificate_cell_value=finite_pair_presentation finite_native_certificate_result_value
    finite_native_certificate_assessment_value"

lemma finite_native_certificate_cell_value_injective [intro]: "inj finite_native_certificate_cell_value"
  unfolding finite_native_certificate_cell_value_def
  by (intro finite_pair_presentation_injective finite_native_certificate_result_value_injective
      finite_native_certificate_assessment_value_injective)

definition finite_certificate_table_value where
  "finite_certificate_table_value problem=finite_indexed_rows_value (finite_pair_presentation problem
    (finite_pair_presentation finite_native_derivation_result_value
      (finite_indexed_rows_value finite_native_certificate_cell_value)))"

lemma finite_certificate_table_value_injective [intro]:
  "inj problem \<Longrightarrow> inj (finite_certificate_table_value problem)"
  unfolding finite_certificate_table_value_def
  by (intro finite_indexed_rows_value_injective finite_pair_presentation_injective
      finite_native_derivation_result_value_injective finite_native_certificate_cell_value_injective)

definition finite_native_certificate_table_value where
  "finite_native_certificate_table_value=finite_certificate_table_value
    (finite_option_presentation finite_native_history_subject_value)"

lemma finite_native_certificate_table_value_injective [intro]: "inj finite_native_certificate_table_value"
  unfolding finite_native_certificate_table_value_def
  by (intro finite_certificate_table_value_injective finite_option_presentation_injective
      finite_native_history_subject_value_injective)

definition finite_native_certificate_packet_value where
  "finite_native_certificate_packet_value=finite_pair_presentation finite_native_certificate_table_value
    finite_investigation_outcome_value"

lemma finite_native_certificate_packet_value_injective [intro]: "inj finite_native_certificate_packet_value"
  unfolding finite_native_certificate_packet_value_def
  by (intro finite_pair_presentation_injective finite_native_certificate_table_value_injective
      finite_investigation_outcome_value_injective)

text \<open>Original sources, demands, evaluations, certificates and their actual checks remain separate complete values. Paths, node coordinates, arbitrary graph mappings and independent original graphs retain their distinct notions and every optional failure level. Native history problems specialize native source problems; derivation and certificate results specialize evidenced results; derivation assessments specialize evidence assessments; derivation packets specialize subject and assessment packets; and a certificate table is parameterized by its problem presentation.\<close>
end
