theory Finite_Presented_Generation_Queries
 imports Finite_Presented_Native_Construction
   Factor_History_Index_Investigation
   RRA_Indexed_Generation_Investigation
   RRA_Digit_Generation_Investigation
begin

definition finite_generation_state_value where
  "finite_generation_state_value=(finite_pair_presentation finite_natural_data finite_environment_presentation)"

lemma finite_generation_state_value_injective [intro]: "inj finite_generation_state_value"
  unfolding finite_generation_state_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective)

definition finite_generation_fields_value where
  "finite_generation_fields_value=(finite_pair_presentation Finite_Target (finite_pair_presentation (finite_collection_presentation (finite_pair_presentation Finite_Payload Finite_Payload)) (finite_pair_presentation Finite_Target Finite_Target)))"

lemma finite_generation_fields_value_injective [intro]: "inj finite_generation_fields_value"
  unfolding finite_generation_fields_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective)

definition finite_generation_anchor_value where
  "finite_generation_anchor_value=(finite_pair_presentation finite_site_data finite_artifact_term)"

lemma finite_generation_anchor_value_injective [intro]: "inj finite_generation_anchor_value"
  unfolding finite_generation_anchor_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective)

definition finite_generation_query_row_value where
  "finite_generation_query_row_value=(finite_pair_presentation finite_history_member_value (finite_pair_presentation (finite_collection_presentation finite_generation_fields_value) (finite_pair_presentation finite_boolean_data (finite_option_presentation finite_artifact_term))))"

lemma finite_generation_query_row_value_injective [intro]: "inj finite_generation_query_row_value"
  unfolding finite_generation_query_row_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective finite_generation_anchor_value_injective)

definition finite_indexed_generation_result_value where
  "finite_indexed_generation_result_value=(finite_pair_presentation finite_boolean_data (finite_pair_presentation (finite_option_presentation (finite_sequence_presentation finite_generation_anchor_value)) (finite_sequence_presentation finite_generation_query_row_value)))"

lemma finite_indexed_generation_result_value_injective [intro]: "inj finite_indexed_generation_result_value"
  unfolding finite_indexed_generation_result_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective finite_generation_anchor_value_injective finite_generation_query_row_value_injective)

definition finite_bounded_generation_subject_value where
  "finite_bounded_generation_subject_value=(finite_pair_presentation (finite_option_presentation finite_generation_state_value) (finite_pair_presentation Finite_Target (finite_pair_presentation Finite_Target (finite_pair_presentation Finite_Target (finite_sequence_presentation finite_history_member_value)))))"

lemma finite_bounded_generation_subject_value_injective [intro]: "inj finite_bounded_generation_subject_value"
  unfolding finite_bounded_generation_subject_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective finite_generation_anchor_value_injective finite_generation_query_row_value_injective finite_indexed_generation_result_value_injective)

definition finite_bounded_generation_value_value where
  "finite_bounded_generation_value_value=(finite_option_presentation (finite_pair_presentation finite_generation_state_value (finite_pair_presentation finite_use_data (finite_generation_value Finite_Target))))"

lemma finite_bounded_generation_value_value_injective [intro]: "inj finite_bounded_generation_value_value"
  unfolding finite_bounded_generation_value_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective finite_generation_anchor_value_injective finite_generation_query_row_value_injective finite_indexed_generation_result_value_injective finite_bounded_generation_subject_value_injective)

definition finite_generation_assessment_body_value where
  "finite_generation_assessment_body_value=(finite_pair_presentation (finite_collection_presentation finite_generation_fields_value) (finite_pair_presentation (finite_collection_presentation finite_site_data) (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data finite_boolean_data)))))))))"

lemma finite_generation_assessment_body_value_injective [intro]: "inj finite_generation_assessment_body_value"
  unfolding finite_generation_assessment_body_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective finite_generation_anchor_value_injective finite_generation_query_row_value_injective finite_indexed_generation_result_value_injective finite_bounded_generation_subject_value_injective finite_bounded_generation_value_value_injective)

definition finite_generation_assessment_value where
  "finite_generation_assessment_value=(finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_option_presentation finite_generation_assessment_body_value)))"

lemma finite_generation_assessment_value_injective [intro]: "inj finite_generation_assessment_value"
  unfolding finite_generation_assessment_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective finite_generation_anchor_value_injective finite_generation_query_row_value_injective finite_indexed_generation_result_value_injective finite_bounded_generation_subject_value_injective finite_bounded_generation_value_value_injective finite_generation_assessment_body_value_injective)

definition finite_history_index_view_value where
  "finite_history_index_view_value=(finite_pair_presentation finite_history_state_value (finite_collection_presentation finite_history_member_value))"

lemma finite_history_index_view_value_injective [intro]: "inj finite_history_index_view_value"
  unfolding finite_history_index_view_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective finite_generation_anchor_value_injective finite_generation_query_row_value_injective finite_indexed_generation_result_value_injective finite_bounded_generation_subject_value_injective finite_bounded_generation_value_value_injective finite_generation_assessment_body_value_injective finite_generation_assessment_value_injective)

definition finite_history_index_result_row_value where
  "finite_history_index_result_row_value=(finite_pair_presentation (finite_option_presentation finite_history_certificate_value) (finite_option_presentation (finite_option_presentation finite_history_index_view_value)))"

lemma finite_history_index_result_row_value_injective [intro]: "inj finite_history_index_result_row_value"
  unfolding finite_history_index_result_row_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_sequence_presentation_injective finite_collection_presentation_injective finite_environment_presentation_injective finite_natural_data_injective finite_boolean_data_injective finite_site_data_injective finite_use_data_injective finite_generation_value_injective finite_target_injective finite_payload_injective finite_artifact_term_injective finite_history_member_injective finite_history_state_value_injective finite_history_certificate_value_injective finite_generation_state_value_injective finite_generation_fields_value_injective finite_generation_anchor_value_injective finite_generation_query_row_value_injective finite_indexed_generation_result_value_injective finite_bounded_generation_subject_value_injective finite_bounded_generation_value_value_injective finite_generation_assessment_body_value_injective finite_generation_assessment_value_injective finite_history_index_view_value_injective)

definition finite_indexed_generation_subject_value where
  "finite_indexed_generation_subject_value X=(case X of (input,l,p,c,rows,queries) \<Rightarrow>
    (finite_pair_presentation (finite_option_presentation finite_generation_state_value) (finite_pair_presentation Finite_Target (finite_pair_presentation Finite_Target (finite_pair_presentation Finite_Target (finite_pair_presentation (finite_sequence_presentation finite_history_member_value) (finite_sequence_presentation finite_history_member_value)))))) (map_option digit_allocated_view input,l,p,c,rows,queries))"

definition finite_digit_generation_subject_value where
  "finite_digit_generation_subject_value=finite_bounded_generation_subject_value \<circ> digit_generation_subject_view"

lemma finite_digit_generation_subject_value_exact:
  "finite_digit_generation_subject_value X=finite_digit_generation_subject_value Y \<longleftrightarrow>
    digit_generation_subject_view X=digit_generation_subject_view Y"
  by (simp add: finite_digit_generation_subject_value_def inj_eq[OF finite_bounded_generation_subject_value_injective])

definition finite_indexed_history_value where
  "finite_indexed_history_value=finite_history_index_view_value \<circ> indexed_history_view"

definition finite_history_index_state_value where
  "finite_history_index_state_value=finite_history_index_view_value \<circ> history_index_state_view"

lemma finite_indexed_history_value_exact:
  "finite_indexed_history_value X=finite_indexed_history_value Y \<longleftrightarrow> indexed_history_view X=indexed_history_view Y"
  by (simp add: finite_indexed_history_value_def inj_eq[OF finite_history_index_view_value_injective])

definition finite_history_index_subject_value where
  "finite_history_index_subject_value=(finite_pair_presentation finite_indexed_history_value finite_history_input_value)"

definition finite_digit_generation_original_value where
  "finite_digit_generation_original_value row=(case row of (value,A) \<Rightarrow>
    (finite_pair_presentation finite_bounded_generation_value_value (finite_pair_presentation (finite_option_presentation finite_generation_assessment_value) (finite_sequence_presentation (finite_pair_presentation finite_natural_data finite_boolean_data)))) (value,A,map (\<lambda>f. (f,digit_generation_original_inspect A f)) generation_record_condition_scope))"

text \<open>
  Generation queries retain complete targets, predecessor occurrences, optional
  anchors, all field readings and every original result check. Digit states are
  presented through their owned allocation views, including the next counter.
  History views retain both the complete original state and actual indexed
  members. Full query lists are separate from the original-source projection.
  Original quality values are computed from the actual original assessment.
\<close>
end
