theory Finite_Presented_Native_Construction
 imports Finite_Presented_Replays Finite_Presented_Assessments
   Factor_Native_Node_Investigation
   Factor_Native_Graph_Investigation
begin

definition finite_native_node_metadata_value where
  "finite_native_node_metadata_value=(finite_graph_node_presentation finite_site_data finite_site_data)"

lemma finite_native_node_metadata_value_injective [intro]: "inj finite_native_node_metadata_value"
  unfolding finite_native_node_metadata_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_option_presentation_injective finite_graph_node_presentation_injective finite_graph_presentation_injective finite_site_data_injective finite_use_data_injective finite_environment_presentation_injective finite_native_graph_value_injective finite_boolean_data_injective finite_payload_injective inj_on_id)

definition finite_native_node_targets_value where
  "finite_native_node_targets_value=(finite_collection_presentation (finite_pair_presentation finite_site_data finite_site_data))"

lemma finite_native_node_targets_value_injective [intro]: "inj finite_native_node_targets_value"
  unfolding finite_native_node_targets_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_option_presentation_injective finite_graph_node_presentation_injective finite_graph_presentation_injective finite_site_data_injective finite_use_data_injective finite_environment_presentation_injective finite_native_graph_value_injective finite_boolean_data_injective finite_payload_injective inj_on_id finite_native_node_metadata_value_injective)

definition finite_native_node_subject_value where
  "finite_native_node_subject_value=(finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_native_node_metadata_value finite_native_node_targets_value))"

lemma finite_native_node_subject_value_injective [intro]: "inj finite_native_node_subject_value"
  unfolding finite_native_node_subject_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_option_presentation_injective finite_graph_node_presentation_injective finite_graph_presentation_injective finite_site_data_injective finite_use_data_injective finite_environment_presentation_injective finite_native_graph_value_injective finite_boolean_data_injective finite_payload_injective inj_on_id finite_native_node_metadata_value_injective finite_native_node_targets_value_injective)

definition finite_native_node_result_value where
  "finite_native_node_result_value=(finite_option_presentation (finite_pair_presentation finite_environment_presentation finite_use_data))"

lemma finite_native_node_result_value_injective [intro]: "inj finite_native_node_result_value"
  unfolding finite_native_node_result_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_option_presentation_injective finite_graph_node_presentation_injective finite_graph_presentation_injective finite_site_data_injective finite_use_data_injective finite_environment_presentation_injective finite_native_graph_value_injective finite_boolean_data_injective finite_payload_injective inj_on_id finite_native_node_metadata_value_injective finite_native_node_targets_value_injective finite_native_node_subject_value_injective)

definition finite_native_node_reading_value where
  "finite_native_node_reading_value=(finite_pair_presentation (finite_pair_presentation finite_native_node_metadata_value finite_native_node_targets_value) (finite_pair_presentation (finite_collection_presentation Finite_Payload) (finite_collection_presentation Finite_Payload)))"

lemma finite_native_node_reading_value_injective [intro]: "inj finite_native_node_reading_value"
  unfolding finite_native_node_reading_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_option_presentation_injective finite_graph_node_presentation_injective finite_graph_presentation_injective finite_site_data_injective finite_use_data_injective finite_environment_presentation_injective finite_native_graph_value_injective finite_boolean_data_injective finite_payload_injective inj_on_id finite_native_node_metadata_value_injective finite_native_node_targets_value_injective finite_native_node_subject_value_injective finite_native_node_result_value_injective)

definition finite_native_graph_input_value where
  "finite_native_graph_input_value=(finite_graph_presentation finite_site_data finite_site_data finite_site_data Finite_Payload)"

lemma finite_native_graph_input_value_injective [intro]: "inj finite_native_graph_input_value"
  unfolding finite_native_graph_input_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_option_presentation_injective finite_graph_node_presentation_injective finite_graph_presentation_injective finite_site_data_injective finite_use_data_injective finite_environment_presentation_injective finite_native_graph_value_injective finite_boolean_data_injective finite_payload_injective inj_on_id finite_native_node_metadata_value_injective finite_native_node_targets_value_injective finite_native_node_subject_value_injective finite_native_node_result_value_injective finite_native_node_reading_value_injective)

definition finite_native_graph_subject_value where
  "finite_native_graph_subject_value=(finite_pair_presentation finite_environment_presentation (finite_pair_presentation finite_native_graph_input_value Finite_Payload))"

lemma finite_native_graph_subject_value_injective [intro]: "inj finite_native_graph_subject_value"
  unfolding finite_native_graph_subject_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_option_presentation_injective finite_graph_node_presentation_injective finite_graph_presentation_injective finite_site_data_injective finite_use_data_injective finite_environment_presentation_injective finite_native_graph_value_injective finite_boolean_data_injective finite_payload_injective inj_on_id finite_native_node_metadata_value_injective finite_native_node_targets_value_injective finite_native_node_subject_value_injective finite_native_node_result_value_injective finite_native_node_reading_value_injective finite_native_graph_input_value_injective)

definition finite_native_graph_result_value where
  "finite_native_graph_result_value=(finite_option_presentation (finite_pair_presentation finite_environment_presentation (finite_pair_presentation (finite_collection_presentation (finite_pair_presentation Finite_Payload finite_site_data)) (finite_pair_presentation finite_site_data finite_native_graph_value))))"

lemma finite_native_graph_result_value_injective [intro]: "inj finite_native_graph_result_value"
  unfolding finite_native_graph_result_value_def
  by (intro finite_pair_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_option_presentation_injective finite_graph_node_presentation_injective finite_graph_presentation_injective finite_site_data_injective finite_use_data_injective finite_environment_presentation_injective finite_native_graph_value_injective finite_boolean_data_injective finite_payload_injective inj_on_id finite_native_node_metadata_value_injective finite_native_node_targets_value_injective finite_native_node_subject_value_injective finite_native_node_result_value_injective finite_native_node_reading_value_injective finite_native_graph_input_value_injective finite_native_graph_subject_value_injective)

definition finite_construction_reading_assessment_value where
  "finite_construction_reading_assessment_value reading=(finite_pair_presentation finite_boolean_data (finite_pair_presentation (finite_option_presentation (finite_pair_presentation (finite_collection_presentation reading) (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data finite_boolean_data)))))) finite_boolean_data))"

lemma finite_construction_reading_assessment_value_injective [intro]:
  "inj reading \<Longrightarrow> inj (finite_construction_reading_assessment_value reading)"
  unfolding finite_construction_reading_assessment_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_boolean_data_injective)

definition finite_native_node_cell_value where
  "finite_native_node_cell_value=(finite_pair_presentation finite_native_node_result_value (finite_construction_reading_assessment_value finite_native_node_reading_value))"

definition finite_native_graph_cell_value where
  "finite_native_graph_cell_value=(finite_pair_presentation finite_native_graph_result_value (finite_construction_reading_assessment_value finite_native_graph_value))"

lemma finite_native_node_cell_value_injective [intro]: "inj finite_native_node_cell_value"
  unfolding finite_native_node_cell_value_def
  by (intro finite_pair_presentation_injective finite_native_node_result_value_injective
      finite_construction_reading_assessment_value_injective finite_native_node_reading_value_injective)

lemma finite_native_graph_cell_value_injective [intro]: "inj finite_native_graph_cell_value"
  unfolding finite_native_graph_cell_value_def
  by (intro finite_pair_presentation_injective finite_native_graph_result_value_injective
      finite_construction_reading_assessment_value_injective finite_native_graph_value_injective)

definition finite_native_graph_checked_subject_value where
  "finite_native_graph_checked_subject_value X=Finite_Pair (finite_native_graph_subject_value X)
    ((finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data finite_boolean_data)) (native_graph_input_inspection X))"

lemma finite_native_graph_checked_subject_value_injective [intro]:
  "inj finite_native_graph_checked_subject_value"
  by (rule injI) (simp add: finite_native_graph_checked_subject_value_def
      inj_eq[OF finite_native_graph_subject_value_injective])

definition finite_scoped_report_value where
  "finite_scoped_report_value report=finite_pair_presentation finite_index_sequence_value
    (finite_pair_presentation finite_index_sequence_value
      (finite_pair_presentation report finite_assessment_truth_value))"

lemma finite_scoped_report_value_injective [intro]:
  "inj report \<Longrightarrow> inj (finite_scoped_report_value report)"
  unfolding finite_scoped_report_value_def
  by (intro finite_pair_presentation_injective finite_index_values_injective
      finite_assessment_truth_value_injective)

definition finite_scoped_inspected_packet_value where
  "finite_scoped_inspected_packet_value context cell=
    finite_scoped_report_value (finite_investigation_packet_value context cell)"

lemma finite_scoped_inspected_packet_value_injective [intro]:
  "inj context \<Longrightarrow> inj cell \<Longrightarrow> inj (finite_scoped_inspected_packet_value context cell)"
  unfolding finite_scoped_inspected_packet_value_def
  by (intro finite_scoped_report_value_injective finite_investigation_packet_value_injective)

text \<open>
  Node and graph inputs keep complete environments, metadata, target and discharge
  relations, mappings, roots, outputs and all independent readings. Their common
  assessment envelope retains readiness, the optional readings and five actual
  checks, and rejection. Every graph input inspection is computed on that actual
  original input and transported alongside it; it supplies no assumed prerequisite.
\<close>
end
