theory Finite_Presented_Decisions
  imports Finite_Presented_Native_Programs Factor_Decision_Replay_Assessment
begin

section \<open>Original requirements, evaluations and native replay inspections\<close>

definition finite_native_application_value where
  "finite_native_application_value=(finite_pair_presentation finite_site_data (finite_pair_presentation Finite_Payload (finite_pair_presentation id (finite_pair_presentation (finite_collection_presentation (finite_pair_presentation Finite_Payload id)) (finite_collection_presentation (finite_pair_presentation Finite_Payload finite_call_value))))))"

definition finite_native_rule_value where
  "finite_native_rule_value=(finite_pair_presentation finite_call_value (finite_collection_presentation (finite_pair_presentation Finite_Payload finite_call_value)))"

definition finite_goal_problem_value where
  "finite_goal_problem_value goals=finite_native_source_problem_value
    (finite_pair_presentation goals (finite_collection_presentation id))"

lemma finite_goal_problem_value_injective [intro]: "inj goals \<Longrightarrow> inj (finite_goal_problem_value goals)"
  unfolding finite_goal_problem_value_def
  by (intro finite_native_source_problem_value_injective finite_pair_presentation_injective
      finite_collection_presentation_injective inj_on_id)

definition finite_requirement_subject_value where
  "finite_requirement_subject_value=finite_goal_problem_value (finite_sequence_presentation (finite_goal_value finite_site_data))"

definition finite_requirement_reference_value where
  "finite_requirement_reference_value=finite_native_answers_value id"

definition finite_evaluation_report_value where
  "finite_evaluation_report_value=(finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation (finite_collection_presentation finite_native_application_value) (finite_pair_presentation (finite_collection_presentation finite_native_rule_value) (finite_option_presentation (finite_collection_presentation finite_call_value)))))))"

definition finite_requirement_original_value where
  "finite_requirement_original_value=(finite_pair_presentation (finite_option_presentation finite_native_system_value) (finite_pair_presentation (finite_option_presentation finite_boolean_data) (finite_pair_presentation (finite_option_presentation (finite_collection_presentation finite_call_value)) (finite_option_presentation finite_evaluation_report_value))))"

definition finite_requirement_result_review_value where
  "finite_requirement_result_review_value=(finite_option_presentation (finite_pair_presentation (finite_option_presentation finite_native_system_value) (finite_pair_presentation finite_evaluation_report_value (finite_pair_presentation (finite_collection_presentation (finite_pair_presentation finite_history_certificate_value finite_boolean_data)) (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data finite_boolean_data))))))))))"

definition finite_requirement_assessment_value where
  "finite_requirement_assessment_value=(finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_requirement_result_review_value finite_boolean_data))"

definition finite_native_replay_subject_value where
  "finite_native_replay_subject_value=finite_native_source_problem_value
    (finite_pair_presentation finite_native_schema_proof_value (finite_pair_presentation finite_site_data id))"

definition finite_native_replay_reference_value where
  "finite_native_replay_reference_value=(finite_option_presentation (finite_pair_presentation finite_native_system_value finite_boolean_data))"

definition finite_native_graph_inspection_value where
  "finite_native_graph_inspection_value=(finite_option_presentation (finite_pair_presentation (finite_collection_presentation finite_native_graph_value) (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data finite_boolean_data))))))"

definition finite_native_replay_readings_value where
  "finite_native_replay_readings_value=(finite_pair_presentation (finite_collection_presentation finite_native_system_value) (finite_pair_presentation (finite_collection_presentation finite_application_reading_value) (finite_pair_presentation finite_environment_presentation (finite_pair_presentation (finite_collection_presentation finite_native_system_value) (finite_pair_presentation (finite_collection_presentation finite_application_reading_value) (finite_pair_presentation (finite_collection_presentation finite_native_graph_value) (finite_collection_presentation finite_assertion_readings_value)))))))"

definition finite_native_replay_review_value where
  "finite_native_replay_review_value=(finite_option_presentation (finite_pair_presentation finite_native_graph_inspection_value (finite_pair_presentation finite_native_replay_readings_value (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_boolean_data finite_boolean_data))))))"

definition finite_native_replay_assessment_value where
  "finite_native_replay_assessment_value=(finite_pair_presentation finite_boolean_data (finite_pair_presentation finite_native_replay_review_value finite_boolean_data))"

definition finite_decision_replay_row_review_value where
  "finite_decision_replay_row_review_value=(finite_pair_presentation finite_native_replay_subject_value (finite_pair_presentation finite_native_replay_reference_value finite_native_replay_assessment_value))"

definition finite_decision_replay_inspection_base_value where
  "finite_decision_replay_inspection_base_value=(finite_pair_presentation (finite_pair_presentation finite_history_certificate_value finite_native_replay_result_value) finite_decision_replay_row_review_value)"

lemma finite_native_application_value_injective [intro]: "inj finite_native_application_value"
  unfolding finite_native_application_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id )

lemma finite_native_rule_value_injective [intro]: "inj finite_native_rule_value"
  unfolding finite_native_rule_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective)

lemma finite_requirement_subject_value_injective [intro]: "inj finite_requirement_subject_value"
  unfolding finite_requirement_subject_value_def
  by (intro finite_goal_problem_value_injective finite_native_source_problem_value_injective finite_native_answers_value_injective finite_native_schema_proof_value_injective finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective)

lemma finite_requirement_reference_value_injective [intro]: "inj finite_requirement_reference_value"
  unfolding finite_requirement_reference_value_def
  by (intro finite_native_source_problem_value_injective finite_native_answers_value_injective finite_native_schema_proof_value_injective finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective)

lemma finite_evaluation_report_value_injective [intro]: "inj finite_evaluation_report_value"
  unfolding finite_evaluation_report_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective)

lemma finite_requirement_original_value_injective [intro]: "inj finite_requirement_original_value"
  unfolding finite_requirement_original_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective)

lemma finite_requirement_result_review_value_injective [intro]: "inj finite_requirement_result_review_value"
  unfolding finite_requirement_result_review_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective)

lemma finite_requirement_assessment_value_injective [intro]: "inj finite_requirement_assessment_value"
  unfolding finite_requirement_assessment_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective)

lemma finite_native_replay_subject_value_injective [intro]: "inj finite_native_replay_subject_value"
  unfolding finite_native_replay_subject_value_def
  by (intro finite_native_source_problem_value_injective finite_native_answers_value_injective finite_native_schema_proof_value_injective finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective)

lemma finite_native_replay_reference_value_injective [intro]: "inj finite_native_replay_reference_value"
  unfolding finite_native_replay_reference_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective)

lemma finite_native_graph_inspection_value_injective [intro]: "inj finite_native_graph_inspection_value"
  unfolding finite_native_graph_inspection_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective)

lemma finite_native_replay_readings_value_injective [intro]: "inj finite_native_replay_readings_value"
  unfolding finite_native_replay_readings_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective)

lemma finite_native_replay_review_value_injective [intro]: "inj finite_native_replay_review_value"
  unfolding finite_native_replay_review_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective)

lemma finite_native_replay_assessment_value_injective [intro]: "inj finite_native_replay_assessment_value"
  unfolding finite_native_replay_assessment_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective finite_native_replay_review_value_injective)

lemma finite_decision_replay_row_review_value_injective [intro]: "inj finite_decision_replay_row_review_value"
  unfolding finite_decision_replay_row_review_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective finite_native_replay_review_value_injective finite_native_replay_assessment_value_injective)

lemma finite_decision_replay_inspection_base_value_injective [intro]: "inj finite_decision_replay_inspection_base_value"
  unfolding finite_decision_replay_inspection_base_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective finite_goal_value_injective
      finite_proof_value_injective finite_natural_data_injective finite_boolean_data_injective
      finite_payload_injective finite_site_data_injective finite_use_data_injective
      finite_environment_presentation_injective finite_call_value_injective finite_history_certificate_value_injective
      finite_native_system_value_injective finite_native_graph_value_injective
      finite_native_replay_result_value_injective finite_application_reading_value_injective
      finite_assertion_readings_value_injective inj_on_id finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective finite_native_replay_review_value_injective finite_native_replay_assessment_value_injective finite_decision_replay_row_review_value_injective)

definition finite_decision_replay_inspection_value where
  "finite_decision_replay_inspection_value row=Finite_Pair
    (finite_decision_replay_inspection_base_value row)
    (finite_sequence_presentation (finite_pair_presentation finite_natural_data finite_boolean_data)
      (map (\<lambda>f. (f,decision_replay_row_inspect (snd row) f)) [0..<10]))"

lemma finite_decision_replay_inspection_value_injective [intro]:
  "inj finite_decision_replay_inspection_value"
  by (rule injI) (simp add: finite_decision_replay_inspection_value_def
      inj_eq[OF finite_decision_replay_inspection_base_value_injective])

definition finite_decision_replay_family_value where
  "finite_decision_replay_family_value=(finite_pair_presentation (finite_collection_presentation finite_history_certificate_value) (finite_pair_presentation finite_boolean_data (finite_collection_presentation finite_decision_replay_inspection_value)))"

definition finite_decision_replay_assessment_value where
  "finite_decision_replay_assessment_value=(finite_pair_presentation finite_requirement_assessment_value (finite_option_presentation finite_decision_replay_family_value))"

definition finite_decision_replay_result_value where
  "finite_decision_replay_result_value=(finite_option_presentation finite_decision_replay_value)"

definition finite_decision_replay_context_value where
  "finite_decision_replay_context_value=(finite_option_presentation (finite_pair_presentation finite_requirement_subject_value (finite_pair_presentation (finite_pair_presentation finite_requirement_reference_value finite_requirement_original_value) (finite_sequence_presentation (finite_pair_presentation finite_natural_data finite_decision_replay_result_value)))))"

definition finite_decision_replay_cell_value where
  "finite_decision_replay_cell_value=(finite_option_presentation (finite_pair_presentation finite_requirement_subject_value (finite_pair_presentation finite_requirement_reference_value (finite_pair_presentation finite_decision_replay_result_value finite_decision_replay_assessment_value))))"

lemma finite_decision_replay_family_value_injective [intro]: "inj finite_decision_replay_family_value"
  unfolding finite_decision_replay_family_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective
      finite_history_certificate_value_injective finite_boolean_data_injective finite_natural_data_injective
      finite_decision_replay_inspection_value_injective finite_decision_replay_value_injective finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective finite_native_replay_review_value_injective finite_native_replay_assessment_value_injective finite_decision_replay_row_review_value_injective finite_decision_replay_inspection_base_value_injective)

lemma finite_decision_replay_assessment_value_injective [intro]: "inj finite_decision_replay_assessment_value"
  unfolding finite_decision_replay_assessment_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective
      finite_history_certificate_value_injective finite_boolean_data_injective finite_natural_data_injective
      finite_decision_replay_inspection_value_injective finite_decision_replay_value_injective finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective finite_native_replay_review_value_injective finite_native_replay_assessment_value_injective finite_decision_replay_row_review_value_injective finite_decision_replay_inspection_base_value_injective finite_decision_replay_family_value_injective)

lemma finite_decision_replay_result_value_injective [intro]: "inj finite_decision_replay_result_value"
  unfolding finite_decision_replay_result_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective
      finite_history_certificate_value_injective finite_boolean_data_injective finite_natural_data_injective
      finite_decision_replay_inspection_value_injective finite_decision_replay_value_injective finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective finite_native_replay_review_value_injective finite_native_replay_assessment_value_injective finite_decision_replay_row_review_value_injective finite_decision_replay_inspection_base_value_injective finite_decision_replay_family_value_injective finite_decision_replay_assessment_value_injective)

lemma finite_decision_replay_context_value_injective [intro]: "inj finite_decision_replay_context_value"
  unfolding finite_decision_replay_context_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective
      finite_history_certificate_value_injective finite_boolean_data_injective finite_natural_data_injective
      finite_decision_replay_inspection_value_injective finite_decision_replay_value_injective finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective finite_native_replay_review_value_injective finite_native_replay_assessment_value_injective finite_decision_replay_row_review_value_injective finite_decision_replay_inspection_base_value_injective finite_decision_replay_family_value_injective finite_decision_replay_assessment_value_injective finite_decision_replay_result_value_injective)

lemma finite_decision_replay_cell_value_injective [intro]: "inj finite_decision_replay_cell_value"
  unfolding finite_decision_replay_cell_value_def
  by (intro finite_pair_presentation_injective finite_option_presentation_injective
      finite_collection_presentation_injective finite_sequence_presentation_injective
      finite_history_certificate_value_injective finite_boolean_data_injective finite_natural_data_injective
      finite_decision_replay_inspection_value_injective finite_decision_replay_value_injective finite_native_application_value_injective finite_native_rule_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_evaluation_report_value_injective finite_requirement_original_value_injective finite_requirement_result_review_value_injective finite_requirement_assessment_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_graph_inspection_value_injective finite_native_replay_readings_value_injective finite_native_replay_review_value_injective finite_native_replay_assessment_value_injective finite_decision_replay_row_review_value_injective finite_decision_replay_inspection_base_value_injective finite_decision_replay_family_value_injective finite_decision_replay_assessment_value_injective finite_decision_replay_result_value_injective finite_decision_replay_context_value_injective)

end
