theory Indexed_Generation_Execution
  imports Finite_Term_Word_Streaming Indexed_Generation_Presentation RRA_Indexed_Generation_Investigation Factor_Executable_Environment_Values Native_Execution_Refinements
begin

setup \<open>Finite_Observation_Contracts.export @{term indexed_generation_investigation}\<close>

export_code indexed_generation_report_value indexed_generation_report_selections finite_term_shared_word_fold indexed_generation_packet indexed_generation_indices indexed_generation_inspect
  indexed_generation_original_subject indexed_generation_source_scope indexed_generation_previous_cases indexed_generation_source_equal
  digit_allocated_view finite_environment_artifact_rows finite_environment_bindings finite_artifact_rows
  generation_locus generation_predecessors generation_payload generation_cause
  Generation Finite_Whole Finite_Anchor fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Indexed_Generation_Execution file_prefix indexed_generation

end
