theory Inference_Claim_Input_Execution
  imports Inference_Claim_Execution Finite_Keyed_Fibre_Values Factor_Finite_Child_Premises
begin

export_code
  finite_child_inference_value finite_child_claim_value finite_child_inference_known
  finite_key_fibre_values finite_enumerated_artifact finite_enumerated_environment
  finite_environment_term finite_self_contained_term use_data_term
  inference_claim_construction_library finite_prefixed_observation_outputs
  finite_literal_inference_value finite_literal_inference_known
  finite_keyed_rows_formed finite_keyed_table_comparison finite_keyed_data_comparison finite_key_fibre_holds keyed_table_construction_library
  admission_plan generated_input_execution admission_pair_reasoning_experiment reasoning_counterexample_experiment finite_admission_counter_check
  admitted_reasoning_frontier finite_generated_schema_applications finite_generated_schema_rules finite_learned_investigation natural_learned_investigation
  specialization_report_reasoning_library specialization_report_investigation finite_binding_observation_outputs finite_binding_observation_frontier binding_observation_reasoning_library
  binding_observation_investigation natural_chained_investigation natural_construction_frontier natural_library_coverage reader_library_coverage
  natural_compiled_library inference_reader_construction_library reader_construction_library inference_reader_investigation_library inference_reader_investigation
  binding_observation_construction_library natural_schema_binding_gaps natural_guided_state natural_guided_investigation binding_observation_guided_investigation
  finite_environment_outer_shape binding_list_construction_library finite_binding_list_seed binding_list_construction_investigation Existing_Admission
  Paired_Admission Collected_Admission Pair_Admission_Instruction List_Admission_Instruction Finite_Payload
  Finite_Pair Finite_Target Finite_Whole finite_empty_artifact Finite_Variable
  Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target finite_factor_schema.make finite_schema_conclusion
  finite_schema_premises finite_schema_materials finite_material_pattern.make finite_material_source finite_material_atoms
  finite_material_edges finite_material_counts finite_material_functions finite_reasoning_term_equal fset
  set fset_of_list nat_of_integer integer_of_nat make_finite_schema
  make_finite_material make_application_problem application_entry application_schema application_enumeration
  application_frontier application_requests application_required Separate_Application_Sources Joined_Application_Observations
  Complete_Instance_Condition Existing_Application_Condition Required_Application_Condition application_candidate_subjects application_condition_subjects
  application_observation_scope application_plan_result application_mandatory_targets application_construct_plan application_construction_case_formed
  application_construction_cases_formed application_construction_report application_requirement_subjects application_indexed_part_coverage application_plan_requirements
  application_part_coverage application_uncovered_requirements application_plan_sufficient application_problem_observations finite_selected_observations
  application_investigation_candidates application_construction_result application_condition_holds application_investigation application_investigation_observations
  application_investigation_relation investigation_repairs investigation_extend investigation_revision finite_pattern_observations
  finite_observed_bindings finite_binding_support finite_join_observations finite_schema_observation_sources finite_schema_call_observations
  natural_schema_observation_sources natural_schema_call_observations natural_observation_join natural_observed_bindings natural_binding_support
  natural_observed_schema_applications Finite_Conclusion_Site Finite_Premise_Site Finite_Material_Source_Site Finite_Material_Atoms_Site
  Finite_Material_Edges_Site Finite_Material_Counts_Site Finite_Material_Functions_Site
  in SML module_name Native_Reasoning file_prefix inference_claim_input


end
