theory Native_Source_Development
  imports Factor_Source_Development_Cases Native_Development_Steering
begin

setup \<open>Finite_Observation_Contracts.export @{term development_subject_investigation}\<close>

export_code
  native_source_development source_development_cases source_development_material_input source_development_schema_input source_development_program_input
  source_development_request_input source_development_report_controls source_development_environment source_development_use source_development_root
  source_development_targets source_development_input source_development_outputs source_report_proposals source_report_observations
  source_report_question source_report_execution source_report_selected source_report_installed source_report_stage
  source_report_query source_development_admission source_development_proposals source_development_indices source_development_values
  finite_development_index finite_development_generated finite_development_scope_complete source_development_question construct_source_development
  source_development_packet reconstruct_source_development source_development_boundary native_steered_development development_steering_choice
  steered_development_result development_steering_packet development_subject_table development_methods development_facets
  development_producer_inspect development_case_inputs native_development_indices development_source development_source_use
  development_source_root development_generator_entry development_problem development_conditions development_scope_criticism
  development_selected_facets condition_source condition_source_use condition_source_root condition_goals
  development_generation development_compiled_conditions development_observed_conditions development_scope_review development_comparison
  development_revision development_condition_input native_development_question_input workflow_source workflow_source_use
  workflow_source_root workflow_entry workflow_outputs finite_environment_artifact_rows finite_environment_bindings
  finite_artifact_rows fset sorted_list_of_fset finite_system_interfaces finite_system_clauses
  finite_schema_conclusion finite_schema_premises finite_schema_materials finite_material_source finite_material_atoms
  finite_material_edges finite_material_counts finite_material_functions nat_of_integer integer_of_nat
  finite_enumerated_environment finite_enumerated_artifact Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair
  Finite_Pattern_Target Finite_Payload Finite_Pair Finite_Target Finite_Whole
  Finite_Anchor Existing_Admission Paired_Admission Collected_Admission development_steering_question
  development_selected_methods development_criterion_rows development_method_row development_table_condition native_development_batch
  native_development_packet construct_native_development native_development_admission native_development_boundary reconstruct_native_development
  development_producer_packet development_condition_outputs development_review_input development_question_value development_generated_values
  development_condition_reference development_reference workflow_scope_result finite_native_generation finite_generated_outputs
  development_workflow_requirements requirement_source requirement_source_use requirement_source_root requirement_goals
  requirement_candidates development_workflow_stages finite_graph_inferences finite_graph_discharges Schema_Proof
  Finite_Inference Finite_Assertion Workflow_Input Workflow_Values Workflow_Generated
  Workflow_Finished Workflow_Unavailable Workflow_Executed native_workflow_inspect set
  in Eval module_name Native_Source_Development file_prefix native_source_development

end
