theory Native_Graph_Investigation_Execution
  imports Factor_Native_Graph_Investigation
begin

setup \<open>Finite_Observation_Contracts.export @{term native_graph_investigation}\<close>

export_code native_graph_indices native_graph_report_packet native_graph_inspect native_graph_input_inspection
  finite_graph_inferences finite_graph_discharges
  finite_environment_artifact_rows finite_environment_bindings finite_artifact_rows
  Finite_Inference Finite_Assertion Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  fset set nat_of_integer integer_of_nat
  in SML module_name Native_Graph_Investigation_Execution file_prefix native_graph_investigation

end
