theory Native_Certificate_Replay_Execution
  imports Factor_Native_Replay_Investigation Native_Execution_Refinements
begin

setup \<open>Finite_Observation_Contracts.export @{term native_replay_investigation}\<close>

export_code native_replay_packet native_replay_indices native_replay_inspect native_replay_family_inspect
  finite_graph_inferences finite_graph_discharges finite_system_interfaces finite_system_clauses
  finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_source finite_material_atoms finite_material_edges finite_material_counts finite_material_functions
  finite_environment_artifact_rows finite_environment_bindings finite_artifact_rows
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target
  Schema_Proof Finite_Inference Finite_Assertion Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Native_Certificate_Replay_Execution file_prefix certificate_replay

end
