theory Native_Certificate_Development_Execution
  imports Factor_Native_Certificate_Development
begin

setup \<open>Finite_Observation_Contracts.export @{term native_certificate_investigation}\<close>

export_code native_certificate_development_packet native_certificate_indices native_certificate_inspect
  native_certificate_criticism_accept native_certificate_family_coverage_inspect
  finite_graph_inferences finite_graph_discharges finite_system_interfaces finite_system_clauses
  finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_source finite_material_atoms finite_material_edges finite_material_counts finite_material_functions
  finite_environment_artifact_rows finite_environment_bindings finite_artifact_rows
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target
  Schema_Proof Finite_Inference Finite_Assertion Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  fset set nat_of_integer integer_of_nat
  in SML module_name Native_Certificate_Development_Execution file_prefix certificate_development

end
