theory Native_Requirement_Investigation_Execution
  imports Factor_Native_Requirement_Sharing Native_Execution_Refinements
begin

setup \<open>Finite_Observation_Contracts.export @{term native_requirement_investigation}\<close>

export_code native_requirement_indices native_requirement_report native_requirement_assess
  native_requirement_shared_packet
  native_requirement_optional_inspect native_requirement_investigation_report
  finite_environment_artifact_rows finite_environment_bindings
  finite_system_interfaces finite_system_clauses
  finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_source finite_material_atoms finite_material_edges finite_material_counts finite_material_functions
  finite_artifact_rows Finite_Whole Finite_Anchor
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target
  Finite_Target Finite_Payload Finite_Pair Existing_Admission Paired_Admission Collected_Admission
  fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Native_Requirement_Investigation_Execution file_prefix native_requirement_investigation

end
