theory Native_Extension_Execution
  imports Factor_Finite_Native_Extension_Cases Factor_Finite_Native_Controls Factor_Executable_Artifact_Values Native_Execution_Refinements
    Native_Package_Presentation
begin

section \<open>Execute the actual package construction and complete native recovery\<close>

export_code finite_native_extension_report native_extension_report_value source_requirement_variants
  native_control_indices finite_term_shared_word_fold finite_native_control_report
  finite_system_interfaces finite_system_clauses
  finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_source finite_material_atoms finite_material_edges finite_material_counts finite_material_functions
  finite_artifact_rows Finite_Whole Finite_Anchor
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target
  fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Native_Extension_Execution file_prefix native_extensions

end
