theory Quoted_History_Execution
  imports Factor_Quoted_History_Investigation Factor_Executable_Artifact_Values Native_Execution_Refinements
begin

setup \<open>Finite_Observation_Contracts.export @{term quoted_history_investigation}\<close>

export_code quoted_history_packet digit_history_indices digit_history_question_inspect digit_history_view digit_history_state_view
  digit_history_subject_view bounded_history_subject_view digit_history_source_scope digit_history_source_cases
  digit_history_source_equal digit_history_source_index digit_history_chain_length
  raw_digit_required_history raw_required_history required_history_source required_history_source_use
  required_history_source_root required_history_goals required_history_entry required_history_policy
  required_history_policy_use required_history_material required_history_members
  generation_locus generation_payload generation_cause generation_predecessors
  finite_artifact_rows finite_environment_artifact_rows finite_environment_bindings
  History_Step Schema_Proof Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  Existing_Admission Paired_Admission Collected_Admission fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Digit_History_Execution file_prefix quoted_history

end
