theory Requirement_Artifact_Execution
  imports Requirement_Artifact_Execution_Base Native_Execution_Refinements Requirement_Plan_Presentation
begin

export_code requirement_artifact_reports requirement_plan_report_value requirement_plan_counters
  finite_term_shared_word_fold checked_requirement_source checked_requirement_reports
  admission_sequence admission_sequence_reports portable_requirement_reports
  portable_requirement_execution portable_table_diagnostics portable_table_goals
  Existing_Admission Paired_Admission Collected_Admission Pair_Admission_Instruction List_Admission_Instruction
  Finite_Payload Finite_Pair Finite_Target Finite_Whole finite_empty_artifact
  finite_reasoning_term_equal nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Requirement_Plans file_prefix requirement_artifacts

end
