theory Requirement_Decision_Execution
  imports Factor_Requirement_Decision_Investigation
begin

setup \<open>Finite_Observation_Contracts.export @{term requirement_decision_investigation}\<close>

export_code requirement_decision_packet requirement_decision_indices requirement_decision_inspect requirement_decision_cell_inspect
  finite_system_interfaces finite_system_clauses finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_source finite_material_atoms finite_material_edges finite_material_counts finite_material_functions
  finite_environment_artifact_rows finite_environment_bindings finite_artifact_rows
  finite_graph_inferences finite_graph_discharges
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target
  Schema_Proof Finite_Inference Finite_Assertion Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  Existing_Admission Paired_Admission Collected_Admission
  fset set nat_of_integer integer_of_nat
  in SML module_name Requirement_Decision_Execution file_prefix requirement_decisions

end
