theory Required_Cause_Execution
  imports Factor_Required_Cause_Investigation Factor_Executable_Environment_Values Factor_Finite_Judgment_Reading_Sharing Native_Execution_Refinements
begin

setup \<open>Finite_Observation_Contracts.export @{term required_cause_investigation}\<close>

export_code required_cause_packet required_cause_indices decision_row_inspect decision_family_inspect
  finite_environment_artifact_rows finite_environment_bindings finite_artifact_rows
  finite_system_interfaces finite_system_clauses finite_schema_conclusion finite_schema_premises finite_schema_materials
  finite_material_source finite_material_atoms finite_material_edges finite_material_counts finite_material_functions
  finite_graph_inferences finite_graph_discharges
  generation_locus generation_predecessors generation_payload generation_cause
  Finite_Variable Finite_Pattern_Payload Finite_Pattern_Pair Finite_Pattern_Target
  Schema_Proof Finite_Inference Finite_Assertion Finite_Target Finite_Payload Finite_Pair Finite_Whole Finite_Anchor
  Existing_Admission Paired_Admission Collected_Admission fset set nat_of_integer integer_of_nat
   complete_artifact_reference complete_object_reference complete_empty_artifacts complete_object_table_rows complete_environment_artifact_objects complete_term_reference complete_empty_terms
  in Eval module_name Required_Cause_Execution file_prefix required_cause

end
