theory Requirement_Decision_Presentation
 imports Finite_Presented_Cause_Families Finite_Term_Words
begin

definition requirement_decision_presented_packet_value where
 "requirement_decision_presented_packet_value=(finite_investigation_packet_value finite_requirement_context_value finite_requirement_cell_value)"

lemma requirement_decision_presented_packet_value_injective [intro]: "inj requirement_decision_presented_packet_value"
 unfolding requirement_decision_presented_packet_value_def
 by (intro finite_pair_presentation_injective finite_option_presentation_injective finite_collection_presentation_injective finite_sequence_presentation_injective finite_inspected_value_injective finite_environment_presentation_injective finite_use_data_injective finite_site_data_injective finite_payload_injective finite_natural_data_injective finite_boolean_data_injective finite_goal_value_injective finite_history_certificate_value_injective finite_native_replay_subject_value_injective finite_native_replay_reference_value_injective finite_native_replay_result_value_injective finite_native_replay_assessment_value_injective finite_requirement_decision_body_value_injective finite_requirement_subject_value_injective finite_requirement_reference_value_injective finite_requirement_original_value_injective finite_requirement_assessment_value_injective finite_cause_subject_value_injective finite_cause_report_value_injective finite_literal_seed_value_injective finite_judgment_context_value_injective finite_application_reading_value_injective finite_native_system_value_injective finite_replay_row_base_value_injective finite_requirement_result_value_injective finite_requirement_context_value_injective finite_requirement_cell_value_injective finite_original_cause_request_value_injective finite_required_cause_subject_value_injective finite_required_cause_source_value_injective finite_required_cause_alignment_value_injective finite_required_cause_policy_value_injective finite_required_cause_report_value_injective finite_certified_cause_context_value_injective finite_required_cause_context_value_injective finite_replay_inspected_row_value_injective finite_decision_family_value_injective finite_investigation_packet_value_injective finite_scoped_report_value_injective)

definition requirement_decision_presented_report where
 "requirement_decision_presented_report ws selections=(let packet=requirement_decision_packet ws selections in
   (requirement_decision_indices,ws,packet,assessment_truth_rows requirement_decision_cell_inspect [0..<8] (fst packet)))"

definition requirement_decision_report_value where
 "requirement_decision_report_value ws selections=finite_scoped_report_value
   requirement_decision_presented_packet_value (requirement_decision_presented_report ws selections)"

theorem requirement_decision_report_value_exact:
 "requirement_decision_report_value ws selections=requirement_decision_report_value vs choices \<longleftrightarrow>
   requirement_decision_presented_report ws selections=requirement_decision_presented_report vs choices"
 unfolding requirement_decision_report_value_def
 by (intro inj_eq finite_scoped_report_value_injective requirement_decision_presented_packet_value_injective)

theorem requirement_decision_report_word_exact:
 "finite_term_shared_word (requirement_decision_report_value ws selections)=
   finite_term_shared_word (requirement_decision_report_value vs choices) \<longleftrightarrow>
   requirement_decision_presented_report ws selections=requirement_decision_presented_report vs choices"
 by (simp only: finite_term_shared_word_injective requirement_decision_report_value_exact)

definition requirement_decision_report_selections :: "nat list list" where
 "requirement_decision_report_selections=[[],[0,1,2,7],[0..<8]]"
end
