#!/usr/bin/env python3
"""Write idea-candidates.md: the library's own vocabulary, for the owner to curate the base's idea tiers from.

Mechanical, no reading added: every word of a theory name that at least MIN theories carry is a notion; its
founding theory is the first in THEORY_MAP.md's (import) order that carries it; beside it stand that theory's
size, how many theories depend on it transitively, and the opening of the map's own description. The owner
marks what belongs in the base; base-load.txt's pinned idea tiers are then written from the marks.
"""
import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from digest import held_text  # noqa: E402
PROJECT = os.path.dirname(os.path.dirname(HERE))
MIN = 4
sys.setrecursionlimit(20000)
rows, imports, content = [], {}, {}
for ln in open(os.path.join(PROJECT, "THEORY_MAP.md")):
    m = re.match(r"\| ([A-Za-z_0-9]+) \| ([^|]*) \| (.*) \|\s*$", ln)
    if m and m.group(1) != "Theory":
        rows.append(m.group(1)); imports[m.group(1)] = [x.strip() for x in m.group(2).split(",")]; content[m.group(1)] = m.group(3).strip()
order = {n: i for i, n in enumerate(rows)}
deps = collections.defaultdict(set)
for n in rows:
    for p in imports[n]:
        if p in order:
            deps[p].add(n)
memo = {}
def closure(n):
    if n not in memo:
        memo[n] = set()
        s = set()
        for d in deps[n]:
            s.add(d); s |= closure(d)
        memo[n] = s
    return memo[n]
def tok(n):
    p = os.path.join(PROJECT, "theories", n + ".thy")  # as held: statements, without proofs
    return len(held_text(p)[0].encode()) / 2.46 / 1000 if os.path.exists(p) else 0
held = set()
for ln in open(os.path.join(HERE, "base-load.txt")):
    m = re.match(r"theories/([A-Za-z_0-9]+)\.thy", ln.strip())
    if m:
        held.add(m.group(1))
words = collections.defaultdict(list)
for n in rows:
    for w in n.split("_"):
        if len(w) > 2:
            words[w].append(n)
def founding_theories():
    """Founding theory of every notion (a word carried by at least MIN theory names), in import order."""
    found = {min(ns, key=lambda n: order[n]) for w, ns in words.items() if len(ns) >= MIN}
    return sorted((f for f in found if os.path.exists(os.path.join(PROJECT, "theories", f + ".thy"))), key=lambda n: order[n])


def main():
    out = ["# Idea candidates: the library's vocabulary and where each notion is founded", "",
           "Generated by idea_candidates.py from THEORY_MAP.md. Mark a row with `x` in the first column to pin its",
           "founding theory in the base; rows already pinned are marked `=`. Size is tokens as held (statements,",
           "proofs omitted); dependents is how",
           "many theories import it directly or indirectly.", "",
           "| pin | notion | theories | founding theory | size | dependents | the map's description opens |", "|---|---|---|---|---|---|---|"]
    table = []
    for w, ns in words.items():
        if len(ns) < MIN:
            continue
        f = min(ns, key=lambda n: order[n])
        table.append((len(closure(f)), len(ns), w, f))
    for d, c, w, f in sorted(table, reverse=True):
        out.append(f"| {'=' if f in held else ' '} | {w} | {c} | {f} | {tok(f):.1f}K | {d} | {content[f][:110]} |")
    open(os.path.join(HERE, "idea-candidates.md"), "w").write("\n".join(out) + "\n")
    total = sum(tok(f) for f in {f for _, _, _, f in table})
    print(f"idea-candidates.md: {len(table)} notions, {len({f for _, _, _, f in table})} distinct founding theories, {total:.0f}K tokens if all were pinned; {len(held)} theories pinned now")


if __name__ == "__main__":
    main()
