"""Break one repair at a time and see whether the test meant to catch it does.

Not part of the harness and nothing runs it automatically: it is the check that found, on 2026-09-21, that
two of the day's repairs were held by nothing and that a third had a branch nothing could reach. Run it from
.claude/orchestration after changing any of the repairs it names, and add a case for every new one. It always
restores the file it broke, in a finally.
"""
import shutil, subprocess, sys, os
ORCH = "/home/julius/structure_and_semantics/.claude/orchestration"
os.chdir(ORCH)
CASES = [
    ("stop.sh", 'if [ -n "$KEEP_WARM" ]; then', 'if false; then', "keeps_the_warmth_daemon",
     "stop.sh --keep-warm leaves the daemon"),
    ("v2.py", 'and k not in skip)', 'and True)', "graphs_shape", "graph_shape's skip"),
    ("v2.py", 'if os.path.isfile(dotgit):', 'if False:', "copy_of_the_harness_in_a_worktree", "_one_tree"),
    ("v2.py", 'if tid not in tasks or tasks[tid].get("status") == "completed":',
     'if tid not in tasks:', "startable_agrees", "startable's completed check"),
    ("v2.py", 'n = max(high, max(used, default=0)) + 1', 'n = max(used, default=0) + 1',
     "high_water_mark", "allocation above the mark"),
    ("v2.py", 'or stage == "unformed" or orphan', 'or orphan', "not_in_form_is_named_again", "the unformed notice"),
    ("ctx_gauge.py", 'v2.py propose {task}', 'v2.py briefed {task}', "no_message_names_a_command", "the command-name test"),
    ("worker-settings.json", '"Bash|TaskCreate|TaskUpdate|', '"Bash|TaskCreate|', "guarded_tool_reach", "the guard's matcher"),
    ("work_meter.py", 'ISABELLE_SYMBOL.sub(" ", ', '(lambda s: s)(', "isabelle_cartouche", "the cartouche strip"),
    ("watchdog.py", 'v2.wake_planner(name)  # cold', 'None  # cold', "sealed_planners_box", "planner_mail"),
    ("v2.py", 'holds_tree = tree_writer(st) == tid', 'holds_tree = False', "holds_the_working_tree", "the tree notice"),
    ("v2.py", 'if briefs and why:', 'if False:', "as_much_independent_work", "the width detention"),
    ("v2.py", 'if c and not ROLES.get(c["role"], {}).get("graph"):', 'if False:', "sets_what_a_task_waits_on",
     "blockers' permission"),
    ("v2.py", 'w["tasks"][tid]["stage"] = "done"\n        log("the stage of "',
     'pass\n        log("the stage of "', "follows_the_list", "reconcile_stages"),
    ("ctx_gauge.py", '.get("stage") not in ("running", "fixing", None)', ' and False', "taken_on_may_end", "may_end"),
    ("v2.py", 'if not TREES:\n        return PROJECT', 'if False:\n        return PROJECT',
     "left_behind_does_not_capture", "worktree_of's guard"),
    ("v2.py", '    if tree:\n        rel = os.path.relpath(tree, PROJECT)\n        return (f"**Your working tree',
     '    if tree or os.path.isdir(os.path.join(PROJECT, TREE_DIR, str(tid))):\n        rel = os.path.relpath(tree or os.path.join(PROJECT, TREE_DIR, str(tid)), PROJECT)\n        return (f"**Your working tree',
     "told_the_tree_it_is_started_in", "tree_text reads the tree it is given and nothing else"),
    ("session_row.py", 'if r.get("name") == sys.argv[1] and ours(r.get("cwd")):',
     'if r.get("name") == sys.argv[1] and os.path.realpath(r.get("cwd", "")) == os.path.realpath(PROJECT):',
     "seen_there_and_resumed_there", "the listing finds a session in its tree"),
    ("v2.py", 'return path if (rec or {}).get("tree") and os.path.isdir(path) else PROJECT', 'return PROJECT',
     "seen_there_and_resumed_there", "a session is resumed where it was started"),
    ("v2.py", '    for d in transcript_dirs():', '    for d in [TRANSCRIPTS]:',
     "read_from_its_tree_s_transcript", "a transcript kept under a tree's directory"),
    ("v2.py", '    os.execv(sys.executable, [sys.executable, target, *argv[1:]])', '    return None',
     "hands_every_call_to_the_one_harness", "_one_harness"),
    ("v2.py", '    trouble = tree_trouble(path)\n    if trouble:\n        worktree_gone(tid)',
     '    trouble = []\n    if trouble:\n        worktree_gone(tid)',
     "refuses_every_check_is_not_handed_out", "a tree from an inconsistent HEAD"),
    ("v2.py", 'if os.path.exists(harness) and ONE_HARNESS not in', 'if False and ONE_HARNESS not in',
     "harness_would_not_hand_over", "a tree whose harness would not hand over"),
    ("v2.py", '    there = sorted(named & set(changed_paths()))', '    there = []',
     "brief_names_what_stands_uncommitted", "a task whose brief names uncommitted work"),
    ("v2.py", '    if done:\n        waits = landing_wait(tid)', '    if False:\n        waits = landing_wait(tid)',
     "waits_for_the_work_it_stands_on", "the landing wait"),
    ("v2.py", '        todo += blockers(d)', '        pass',
     "waits_for_the_work_it_stands_on", "the landing wait through the tasks between"),
    ("v2.py", '    if apart((rec or {}).get("task")):\n        return None  # its own tree',
     '    if False:\n        return None  # its own tree', "holds_do_not_reach", "tree_holder in a tree"),
    ("v2.py", 'and os.path.exists(os.path.join(BUILD, tid, "finalize.json")) and not apart(tid)), None)',
     'and os.path.exists(os.path.join(BUILD, tid, "finalize.json"))), None)', "holds_do_not_reach",
     "finalizing across trees"),
    ("v2.py", 'if t.get("stage") == "checking" and not apart(tid)), None)', 'if t.get("stage") == "checking"), None)',
     "holds_do_not_reach", "check_isolation across trees"),
    ("v2.py", '    elsewhere = check_elsewhere(tid, check or "")', '    elsewhere = []',
     "hands_over_its_tree_s_files", "a check that names the one tree"),
    ("v2.py", '    tree = worktree_of(tid)  # the finalizer checks and commits there', '    tree = PROJECT  #',
     "hands_over_its_tree_s_files", "finalize's files in the task's tree"),
    ("v2.py", '    d, tree = (os.path.join(BUILD, tid), worktree_of(tid)) if tid else (None, PROJECT)',
     '    d, tree = (os.path.join(BUILD, tid), PROJECT) if tid else (None, PROJECT)', "the_tree_the_work_stands_in",
     "a read in the task's tree"),
    ("v2.py", '    tree = worktree_of(tid) if apart(tid) else None  # the work it judges', '    tree = None  #',
     "the_tree_the_work_stands_in", "a reviewer started where the work stands"),
    ("work_meter.py", '    if here != v2.PROJECT:\n        main = ', '    if False:\n        main = ',
     "writes_there_and_not_in_the_one_tree", "a session in a tree writing the one tree"),
    ("v2.py", 'stage not in ("running", "parked", *FINISHING):', 'stage != "running":',
     "empty_tree_stays_while", "an empty tree kept while its task is under way"),
    ("finalize.py", '    worse = v2.new_trouble(tree)\n    if worse:', '    worse = []\n    if worse:',
     "leave_head_inconsistent_is_refused", "the finalizer's consistency gate"),
    ("v2.py", '    return [x for x in trouble_of(tree, target, changed) if x not in before]',
     '    return trouble_of(tree, target, changed)', "trouble_head_already_has", "only new trouble refused"),
    ("commit_gate.py", 'if worse:', 'if False:', "manual_commit_is_held", "the git hook"),
    ("finalize.py", '"Bring what landed meanwhile into task {tid}", main, tree=tree)',
     '"Bring what landed meanwhile into task {tid}", "HEAD", tree=tree)', "checked_with_what_landed",
     "what landed brought into the branch"),
    ("finalize.py", '            ok, tail = recheck(tid, tree, deadline)', '            ok, tail = True, ""',
     "does_not_stand_with_what_landed", "the landing re-check"),
    ("finalize.py", 'if git("rev-parse", "HEAD", tree=tree).stdout.strip() != before:', 'if True:',
     "nothing_is_checked_again", "no re-check when nothing landed"),
    ("v2.py", '                t.update(stage="fixing", fixing=None, fix_text=text)',
     '                to_planner(st, tid, "the finalizer", text)', "goes_back_to_be_fixed",
     "a failed landing goes to a quick fix"),
    ("finalize.py", '        if not held:\n            return refuse(', '        if False:\n            return refuse(',
     "one_landing_at_a_time", "the landing lock"),
    ("v2.py", '    absolute = one_tree_paths(text)', '    absolute = []', "absolute_path_is_not_in_form",
     "a brief naming the repository by its absolute path"),
    ("finalize.py", '    unreviewed = unreviewed_work(tid, files)\n', '    unreviewed = {}\n',
     "nothing_is_committed_before_its_review", "review before commit, at the finalizer"),
    ("work_meter.py", 'if inp.get("status") == "completed" and task.get("status") != "completed" and kind in',
     'if False and kind in', "not_completed_by_hand", "the planner completing a build by hand"),
    ("v2.py", '    reopen_unlanded()  # first:', '    pass  # first:', "completed_without_landing",
     "a build completed without landing taken back"),
    ("work_meter.py", '        refused = v2.goal_refusal(other,', '        refused = None and v2.goal_refusal(other,',
     "hung_at_the_end_of_a_chain", "a goal hung by addBlocks"),
    ("v2.py", '    goal = goal_refusal(tid, want)\n', '    goal = None\n', "hangs_no_further_goal",
     "blockers' depth rule"),
    ("v2.py", '            if t.get("stage") not in ("proposed", "planner"):',
     '            t["stage"] = "reviewing"\n            if t.get("stage") not in ("proposed", "planner"):',
     "records_its_result_after_proposing", "a brief's result keeping its proposal"),
    ("v2.py", '    placing = proposal_text(bid, entries)\n', '    placing = json.dumps(entries)\n',
     "what_placing_needs", "the planner told what placing needs"),
    ("finalize.py", '    if not m or not os.path.exists(os.path.join(cwd, m.group(2))):\n        return check',
     '    if True:\n        return check', "fresh_output", "a re-run check's fresh output"),
    ("work_meter.py", 'or any(t.startswith(trees) and copy in t for t in targets):', ':',
     "tree_s_copy_of_the_harness", "a tree's copy of the harness written by a session"),
    ("v2.py", '    if ahead and int(ahead.strip() or 0):', '    if False:', "unmerged_work_is_not_reset",
     "a branch with unmerged work reset by a new tree"),
    ("finalize.py", '    with (v2.landing(deadline, shared=True) if not v2.apart(tid) else contextlib.nullcontext(True)) as held:',
     '    with contextlib.nullcontext(True) as held:', "does_not_move_under_a_check", "a one-tree check holding main"),
    ("v2.py", '        if deepest > GRAPH_DEPTH:\n            out.append((name, deepest))', '        if False:\n            out.append((name, deepest))',
     "admits_its_own_value", "the per-chain limit"),
    ("v2.py", '        deepest = max([depths.get(b, 0) for b in e.get("blockedBy") or []',
     '        deepest = max(depths.values(), default=0) or max([depths.get(b, 0) for b in e.get("blockedBy") or []',
     "short_chain_is_admitted", "per chain, not the graph's longest"),
    ("v2.py", '        if name in detail or brief_kind((after.get(name) or {}).get("description") or "") == "review":',
     '        if name in detail:', "admits_its_own_value", "reviews exempt from the limit"),
    ("v2.py", '    detail = spliced(group, after)  # read on the graph',
     '    detail = spliced(group, {t["id"]: t for t in all_tasks()})  # read on the graph',
     "splice_made_by_re_pointing", "a splice read on the edited graph"),
    ("v2.py", '            out.append(f"task {tid} would still wait on {\', \'.join(gone)}, which this edit deletes',
     '            (f"task {tid} would still wait on {\', \'.join(gone)}, which this edit deletes',
     "waiting_on_a_deleted_task", "an edit leaving a task waiting on a deleted one"),
    ("v2.py", '        for tid, was in kept.items():\n            with contextlib.suppress(Exception):',
     '        for tid, was in []:\n            with contextlib.suppress(Exception):',
     "takes_back_everything or all_of_it_or_none", "a failed edit, or a failed placement, put back"),
    ("v2.py", '    link_reviews()\n    st = peek()', '    st = peek()', "planner_writes_is_linked",
     "a planner's review task linked"),
    ("v2.py", '        if x == "--":', '        if x == "---":', "double_dash_are_each", "batched groups"),
    ("v2.py", '        for tid in rest[:max(n, 1)]:', '        for tid in rest[:1]:', "several_ids_directly",
     "tell to several tasks"),
    ("v2.py", '    if name.startswith("task:"):', '    if False:', "takes_task_briefs_and_proposals", "the gather reading a task"),
    ("v2.py", '    for key in keys:\n        e = next(', '    for key in keys[:1]:\n        e = next(',
     "takes_task_briefs_and_proposals", "several briefs of a proposal"),
    ("v2.py", '[b for b in waited if b != op.get("instead")]', 'waited', "accept_wires_feeds",
     "a splice taken off the brief task"),
    ("work_meter.py", '            or (k == "own" and brief["task_tools"] and graph_edited(inp, response)):',
     '            or False:', "graph_through_the_harness", "a graph edit through the harness counted as production"),
    # the reading limits (the owner, 2026-09-21): a batch one read, both tiers, the bytes of a read and a batch
    ("work_meter.py", '            batches.add(mid)', '            batches.add(c.get("id"))', "batch_is_one_read",
     "a batch counted once"),
    ("work_meter.py", '    return call.get("id") not in refused and call.get("name") in GUARDED_TOOLS',
     '    return True and call.get("name") in GUARDED_TOOLS', "refused_read_takes_nothing", "a refused read not counted"),
    ("work_meter.py", 'v2\\.py\\s+(?:read|proposal|graph|status|who)', 'v2\\.py\\s+(?:proposal|graph|status|who)',
     "any_source_is_a_read_like_any_other", "v2.py read, a read"),
    ("work_meter.py", '    st["reserve"] = min(RESERVE, max(0, reserve_of(st) - drawn) + 1)',
     '    st["reserve"] = min(RESERVE, max(0, reserve_of(st) - drawn) + 0)', "restarts_the_first_tier_and_gives_one_back",
     "a production giving one back"),
    ("work_meter.py", '    st["reserve"] = min(RESERVE, max(0, reserve_of(st) - drawn) + 1)',
     '    st["reserve"] = max(0, reserve_of(st) - drawn) + 1', "never_grows_past_its_size", "the reserve's ceiling"),
    ("work_meter.py", '    st["reserve"] = min(RESERVE, max(0, reserve_of(st) - drawn) + 1)',
     '    st["reserve"] = min(RESERVE, max(0, reserve_of(st)) + 1)', "restarts_the_first_tier_and_gives_one_back",
     "what the reserve gave, paid"),
    ("work_meter.py", '        if drawn > reserve_of(st):', '        if drawn > reserve_of(st) + 1:',
     "first_tier_then_the_reserve_then_nothing", "the reserve's last read"),
    ("work_meter.py", '    return max(0, min(st.get("reserve", RESERVE), RESERVE))', '    return max(0, st.get("reserve", RESERVE))',
     "larger_reserve_holds_no_more", "a reserve bounded by the setting"),
    ("work_meter.py", '            st["refused"] = (st.get("refused") or []) + [hook["tool_use_id"]]',
     '            st["refused"] = st.get("refused") or []', "refused_read_takes_nothing", "a refusal remembered"),
    ("work_meter.py", '    out["root"] = v2.tree_of(rec)', '    out["root"] = v2.PROJECT', "credited_for_what_it_writes_there",
     "production measured in the session's tree"),
    ("ctx_gauge.py", '            v2.say_once(f"record-failed-{session}"', '            (lambda *a, **k: None)(f"record-failed-{session}"',
     "record_that_fails_is_said", "a failed record said"),
    ("work_meter.py", '        fcntl.flock(lock, fcntl.LOCK_EX)\n        st = load(session)', '        pass\n        st = load(session)',
     "written_under_its_lock", "the meter's lock"),
    ("work_meter.py", '        if read >= BATCH:', '        if False:', "batch_reads_at_most_its_bytes", "the batch's bytes"),
    ("work_meter.py", '(st.get("batches") or {}).get(batch, 0) + shown})', '0})', "batch_reads_at_most_its_bytes",
     "what a batch has read, added"),
    ("work_meter.py", '            if size is not None and size > READ_BYTES:', '            if False:',
     "longer_than_a_read_shows", "a known read over its bytes"),
    ("work_meter.py", '                if total > READ_BYTES:\n                    break', '                if total > READ_BYTES + 200:\n                    break',
     "longer_than_a_read_shows", "the lines that fit"),
    ("work_meter.py", '    return allow(dict(inp, command=f"{prefix}{WRAP_OPEN}{body}',
     '    return None and allow(dict(inp, command=f"{prefix}{WRAP_OPEN}{body}', "every_output_is_cut", "an output cut"),
    ("work_meter.py", '    m = re.match(r"^(\\s*cd\\s+', '    m = None and re.match(r"^(\\s*cd\\s+', "every_output_is_cut",
     "a leading cd kept outside the cut"),
    ("work_meter.py", '            v2.say_once("cut-not-applied"', '            (lambda *a, **k: None)("cut-not-applied"',
     "cut_that_did_not_take", "a cut that did not take, said"),
    ("work_meter.py", '        return len(((response.get("stdout") or "") + (response.get("stderr") or "")).encode())',
     '        return 0', "batch_reads_at_most_its_bytes", "what a command showed"),
    ("work_meter.py", '            return "read" if V2_READS.search(c) else "own"', '            return "own"',
     "reading_commands_are_reads", "the harness's reading commands"),
    ("v2.py", '{text if seen else one_read(text)}', '{text}', "every_source_is_a_read", "a source as one read"),
    ("v2.py", '        if unshown or (out and size + len(part.encode()) > READ_BYTES):', '        if False:',
     "one_read_shows_at_most_a_read", "a read of several sources, bounded"),
    ("v2.py", '            unshown.append(src)  # the first source', '            pass  # the first source',
     "one_read_shows_at_most_a_read", "what a read had no room for, named"),
    # reads of lines in context filtered, not refused (the owner, 2026-09-21)
    ("work_meter.py", '            if end >= first and not missing:', '            if False:', "lines_in_context_is_filtered",
     "a read wholly in context"),
    ("work_meter.py", '            if missing and missing != [(first, end)]:', '            if False:',
     "lines_in_context_is_filtered", "a read partly in context, filtered"),
    ("work_meter.py", '    if not seen or seen["stamp"] != stamp(path):\n        return [], ""', '    if not seen:\n        return [], ""',
     "lines_in_context_is_filtered", "a changed file is not in context"),
    ("work_meter.py", '    if not seen or seen["stamp"] != stamp(path):\n        seen = st["reads"][path]',
     '    if not seen:\n        seen = st["reads"][path]', "lines_in_context_is_filtered", "a changed file read anew"),
    ("work_meter.py", '    if shown_by_rewrite and ran:', '    if False:', "several_gaps_shows_each_and_records",
     "what a filtered read showed, recorded"),
    ("work_meter.py", '    if shown_by_rewrite and ran:', '    if shown_by_rewrite:', "filtered_read_that_did_not_run",
     "a filtered read that did not run"),
    ("work_meter.py", "{','.join(f'{a}-{b}' for a, b in missing)}", "{first}-{end}", "several_gaps_shows_each",
     "a command filtered to what is missing"),
    ("lines.py", '        for i in range(a, min(b, len(lines)) + 1):', '        for i in range(a - 1, min(b, len(lines)) + 1):',
     "lines_in_context_is_filtered", "the lines lines.py shows"),
    ("v2.py", '    missing = work_meter.gaps(known, a, b)\n    left', '    missing = [(a, b)] if b >= a else []\n    left',
     "leaves_out_what_is_in_context", "a read of a source filtered"),
    ("v2.py", '                shown[-1] = (path, shown[-1][1], i)', '                shown[-1] = (path, shown[-1][1], y)',
     "leaves_out_what_is_in_context", "a gather records what it printed"),
    ("v2.py", '            work_meter.saw(wst, path, a, b)', '            pass', "leaves_out_what_is_in_context",
     "a read's own sources filtered"),
    ("v2.py", "name the rest by its lines (`{rel}:{stop}-{b}`)", "name the rest by its lines (`{rel}:{stop + 1}-{b}`)",
     "leaves_out_what_is_in_context", "where a gather's source goes on"),
    ("v2.py", '        with work_meter.meter(c["sid"]) as m:', '        with __import__("contextlib").nullcontext('
     'work_meter.load(c["sid"])) as m:', "read_writes_the_meter_under_its_lock", "the read's lock"),
    ("v2.py", '    lines = re.search(r":(\\d+)-(\\d+)$", src) if src.startswith(("task:", "proposal:")) else None',
     '    lines = None', "every_source_is_a_read", "a task's brief by its lines"),
    ("v2.py", '        return lines_of_text(text, int(a), int(b)) if a else text', '        return text',
     "readers_own_task", "a result, a log and a diff by their lines"),
    ("cut.py", '    if len(data) <= limit:', '    if True:', "every_output_is_cut", "the cutter"),
    ("work_meter.py", 'if t.startswith(trees) and not (here', 'if False and not (here',
     "writes_another_task_s_tree", "a session writing another task's tree"),
    ("v2.py", '        for tid in made:\n            with contextlib.suppress(OSError):\n                os.remove(task_path(tid))',
     '        for tid in []:\n            with contextlib.suppress(OSError):\n                os.remove(task_path(tid))',
     "all_of_it_or_none or takes_back_everything", "the tasks a failed edit made taken out"),
    ("v2.py", '(peek()["tasks"].get(t.get("reviews") or "") or {}).get("stage") == "done")',
     'False)', "subject_has_finished", "the orphaned review"),
    ("v2.py", 'fresh_sweep(st)  # a charge', 'None  # a charge', "drops_the_events_it_supersedes", "fresh_sweep"),
    ("health.py", 'standing(st, now)\n        return\n    if not st["active"]:', 'return\n    if not st["active"]:',
     "restart_meets", "the stopped run's standing state"),
    ("v2.py", 'taken = {tid for tid, t in st["tasks"].items() if (t or {}).get("stage") not in ("ready", None)}',
     'taken = set()', "admitted_again_once_a_slot", "the width's taken set"),
    ("v2.py", '    left = unread(name)', '    left = []', "cannot_be_delivered", "the unread-mail notice"),
    ("v2.py", 'if task is not None and task.get("status") != "completed":',
     'if task is None or task.get("status") != "completed":', "taken_out_of_the_list", "the task gone from the list"),
    ("health.py", 'return "warm_daemon" in open(f"/proc/{pid}/cmdline").read()', 'return True',
     "not_the_daemon", "daemon_alive by name"),
    ("warm_daemon.sh", 'tr \'\\0\' \' \' < "/proc/$p/cmdline" | grep -q warm_daemon', 'true',
     "not_the_daemon", "--ensure by name"),
    ("health.py", 'tended = daemon_alive() and not read("stopped")', 'tended = True',
     "stale_layer", "who refreshes a stale layer"),
    ("ctx_gauge.py", 'if role in v2.PRODUCING:\n            # a producing session holds the slot',
     'if False:\n            # a producing session holds the slot', "whose_work_was_taken_on",
     "the producing session's own stop reason"),
    ("ctx_gauge.py", '\n        blocked_again(session, rec, role)', '\n        None',
     "cannot_end_at_all", "the blocked-turn count"),
    ("work_meter.py", 'if head[:1] == ["v2.py"] or (head[:1] and head[0] in RUNNERS and head[1:] == ["v2.py"]):',
     'if ".claude/orchestration/v2.py" in command:', "rounds_since_production", "v2.py written short"),
    ("v2.py", 'if isinstance(e, OSError) and not os.path.exists(task_path(tid)):', 'if isinstance(e, OSError):',
     "cannot_be_read_is_not_read", "a task file that cannot be read"),
    ("health.py", 'if p in changed and (v2.read_task(t) or {}).get("status") == "completed"}',
     'if False}', "graph_calls_done", "work the repository does not hold"),
    ("v2.py", '        raise RuntimeError(f"{what} ({path}) is there and cannot be read: {e!r}. Nothing writes over it; move it "\n                           "aside only when you know what it should hold.") from e', '        return {}',
     "never_written_over", "a kept file that cannot be read"),
    ("v2.py", '        except OSError as e:\n            # a ledger that is there and cannot be read was replaced by a fresh header and this one entry: every\n            # direction the owner had ever given, gone, under the lock that was meant to protect them. The words are\n            # kept in the log instead and the file is left alone (2026-09-21).\n            log(f"ATTENTION the owner ledger could not be read ({e!r}) and is left untouched. What was said, in "\n                f"full:\\n{entry}")\n', '        except OSError:\n            s = "# Owner ledger"\n',
     "owner_types", "a ledger that cannot be read"),
    ("v2.py", '    if not os.path.exists(path):\n        return ""\n    try:\n        return open(path).read().strip()',
     '    try:\n        return open(path).read().strip()', "hold_whose_file", "a hold that fails closed"),
    ("v2.py", '    except (KeyError, FileNotFoundError):\n        return []      # it never started',
     '    except (KeyError, FileNotFoundError, OSError):\n        return []      # it never started',
     "transcript_that_cannot_be_read", "a transcript that cannot be read"),
    ("watchdog.py", '    if model == "<synthetic>" and re.search(r"hit your .*limit", said, re.I):\n        if time.time()',
     '    if False and re.search(r"hit your .*limit", said, re.I):\n        if time.time()',
     "usage_limit", "the limit before the mail"),
    ("efficiency.py", '            if s:\n                # a fork', '            if s and name is None:\n                # a fork',
     "own_launch_prompt", "a fork measured as itself"),
    ("v2.py", 'if t.get("stage") in ("planner", "unformed") or reopened:', 'if t.get("stage") in ("planner", "unformed"):',
     "puts_back_to_pending", "a task the planner re-opens"),
    ("v2.py", 'judge = stage == "reviewing" and t.get("kind") not in ("build", "fix")', 'judge = False',
     "waiting_for_the_planner_s_verdict", "a design waiting for a verdict"),
    ("v2.py", 'stopped = os.path.exists(os.path.join(STATE, "stopped")) and', 'stopped = False and',
     "start_then_stop_then_start_again", "nothing starts while the run is stopped"),
    ("work_meter.py", 'if any(t.startswith(graph) for t in targets):', 'if False:',
     "written_by_no_session", "a task file written by hand"),
    ("work_meter.py", 'if any(t.startswith(h) for t in targets for h in harness) or any(', 'if False or any(',
     "harness_s_own_files", "the harness edited by a session"),
    ("work_meter.py", '    if c and any(os.path.basename(w.strip("\'\\"`")) == "claude" for words in segments(shell_syntax(c)) for w in words[:1]):', '    if False:',
     "starts_no_session", "a session starting a session"),
    ("work_meter.py", 'if raw.endswith((".py", ".sh")) and under and os.path.basename(path) not in ("v2.py", "show.py"):',
     'if False:', "harness_s_own_scripts", "the harness's own scripts run by a session"),
    ("watchdog.py", 'if r["activity"] not in ("busy", "idle"):', 'if False:',
     "supervisor_no_longer_runs", "a session listed but not run"),
    ("v2.py", '    age = age_of(mark)\n    if age is not None and age < RETRY:\n        return None\n', '',
     "not_confirmed_is_not_tried", "the backoff after a start nobody confirmed"),
    ("v2.py", '        if task is None and in_list(tid):\n            continue  # there and unreadable', '        if False:\n            continue  # there and unreadable',
     "not_said_to_be_out_of_the_list", "an unreadable file called a missing task"),
    ("v2.py", 'if c and c["role"] != "planner" and q.get("session") != c["name"]:', 'if False:',
     "planner_tells_a_working_session", "who may answer a question"),
    ("v2.py", 'if not c or c["role"] not in PRODUCING or not c.get("task"):', 'if not c or not c.get("task"):',
     "timing_run_takes_the_machine", "who may claim the machine"),
    ("v2.py", 'missing = [tid for tid in ids if not in_list(tid)]\n    if missing:', 'missing = []\n    if missing:',
     "names_nothing_is_refused", "an order naming a task that is not there"),
    # every output bounded, the gather a read, the tokens gone (the owner, 2026-09-21)
    ("work_meter.py", "{'tail' if k == 'check' else 'head'}", "{'head'}", "check_shows_its_end", "a check shows its end"),
    ("cut.py", '        path, failed = keep(directory, data), None', '        path, failed = None, "x"', "every_output_is_cut",
     "the whole output kept"),
    ("cut.py", '        return data[:i], int(data[i + 2:].strip())', '        return data[:i], 0', "check_shows_its_end",
     "a cut command's status"),
    ("cut.py", '        part = data[-limit:]', '        part = data[:limit]', "check_shows_its_end", "the end a check shows"),
    ("cut.py", '    on = shown + 1 if head.endswith(b"\\n") else shown', '    on = shown + 2 if head.endswith(b"\\n") else shown',
     "every_output_is_cut", "where an output is read on"),
    ("work_meter.py", '        inp = dict(inp, command=unwrapped(inp["command"]))', '        pass',
     "recorded_as_the_call_the_session_made", "a cut call recorded as made"),
    ("work_meter.py", '    return prefix + body if runner or WRAPPED.match(command) else command', '    return command',
     "every_output_is_cut", "a cut call unwrapped"),
    ("work_meter.py", ' or KEPT.search(text)', ' or None', "check_shows_its_end", "a check judged on its whole output"),
    ("work_meter.py", '            or (own_command(c) and re.search(r"\\bv2\\.py\\s+read\\b", c)):', '            or False:',
     "every_output_is_cut", "v2.py read not cut again"),
    ("work_meter.py", '    c = inp.get("command") or ""\n    if tool != "Bash" or not c.strip()',
     '    if k not in ("read", "other"):\n        return None\n    c = inp.get("command") or ""\n    if tool != "Bash" or not c.strip()',
     "every_output_is_cut", "every kind of command cut"),
    ("v2.py", '    tid = c and (c.get("reviews") or c.get("task"))', '    tid = c and c.get("task")', "readers_own_task",
     "a reviewer reads what it reviews"),
    # Grep, Glob, WebFetch and WebSearch taken out of every base, and nothing forked from a base with other tools
    ("work_meter.py", '    if tool in REMOVED_TOOLS:\n        return deny(', '    if False:\n        return deny(',
     "removed_tools_are_in_no_session", "the removed tools refused"),
    ("v2.py", '    if other_tools(org):\n        say_once(', '    if False:\n        say_once(', "other_tools",
     "no fork of what has other tools"),
    ("v2.py", '    if other_tools(s):  # the ping', '    if False:  # the ping', "other_tools", "no ping of it either"),
    ("v2.py", 'flags=" ".join(session_flags()), **fields)', '**fields)', "other_tools", "a session's flags recorded"),
    ("v2.py", '    return (rec or {}).get("flags") != " ".join(session_flags())', '    return False', "other_tools",
     "the flags compared"),
    ("v2.py", '"flags": b.get("flags")}', '"flags": " ".join(session_flags())}', "other_tools", "a base's flags read"),
    ("base.sh", '    lean_as "$forked" || {', '    true || {', "other_tools_is_not_pinged", "base.sh's ping of it"),
    # one command changes files; every other content write refused; checks stop at their first error; the tools that
    # are a session's are Bash, TaskCreate, TaskUpdate and TaskStop (the owner, 2026-09-21)
    ("v2.py", 'if count == 0 or (count > 1 and op["op"] == "replace"):', 'if count == 0:', "replacement_must_be_unique",
     "a replacement unique"),
    ("v2.py", '-1 if op["op"] == "replace-all" else 1)', '1)', "replace_all_takes_every_one", "replace-all"),
    ("v2.py", '    now, at, problems = changed_texts(ops, base)\n    if problems:', '    now, at, problems = changed_texts(ops, base)\n    if False:',
     "nothing_is_written", "a change refused whole"),
    ("v2.py", '                    open(path, "wb").write(was)', '                    pass', "failure_part_way_puts_back",
     "a file put back"),
    ("v2.py", '                if was is None:\n                    os.remove(path)', '                if was is None:\n                    pass',
     "failure_part_way_puts_back", "a file made taken out"),
    ("v2.py", 'written all or none.]" if len(ops) == 1 else "")', 'written all or none.]" if False else "")',
     "told_to_batch", "the note to batch"),
    ("v2.py", '                shutil.copymode(path, tmp)', '                pass', "keeps_its_mode", "a file's mode kept"),
    ("v2.py", '            if was is not None and was == new.encode("utf-8"):\n                continue',
     '            if False:\n                continue', "unchanged_one_is_not_touched", "an unchanged file left alone"),
    ("v2.py", '        if path not in now:\n            try:', '        if True:\n            try:',
     "changes_to_many_files_in_one_call_in_order", "each change on what the one before left"),
    ("v2.py", '            if body[j] != SEARCH:', '            if False:', "form_is_said", "a block's form"),
    ("work_meter.py", '            return "write"  # the one way a session changes files', '            return "own"  # x',
     "change_is_a_write", "a change is a write"),
    ("work_meter.py", '        return list(dict.fromkeys(v2.change_path(where,', '        return list(dict.fromkeys(v2.change_path(cwd,',
     "exactly_its_files", "a change's files where it stands"),
    ("work_meter.py", '    if not how:\n        return None', '    if True:\n        return None', "every_other_way_of_writing",
     "other content writes refused"),
    ("work_meter.py", '        if not call:\n            return ("`v2.py change` takes',
     '        if False:\n            return ("`v2.py change` takes', "one_form_is_a_quoted_heredoc", "the change's one form"),
    ("work_meter.py", '        if not call[1]:', '        if False:', "one_form_is_a_quoted_heredoc", "a quoted heredoc"),
    ("work_meter.py", '    if k == "write":  # where it writes first', '    if False:  # where it writes first',
     "judged_before_how", "where before how"),
    ("work_meter.py", 'CHECK.search(HEREDOC.sub(" ", c))', 'CHECK.search(c)', "run_to_list_every_error",
     "prose naming a check"),
    ("work_meter.py", '    if k == "check":\n        body = gathering(', '    if False:\n        body = gathering(',
     "ends_by_listing_every_error", "a check run to list its errors"),
    ("work_meter.py", '        return allow(dict(inp, command=prefix + body)) if k == "check" else None', '        return None',
     "run_to_list_every_error", "a background check run to stop"),
    ("work_meter.py", 'LOGGED = re.compile(r"--(?:work|output)', 'LOGGED = re.compile(r"--(?:nothing)',
     "run_to_list_every_error", "where a check logs"),
    ("work_meter.py", '            body = shlex.split(runner.group(1))[0]', '            pass',
     "run_to_list_every_error", "a check unwrapped"),
    ("work_meter.py", 'if tool in ("ToolSearch", "TaskStop"):', 'if tool in ("ToolSearch",):', "stopping_its_own_job",
     "TaskStop the session's own"),
    ("work_meter.py", ' {REMOVED_TOOLS[tool]}")', '")', "removed_tools_are_in_no_session", "where a tool's work goes"),
    ("work_meter.py", '        if spent and not (targets and all(t.endswith(result) for t in targets)):', '        if spent:',
     "quick_fix_has_its_own_budget", "a spent fix may still record its result"),
    ("base.sh", 'record = dict(sessionId=sid, model=model, effort=effort, name=name, flags=flags)',
     'record = dict(sessionId=sid, model=model, effort=effort, name=name)', "build_packed", "a base's flags recorded"),
    # a command that went wrong is fixed, not written again (the owner, 2026-09-21)
    ("work_meter.py", '        kept = keep_command(rec.get("name"), inp["command"])', '        kept = None',
     "every_command_is_kept", "every command kept"),
    ("work_meter.py", '        if fixed:  # guarded, rewritten and counted', '        if False:  # guarded, rewritten and counted',
     "again_runs_the_kept_command_fixed", "again applied"),
    ("work_meter.py", '        if why:\n            return deny(why)', '        if False:\n            return deny(why)',
     "again_is_refused_loudly", "again refused"),
    ("work_meter.py", '    if denied and kept and fixable:', '    if denied and kept:', "refused_one_says_how_to_fix_it",
     "only a fixable refusal told to fix"),
    ("work_meter.py", '        said["permissionDecisionReason"] += " " + fix_note(kept)', '        pass',
     "refused_one_says_how_to_fix_it", "a refusal told how to fix"),
    ("work_meter.py", '    if fixed and not denied and "updatedInput" not in said:\n        refused = allow(inp)',
     '    if False:\n        refused = allow(inp)', "again_runs_the_kept_command_fixed", "a fixed command run when uncut"),
    ("work_meter.py", '    inp = {"command": resolved[call.get("id")]} if call.get("id") in (resolved or {}) else call.get("input") or {}',
     '    inp = call.get("input") or {}', "again_call_counts", "an again call counted as what it ran"),
    ("work_meter.py", '    if tool == "Bash" and resolved:  # a `v2.py again` call', '    if False:  # a `v2.py again` call',
     "again_call_counts", "an again call recorded as what it ran"),
    ("work_meter.py", '                    st["resolved"] = dict(st.get("resolved") or {}, **{hook["tool_use_id"]: fixed})',
     '                    st["resolved"] = {}', "again_call_counts", "what an again call ran, kept"),
    ("work_meter.py", '    if not m.group(4).strip():  # no correction', '    if False:  # no correction',
     "again_runs_the_kept_command_fixed", "again as it was"),
    ("work_meter.py", '        problems += [problem] if problem else []', '        problems += [problem] if problem else []\n        break',
     "again_is_refused_loudly", "every block of again judged"),
    ("cut.py", '    note = fix_note(kept, status) if kept and status else ""', '    note = ""',
     "ended_failing_is_told", "a failed command told how to fix"),
    ("work_meter.py", 'if kept and k != "check" and not answers(body)', 'if kept and not answers(body)',
     "ended_failing_is_told", "a check not told to fix its command"),
    ("v2.py", '        return 1 if said.startswith("refused") else 0', '        return 0', "ended_failing_is_told",
     "a refused change reads as failing"),
    ("check_errors.py", '    errors = errors_in(output) + [e for', '    errors = [] + [e for', "lists_every_error_last",
     "the errors of a check's output"),
    ("check_errors.py", '[e for _, text in logs_read for e in errors_in(text)]', '[]',
     "logs_it_wrote_are_gathered", "the errors of the logs it wrote"),
    ("check_errors.py", '                if os.path.getmtime(log) >= since:', '                if True:',
     "an_old_log_is_not", "another run's log"),
    ("check_errors.py", '    errors = list(dict.fromkeys(errors))', '    errors = list(errors)', "is_one_error",
     "one error in output and log"),
    ("check_errors.py", '        if size > ROOM:\n            break', '        if False:\n            break',
     "long_list_shows_what_fits", "a long list bounded"),
    ("check_errors.py", '            open(path, "w").write(', '            (lambda *a: None)(', "long_list_shows_what_fits",
     "a long list kept whole"),
    ("check_errors.py", 'if m and line.startswith("At command")),', 'if False),', "stands_is_its_command",
     "where an error stands"),
    ("check_errors.py", '    return status', '    return 0', "lists_every_error_last", "a check's own status"),
    ("v2.py", '    shutil.rmtree(outputs_of(name), ignore_errors=True)  # its kept outputs', '    pass  # its kept outputs',
     "released_one_nothing", "what a session keeps goes at release"),
    ("v2.py", 'os.path.join(STATE, f"work-{sid}.json.lock"),', '', "released_one_nothing", "the meter's lock goes too"),
    ("work_meter.py", "sorted(int(f[:-3]) for f in os.listdir(folder) if f.endswith(\".sh\") and f[:-3].isdigit())[:-KEPT_COMMANDS]",
     "[]", "keeps_its_newest_commands", "the newest commands kept"),
    # what the restrictions left undoable (the owner's pass, 2026-09-21)
    ("v2.py", '    refused = planner_only("a question in the owner ledger")\n    if refused:\n        return refused',
     '    refused = None\n    if refused:\n        return refused', "puts_a_question_to_the_owner", "the ledger the planner's"),
    ("v2.py", '        n = 1 + max((int(x) for x in re.findall(r"^\\*\\*Q(\\d+)\\b", s, re.M)), default=0)',
     '        n = 1', "puts_a_question_to_the_owner", "a question numbered on"),
    ("v2.py", '             else s[:end + 1] + entry + s[end + 1:])', '             else s + entry)',
     "goes_before_a_section_that_follows", "a question under its section"),
    ("v2.py", '    return lines_of_text(text, int(m.group(2)), int(m.group(3))) if m.group(2) else text', '    return text',
     "fact_is_read_by_its_lines", "a fact by its lines"),
    ("work_meter.py", '    if any((full + os.sep).startswith(os.path.join(d, "")) for d in own):\n        return False',
     '    if False:\n        return False', "reads_its_own_drafts", "a reader's own drafts"),
    ("work_meter.py", '    if targets and all(scratch(t) for t in targets):  # a program', '    if False:  # a program',
     "every_other_way_of_writing", "a command's output under .build"),
    ("work_meter.py", '    return rel.startswith(".build/") and not rel.startswith((".build/trees/", ".build/outputs/"))',
     '    return rel.startswith(".build/")', "every_other_way_of_writing", "not a tree's, not the harness's records"),
    ("work_meter.py", 'r"|stash(?!\\s+(?:list|show)\\b)', 'r"|stash', "reading_forms_stand", "git's reading forms"),
    ("work_meter.py", '    text = re.sub(r"&>", " >", re.sub(', '    text = (lambda a, b, c: c)(r"&>", " >", re.sub(',
     "every_other_way_of_writing", "&> a redirection"),
    ("work_meter.py", 'if kept and k != "check" and not answers(body)', 'if kept and k != "check"',
     "found_nothing_is_not_told", "a search's answer no failure"),
    ("cut.py", '    if end == "tail" or status:  # a failure', '    if end == "tail":  # a failure',
     "failing_command_shows_its_end", "a failed command's end"),
    ("cut.py", '        before = said_before(data, first) if status else None', '        before = None',
     "failing_command_shows_its_end", "a failure said before the end, quoted"),
    ("check_errors.py", '    if status:  # a failed check says what else failed', '    if False:  # a failed check says what else failed',
     "lists_what_else_failed", "what else failed"),
    ("check_errors.py", '    if not isinstance(row, dict) or row.get("status") != "failed":',
     '    if not isinstance(row, dict):', "lists_what_else_failed", "only what failed"),
    ("check_errors.py", '            out.append(f"the check: {str(row[\'error\'])[:200]}")', '            pass',
     "lists_what_else_failed", "the check's own error"),
    ("check_errors.py", '        said = last_failure(text) if path not in used else None', '        said = None',
     "lists_what_else_failed", "a log that ends on a failure"),
    ("finalize.py", '    check = work_meter.gathering(fresh_output(tid, spec["check"], cwd), cwd, os.path.join(d, "run-errors"))',
     '    check = fresh_output(tid, spec["check"], cwd)', "failed_check_gets_one_quick_fix",
     "the finalizer's check lists its errors"),
    ("check_errors.py", '        if body.strip().startswith("At command"):\n            close()',
     '        if False:\n            close()', "without_a_place_of_its_own", "a message ends at its command"),
    # the sandbox (2026-09-21): what a session cannot do there is asked of the supervisor, never half done
    ("v2.py", '        want(release=name)\n        log(f"{name} is to be released: asked of the supervisor, which can '
     'stop it")\n        return\n', '        pass\n', "a_drop_inside_asks_the_supervisor", "release inside the sandbox"),
    ("v2.py", '        return  # it stays in the box: the watchdog opens every box',
     '        pass  # it stays in the box: the watchdog opens every box', "a_message_inside_waits",
     "hand_mail leaves the mail to the watchdog inside the sandbox"),
    ("v2.py", '    if not control():\n        want(key="dispatch", run=["v2.py", "dispatch"])\n        return\n', '',
     "nothing_dispatches_inside", "no dispatch inside the sandbox"),
    ("v2.py", '        want(key="dispatch" if (script, args) == ("v2.py", ("dispatch",)) else None, run=[script, *args])'
     '\n        return\n', '        pass\n', "a_background_run_is_asked_of_the_supervisor",
     "background asks the supervisor inside the sandbox"),
    ("v2.py", 'if ("--bg" in args or args[:1] in (("stop",), ("rm",))) and not control():', 'if False:',
     "a_background_run_is_asked_of_the_supervisor", "claude() refuses session control inside the sandbox"),
    ("v2.py", 'if c in ("start", "stop", "talk", "ping") and not control():', 'if False:',
     "owner_s_commands_refuse_inside", "the owner's commands refuse inside the sandbox"),
    ("warm_daemon.sh", "grep -q '\\.json$' && [ ! -e \"$STATE/stopped\" ] && active && break", 'false',
     "wakes_the_sleeping_daemon", "a request wakes the daemon"),
    # the sandbox's process namespace (2026-09-21): what a command there cannot see is judged by what can
    ("v2.py", '    if claim.get("pid") and not control():\n', '    if False:\n',
     "claim_whose_process_cannot_be_seen", "a claim inside the sandbox is not cleared"),
    ("v2.py", '    if not control():\n        # inside Claude Code\'s sandbox no other run is visible', '    if False:\n        #',
     "measurement_inside_is_decided_by_the_supervisor", "measuring inside asks the supervisor"),
    ("v2.py", '                    deliver(c["name"], "the harness", measure_claim(c, request.get("text") or ""))',
     '                    pass', "measurement_inside_is_decided_by_the_supervisor", "the supervisor decides a measurement"),
    ("health.py", '    if not v2.control():\n        try:\n            beat', '    if False:\n        try:\n            beat',
     "reads_the_daemon_by_its_heartbeat", "health reads the heartbeat inside the sandbox"),
    ("warm_daemon.sh", 'do touch "$STATE/warm.beat";', 'do :;', "reads_the_daemon_by_its_heartbeat",
     "the daemon's heartbeat"),
]
bad = []
for fname, old, new, k, label in CASES:
    src = open(fname).read()
    if src.count(old) != 1:
        bad.append(f"{label}: anchor not unique ({src.count(old)})"); continue
    shutil.copy(fname, fname + ".bak")
    try:
        open(fname, "w").write(src.replace(old, new))
        # no bytecode: Python's cache is keyed by a file's modified second and its size, and this rewrites the same
        # files several times a second, so a test could run an earlier mutant or the original — a mutation it did
        # catch alone read as missed in the full run (2026-09-21)
        shutil.rmtree("__pycache__", ignore_errors=True)
        r = subprocess.run([sys.executable, "-B", "-m", "pytest", "-q", "-p", "no:cacheprovider", "-k", k]
                           + [f for f in os.listdir(".") if f.startswith("test_") and f.endswith(".py")],
                           capture_output=True, text=True, env=dict(os.environ, PYTHONDONTWRITEBYTECODE="1"))
        last = r.stdout.splitlines()[-1] if r.stdout.strip() else ""
        caught, broken = "failed" in last, "error" in last and "failed" not in last
        print(f"  {'CAUGHT ' if caught else 'BROKEN ' if broken else 'MISSED '} {label}")
        if broken: bad.append(f"{label}: the mutation broke the import rather than the repair; write another")
        elif not caught: bad.append(f"{label}: the mutation was not caught")
    finally:
        shutil.move(fname + ".bak", fname)
print()
print("\n".join("  ! " + b for b in bad) or "  every mutation was caught")
